### ISSUE TITLE
Raid activities are being logged as mode 0

### ISSUE THREAD

**Issue by v-fedorov** [Bungie-net/api#101]
Sample ids

```
# instanceId, period, mode, map
251765825, 2017-09-13 17:00:30, 0, 2693136601
251765865, 2017-09-13 17:01:49, 0, 2693136601
251767003, 2017-09-13 17:01:05, 0, 2693136601
251767100, 2017-09-13 17:00:52, 0, 2693136601
251767204, 2017-09-13 17:01:11, 0, 2693136601
251767303, 2017-09-13 17:01:37, 0, 2693136601
251768254, 2017-09-13 17:01:17, 0, 2693136601
251768666, 2017-09-13 17:01:17, 0, 2693136601
251768934, 2017-09-13 17:00:41, 0, 2693136601
251769122, 2017-09-13 17:01:25, 0, 2693136601
251769409, 2017-09-13 17:00:48, 0, 2693136601

```

**Comment by vthornheart-bng** [comment]
Ah, junk.  I'll have to investigate that, sorry guys.

**Comment by vthornheart-bng** [comment]
Turns out that I was expecting the Raid Activity Mode to be un-redacted, but I missed that: it was still redacted in the content going live today.

It will be fixed tomorrow when we un-redact all Raid-related content... unfortunately, that means that for today all Raid PGCRs will be coming back as mode 0.  I apologize for this, it's a definite bummer and a miss on my part for not noticing that it was still redacted before we green lit for today's ship.

**Comment by v-fedorov** [comment]
no worries its not your fault, its all these damn redactions *shakes fist*

**Comment by vthornheart-bng** [comment]
I should have been paying more attention to the implications of this particular redaction and gotten it un-redacted early alongside that Enum.  That was totally a miss on my part... we've got a boatload of redactions, but this one was important in a different way than redactions usually are due to this Stats dependency.  Lessons learned!

**Comment by vthornheart-bng** [comment]
This should be resolved as of yesterday.  Try it now.
