### ISSUE TITLE
Add activity reference id to current activity data

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1017]
Currently, it is possible to detect a users current activity via:
 
https://www.bungie.net/Platform/Destiny2/1/Profile/4611686018429783292/?components=204

and checking the following properties.

currentActivityHash
currentActivityModeHash
currentActivityModeTypes

However, it does not appear possible to link the current activity with an ID so it can be matched with activities via:

https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429783292/Character/2305843009264966985/Stats/Activities/?mode=5&count=1

Responses to the Activities call include an ID that uniquely identifies the activity.

Would it be possible to include the activity ID in the Profile call? This would make it possible to link the current activity, with the archived activity (once it is completed).

(I understand the ID may not be created until the activity is completed, but if it is created, it would be useful to have a reference to it in the Profile call).

**Comment by vthornheart-bng** [comment]
Aye - unfortunately, the ID is indeed not created until the activity is completed - in truth, up to several minutes after it's been completed.  There's a couple of things that would make pushing it back infeasible unfortunately: one is that by the time it's generated, it's no longer the current activity.  I could see a world where we have some info about the last activity played, but the other problem is that it'd be a pretty significant set of infrastructure work to get the live game servers to know about recent activities in the stats system that generates IDs.

Because of those issues, this one is unfortunately not one we'll be able to do unless there's a pretty significant change to how Destiny processes and uses stats.  Sorry about that!

**Comment by mikechambers** [comment]
@vthornheart-bng Thanks. That is what i figured. Im currently trying to match by hashing activity mode and location (in my case pvp map name and game type), but of course, that is not 100% reliable.

**Comment by floatingatoll** [comment]
What % reliable is it? 90, 60, 5?

**Comment by mistahj67** [comment]
!pvp scry via Charlemagne?

**Comment by mikechambers** [comment]
@floatingatoll In my case, It depends on the pvp playlist, and the frequency that you will get the same map, and game mode twice in a row.

@mistahj67 Im a big charlemagne fan, but im not asking how to detect current activity (I know how to do that). I am requesting a way to link the current activity, with a future activity report. Appears to be not current possible with certainty..

**Comment by vthornheart-bng** [comment]
Yes, unfortunately it's a tough one.  The best you could likely do is after the fact, if you're looking to match PGCR data to it.  You could take the time that you saw them playing, and then look for a PGCR whose active time has that time fall into the range.  But it's definitely janky, and would require you to not actually care until after the activity has ended. :(

**Comment by Suckitup** [comment]
I know this thread is incredibly old, and I do not post a lot. But is this still the case? (After the updates to servers and the entire game itself I mean?) I am looking to do something to help people out who have difficulty with symbols, (which is a medical condition) for the raid in real-time or even location on a map to start. Eventually, I would like to help with something to figure out which symbols were going to pop up near linked guardian
