### ISSUE TITLE
50pt Triumph score mystery

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#1025]
I think this has been discussed in the past, but not sure it was ever solved. It seems that in some cases given two players with 100% identical triumph lists, one player will have a Triumph score 50 pts higher than another. 

Someone on reddit has invested some decent time and effort investigating this and is offering to gather data if it's helpful. If this has already been solved and explained I'd hate to have them waste time (on the other hand, if not, this could be very helpful).

https://old.reddit.com/r/DestinyTheGame/comments/cs6ij7/how_to_check_for_the_50_point_triumph_score_bug/

**Comment by delphiactual** [comment]
https://old.reddit.com/r/DestinyTheGame/comments/cy8psb/doubts_about_shadowkeep/eyqjk5z/

**Comment by floatingatoll** [comment]
Does the API return a detailed breakdown of what is contributing the points for analysis, or does it simply return two different numbers for two such players?

**Comment by delphiactual** [comment]
`Season 4: Armor` initially was worth 50pts it no longer is worth any points... Anyone how redeemed it prior to the point reduction, kept their points.

**Comment by dcaslin** [comment]
> `Season 4: Armor` initially was worth 50pts it is no longer is worth any points... Anyone how redeemed it prior to the point reduction, kept their points.

Mystery solved, thanks!

**Comment by 3jlowes** [comment]
> Season 4: Armor initially was worth 50pts it is no longer is worth any points... Anyone how redeemed it prior to the point reduction, kept their points.

Mystery unsolved sadly. I have some concrete proof from CSV's downloaded using D2 Checklist.
Season 4: Armor is row 1019 and I myself J3lowes#1538 have the 50 points bug despite not having the triumph. Included in the workbook is SneakyBeaver#11271 and  Scattrx#1574 and my data from D2 Checklist.

The same info from the spreadsheet, just on the website showing I do not own the Season 4: Armor triumph despite having a bonus 50 points.
J3lowes: https://www.d2checklist.com/4/J3lowes%231538/triumphs/tree/1473714136
https://www.d2checklist.com/4/SneakyBeaver%2311271/triumphs/tree/1473714136

Here is the workbook with the three profiles referenced
[50TriumphMystery.xlsx](https://github.com/Bungie-net/api/files/3564553/50TriumphMystery.xlsx)

If you see this, thanks for taking your time to read my post. Hopefully we can get to the bottom of this.

**Comment by floatingatoll** [comment]
Does the Bungie.net website show the same value for your current Triumph score as is shown in-game, or are they 50 points different?

**Comment by 3jlowes** [comment]
Bungie.net is showing the same triumph score as the one in-game. When I went to add up the total triumph score in the spreadsheet download from D2 Checklist, the 50 points were gone from both people with the bug.

**Comment by floatingatoll** [comment]
So, that implies that this is not an API issue, but an in-game issue. You may not find that the API team is able to help you answer this question, but presumably you’ve already opened a Help thread on the official Bungie forums by now; linking it here would be useful for others.

Do you have the same spreadsheet for a player that has the extra 50 points showing? If you sort both spreadsheets by Triumph name, do they have the same number of rows or does one of them have one more row than the other?

You may need to resort to inspecting every single triumph in someone’s collection in-game, both one who has the +50 and one who does not, in order to find this - but unless you can find evidence that the API is somehow providing information that does not match that provided in-game, I suspect they won’t be able to help here.

**Comment by xXBigRedXx** [comment]
Hi all, new to GitHub, just created an account to comment on this.

I manually added my triumphs one by one about a month ago, and double checked each subsection's total against D2checklist's subcategory totals to make sure all checked out.

All triumphs present when summed up via their reported score in game will result in 93,800. I have Season 4: Armor and it is listed at 0 points. So the fact that my points sum up correctly to my API and in game total suggests that it not the cause.

Also, I had another friend manually add up there triumphs in a similar way. They're total is 93,800 when added manually but reported as 93,750 in game and the API.

**Comment by vthornheart-bng** [comment]
Hey folks!  Okay, I filed a bug on it to investigate when we get the time to do so, TFS 826538.

**Comment by bladesandaxes** [comment]
We believe we figured out what triumph was causing it [here](https://www.reddit.com/r/DestinyTheGame/comments/cz93d2/50_missing_triumph_points_and_where_they_are_from/) if you want to look into it

**Comment by darkzimpulse** [comment]
Pretty much nailed the issue down, explanation can be found at the link below.

https://www.reddit.com/r/DestinyTheGame/comments/cz93d2/50_missing_triumph_points_and_where_they_are_from/

The bug most likely comes from turning in the IO adventurous triumph when it was 0 points. A week later it was changed to 50 but did not register retroactively to people who already had the triumph turned in.

**Comment by vthornheart-bng** [comment]
Damn fine sleuthing there!  I'll bubble it up - unfortunately this might not be something we can feasibly fix.  Ideally those numbers should have been kept fixed, because there's not really a process that exists which can do a post-facto points fixup.  But I'll hit people up and see what they think about it.
