### ISSUE TITLE
Some hashes are removed from the DB and Milestones after the new update

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#1028]
After yesterdays update these hashes are missing from both Db and public milestones.

Current known missing hashes
```
2853331463: weekly nightfall score
3082135827: Daily Heroic Story
1300394968: Heroic Adventure
```

**Comment by mrphlip** [comment]
Daily heroic story `3082135827` and heroic adventure `1300394968` are also missing from the public milestones.

Possible there might be others too, but those are the three I'm interested in that are missing.

**Comment by SarKurd** [comment]
i don't use those in my app that's why i didn't notice.

**Comment by kdeun1** [comment]
I have also confirmed that it is missing.

**Comment by vthornheart-bng** [comment]
We'll be investigating this shortly, thanks for the report!

**Comment by kdeun1** [comment]
It still seems to be fixed. Please check again.

**Comment by landervervaeke** [comment]
@kdeun1 I'm still having this issue. Are you using other hashes?

**Comment by justrealmilk** [comment]
This is still under investigation. pls wait

**Comment by justrealmilk** [comment]
I've been looking at using character activities to determine nightfalls and I've noticed through some pain that the activity mode type for all nightfalls since the community even started are 16. 

There aren't definitions for all nightfalls under type 16. Mode type 46 on the other hand...

Thought I'd note it in case it helped.
