### ISSUE TITLE
OpenAPI files are pretty large

### ISSUE THREAD

**Issue by stevelatta** [Bungie-net/api#1043]
Are there any good options for breaking up the swagger files? I'm working with some tools that don't like anything over 1M.

**Comment by ROMVoid95** [comment]
As far as my personal past with these files knows, there is not a easy way to do this. What tools do you happen to be working with? 

One option (what i am currently doing) is creating my own swagger spec with the endpoints / defs i need and making sure its within the OpenAPI specifications. Mainly because the ones provided throw some weird errors when generating clients for Java in particular.

**Comment by vthornheart-bng** [comment]
Oy, yeah that is totally understandable.  I don't know if I'm going to ever find the time to actually bump this up to the top of my queue (or most of the other other swagger spec-related requests unfortunately), but let me file it so that if we ever can loop back to it we do so.

There's definitely issues with our swagger spec - if you use the spec tag you can see them, which'll give you an idea of some of the pitfalls as you try to use it.  I apologize for the pain that this causes.  

A side benefit if you work around these, however, is that you can also build in your own support for the extension tags we provide, that will let you more easily get information such as enumeration string-to-value mappings, relationships between hash properties and the definitions they point to, etc...
