### ISSUE TITLE
Throttling does not populate ThrottleSeconds

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1051]
<img width="590" alt="Screen Shot 2019-10-01 at 8 37 13 PM" src="https://user-images.githubusercontent.com/313208/66016386-4faf8200-e48b-11e9-9a5c-c4a69dfc58c4.png">

I'd like DIM to be a good citizen and back off requests by the amount set in `ThrottleSeconds` when the API responds that we're throttled. Unfortunately this property always seems to be 0.

**Comment by justrealmilk** [comment]
I think it’s because it’s a fake throttle as the API for third parties is just off rn

**Comment by bhollis** [comment]
Does that maybe mean 0 is "come back later, I don't know when"?

**Comment by YourFavoritePerson** [comment]
I dont think ive ever seen it not be 0.  Pretty sure 0 means not throttled (at least in that way).

**Comment by vthornheart-bng** [comment]
I'll check on this - we do have some new throttles that we can apply in emergency situations, and last week was certainly a time where we turned them on... I'll check out if those throttles aren't setting that response property as they ought to.

**Comment by vthornheart-bng** [comment]
TFS 838483

**Comment by Achronos-BNG** [comment]
This issue has been fixed in the following ways:

- ThrottleSeconds will now be populated with an integer value of how many seconds you should wait to clear your particular throttle value.  This will almost always be 10 seconds in the current runtime config, as if you're getting throttled we're going to make you wait a full "cycle" for the request counters to clear.  Applies to ErrorCodes PerApplicationThrottleExceeded, PerApplicationAuthenticatedThrottleExceeded, PerEndpointRequestThrottleExceeded,PerUserThrottleExceeded,  and PerApplicationAnonymousThrottleExceeded.    I also added a value called MaximumRequestsPerSecond that will indicate the approximate rate that will get you throttled to the exceptions MessageData dictionary.  These changes will go live sometime in the beginning of March.
