### ISSUE TITLE
Can't get Destiny2 profile information for B.Net linked accounts

### ISSUE THREAD

**Issue by AJMcKane** [Bungie-net/api#106]
(I'm copying this as I ended up on the wrong repo somehow when I posted it first)

Hi, I'm currently setting up a raid planner of sorts for my clan, POC'ing it via google sheets (so CORS requests being fired via that), however it seems the api endpoints I want to hit are all on 'http://www.bungie.net/d1/Platform/Destiny/' rather than the user, but I can't find any documentation that allows me to get a user's membership type from their Bungie.net ID.
For example: http://www.bungie.net/Platform/User/GetBungieNetUserById/15362416/ returns my public profile info, but there's no membershiptype value, and the github link I found on another thread had them written out into a enum didn't include the Battle.net value.
So if I hit: http://www.bungie.net/d1/Platform/Destiny/254/Account/15362416/Summary/ I get an invalid parameter error (which makes sense as the API docs say the {membershiptype} should be non bungie, but my profile page lists me as /254/15362416/
Halp?

Update: I've cloned that from my post, but I realise the destiny2 api runs on a different URL, however if I hit: https://bungie.net/Platform/Destiny2/254/Profile/15362416/ I get the same issue. I'm still assuming because my membership type is "254" and the API requires a non-bungie api value?

Update 2: After speaking to Tetron, I was pointed at the following method. https://www.bungie.net/Platform/User/GetMembershipsById/15362416/254/

This has worked, but then if I invoke:
https://www.bungie.net/Platform/Destiny2/4/Profile/4611686018467302689/

Where 4 is the returned membershiptype value and the bigint is the destinymembership I'd I still receive error code 18.

**Comment by iBotPeaches** [comment]
I'm not aware of any PC stat endpoints working yet. 

4 = `PC`
2 = `PSN`
1 = `XBL`

Which might explain the error. You also need to add `components` query string to the Profile endpoint otherwise you will get 0 data. Also, if users aren't signing in and don't require any authentication endpoints. You can just use this flow.

```
Destiny2/SearchDestinyPlayer/all/iBot/?lc=en (251.27ms)
Destiny2/1/Profile/4611686018430553461/?lc=en&components=100,103,200,202,205,300 (698.44ms)
Destiny2/1/Account/4611686018430553461/Stats/?lc=en&groups=1,102,2 (1.75s)
```

I'm searching for all users known as `iBot`, then that returns both a PSN/XBL account, thus changes that `1` in the next request. I ask for tons of components (stats, activities, progressions, characters, equipment)

then aggregate stats below.

**Comment by vthornheart-bng** [comment]
Did that successfully resolve your issue?  I think this should be good to go - I'm going to close it for now, let me know if you're still experiencing difficulties.
