### ISSUE TITLE
woomera b-5 exhaust on rear LH side to low.

### ISSUE THREAD

**Issue by Dreadous** [Bungie-net/api#1073]
woomera b-5 exhaust on rear LH side to low. Please move to correct location.
![20191006015316_1](https://user-images.githubusercontent.com/56216287/66265679-84536e80-e7e8-11e9-9741-7dbd4ce0156f.jpg)

**Comment by floatingatoll** [comment]
Unfortunately, in-game problems like this can’t be reported to this API forum, as the API team doesn’t have any control over the art direction and models used for spaceship warping and engines. Please file this in the official Bungie Help forums so that the appropriate team sees it (as you are correct, it’s clearly askew).
