### ISSUE TITLE
TransferItem yields UnhandledException, when using wrong membershipType

### ISSUE THREAD

**Issue by pancakeslp** [Bungie-net/api#1076]
I've noticed that if you specify the wrong membershipType in the request to "TransferItem" (https://www.bungie.net/Platform/Destiny2/Actions/Items/TransferItem/)
then this will give an "UnhandledException"

(tbh i hadn't noticed the significant of membershipType prior to steam migration/Shadowkeep)

Request Body (membershipType as 4 when it should have been 3)
`{"characterId":"2305843009309410383","membershipType":4,"itemId":"6917529083104192099","itemReferenceHash":"2362471601","stackSize":1,"transferToVault":false}`

Response Body 
`{"Response":0,"ErrorCode":3,"ThrottleSeconds":0,"ErrorStatus":"UnhandledException","Message":"We've encountered an error, please try again later.","MessageData":{}}`

Wanted to share to help the next idiot.

**Comment by vthornheart-bng** [comment]
Ah, thank you for the info!  We want to move away from Membership Type mattering in our endpoints, so hopefully we can get around to fixing this so that it doesn't matter which one you pass in.  Eventually in the next major version of the API I'd like to remove the membership type entirely from the endpoints.  We'll see if we have time to get to that - but until then, thank you for the heads up!

**Comment by vthornheart-bng** [comment]
TFS 838418
