### ISSUE TITLE
IntervalObjectives question

### ISSUE THREAD

**Issue by BoofLord** [Bungie-net/api#1083]
i'm looking through the records for people and i'm finding some records with just an objectives section in it, others with objectives and internalobjectives, and others with just internalobjectives.

with the internal objectives, when would you have an objectives object with it and when wouldnt you?  what's the difference?

no objectives object in this one:
``` "56035082": {
            "state": 6,
            "intervalObjectives": [
              {
                "objectiveHash": 1801298108,
                "progress": 1,
                "completionValue": 25,
                "complete": false,
                "visible": true
              },
              {
                "objectiveHash": 3021270508,
                "progress": 1,
                "completionValue": 50,
                "complete": false,
                "visible": true
              }
            ],
            "intervalsRedeemedCount": 0
          },```

internal objectives and regular objectives - 
```
 "1444711376": {
            "state": 6,
            "objectives": [
              {
                "objectiveHash": 2407834686,
                "progress": 0,
                "completionValue": 50,
                "complete": false,
                "visible": true
              }
            ],
            "intervalObjectives": [
              {
                "objectiveHash": 3469876706,
                "progress": 0,
                "completionValue": 25,
                "complete": false,
                "visible": true
              },
              {
                "objectiveHash": 2407834686,
                "progress": 0,
                "completionValue": 50,
                "complete": false,
                "visible": true
              }
            ],
            "intervalsRedeemedCount": 0
          },
```

**Comment by vthornheart-bng** [comment]
Ah, I had to ask around about this one!  I wasn't actually sure about the situation when they're combined.

The normal "Objectives" are meant to be shown all at once as the Triumph's overall objective data when it exists, and when complete then the Triumph has nothing more to give out: it's a single activation/single reward situation.

The "Interval objectives" are essentially "checkpoints" within the Triumph where completing different objectives will get you different Triumph Score rewards, and could be combined into a progress bar of overall progress on the Triumph across multiple rewards/checkpoints.

When they're combined, these are old/legacy Triumphs that still had the old data and it was never removed, but it has been superceded by Interval Objective data.  When you see interval objectives, use those instead of the now out-of-date standard Objectives.  Apparently the UI will only show interval objectives if it's populated.

**Comment by BoofLord** [comment]
thanks for the insanely fast answer.
