### ISSUE TITLE
Any chance of a better Seasonal Artifact screenshot?

### ISSUE THREAD

**Issue by NigelBreslaw** [Bungie-net/api#1086]
The seasonal artifact image is without the eye powered up and looks quite sad. Any chance this could be updated as it is such a cool part of Shadowkeep?

https://data.destinysets.com/i/InventoryItem:1387688628

<img width="529" alt="Screenshot 2019-10-10 at 10 59 01" src="https://user-images.githubusercontent.com/1957186/66549908-01fedd80-eb4d-11e9-9951-099f7a8e31aa.png">

**Comment by vthornheart-bng** [comment]
Ooh, good question - so the reason why it's the sad and unpowered one has to do with how we generate the screenshots.  

I'll log a bug on it, as this does feel like one that'd be worthy of getting a better one-off screenshot for: but there's another pressure, which is that if we start making custom screenshots for items we could be setting ourselves up for a lot of work if more "statefully changing" items like this appear in the future.  I'd be up for at least doing this one, but if we get a lot of these I can't promise that we'd have the resources to keep it up as a policy!

**Comment by justrealmilk** [comment]
Maybe you could do something with https://www.bungie.net/7/ca/destiny/bgs/seasons/VEye.png? It's a straight on angle but heh

**Comment by vthornheart-bng** [comment]
I filed the bug, but I need to warn that it's likely a low enough priority that it's going to end up in the great and terrible bug backlog. :(

**Comment by floatingatoll** [comment]
https://www.svg.com/169042/destiny-2-shadowkeep-how-to-get-the-seasonal-artifact/ Has one that’s really well lit, but I don’t know if it’s an in game screenshot, a Bungie marketing promo image, or something they made up.

**Comment by vthornheart-bng** [comment]
The act of generating a new screenshot isn't the problem as much as turning part of our automated pipeline into a manual one.

I think if we do generate a new screenshot for it, we'd want it to be uniform with the other screenshots we make rather than harvesting from another location: but the part of making one off screenshots or using existing ones that we harvest from other media is the precedent for additional manual work before every release.  We're already stretched thin for time, and I don't have any firm understanding of whether items with dynamic visual states will proliferate over time and turn a bit of one-off work into a decent amount of one-off work.
