### ISSUE TITLE
Armor 2.0 and Collections

### ISSUE THREAD

**Issue by delphiactual** [Bungie-net/api#1088]
https://data.destinysets.com/i/InventoryItem:1230192768
vs 
https://data.destinysets.com/i/InventoryItem:3592548938

https://data.destinysets.com/i/Collectible:4204233971

It appears that armor 2.0 items do not contain collectibleHash information.
If feasible it would be nice to update the Collectibles to contain an array of itemHashes (to deduplicate information)
and then update the Armor 2.0 with the appropriate hash information

**Comment by vthornheart-bng** [comment]
Oh, shoot.  This is one I need to really investigate more closely before I can make any promises about.  Currently there is absolutely no real relationship in the data between the armor 2.0 version of the item and this non-armor 2.0 version that's referred to in collections.

There may be something we could key off of in the content (for instance, if they have the same English name or some other heuristic like that), but what I'd be afraid of potential of it breaking for arbitrary content (typos, intentional choices to rename the collections version of the item, dummy versions of the item that also share the name etc... to use the English name as a heuristic example).  

There's a potential to do this through some fragile implicit or heuristic relationships, but with the resources devoted to working on the API I'm afraid to add more heuristics that need to be maintained if it can be avoided.

I'm going to add this to the backlog of ideas because I do think this'd be really nice to provide, but I just wanted to make sure it's known that I think it could be feasible to do in theory, but my fear is the ongoing cost of maintaining whatever heuristic we'd build up for it.
