### ISSUE TITLE
PlugSetDefinitions don't have displayProperties

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#1095]
Specifically, the Emotes definition used to be named Emotes, but now has no name. But all of them are nameless now.

**Comment by vthornheart-bng** [comment]
I'll see what we can do about that - they're game-sourced now, but we could re-add our override specifically for Emotes plug sets.  Unless the game ever starts returning us string data however, I want to make sure folks know that we won't be supporting strings for any plug set other than that one.  The only reason why I'd add them back to Emotes is because it used to have localized strings before these became sourced by the game, and I can't sign us up to add them to any other plug sets.

**Comment by bhollis** [comment]
That makes sense. In that case I’m happy to just maintain those ourselves, since we’ll need to anyway for non-Emote sets.

**Comment by vthornheart-bng** [comment]
Ah, totally understandable.
