### ISSUE TITLE
Count of full fireteam wipes in activity (raids)

### ISSUE THREAD

**Issue by TangoJoker** [Bungie-net/api#1097]
Uhm, sorry in advance for incorrect way of using issues forum. But i'm not really good at using GitHub. If there is a good place to post improvement suggestions, please give me a direction. Thank you,

Anyway, until that. There is a good request - /Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/Activities/

Can we have there info about number of full raid wipes character participated in, please? This can be usefull to understand viability of certain guardian during raids by maintaining deaths/wipes value.

**Comment by vthornheart-bng** [comment]
Unfortunately, with the way the content is set up before it reaches us, we don't get that information.  I'll file a request to get it, but I wanted to forewarn ahead of time that we may not ever see this stat come through the API.

**Comment by irons** [comment]
One thing the game does not need is a disincentive to raid with people who are new or bad at it, such that wipes would feel like they’re going on everyone’s permanent record, making it more likely that normal failures lead to toxic blowups, and people flouncing off to protect their stats. 

If this was delivered in the API in a way that lent itself to a reductive overall wipes/clears ratio, I’d be asking for it to be removed.

**Comment by TangoJoker** [comment]
> One thing the game does not need is a disincentive to raid with people who are new or bad at it, such that wipes would feel like they’re going on everyone’s permanent record, making it more likely that normal failures lead to toxic blowups, and people flouncing off to protect their stats.
> 
> If this was delivered in the API in a way that lent itself to a reductive overall wipes/clears ratio, I’d be asking for it to be removed.

Then what with KDR or deaths amount? Does it lead to toxicity? Should it be removed too for raid stats?
Also, emblems with raid closes work on dividing community just fine. This info won't add something more on top of it, imho.

**Comment by floatingatoll** [comment]
KDR is absolutely used as a filter by some LFG folks, even though it excludes players who play support roles like “prevent captures of our point” or “follow Lone Ranger blueberries to keep them alive”, because they mistakenly think that KDR is somehow evidence of competence or lack thereof.

Raid closes are a measure of success, a badge of honor.

Raid wipes are a measure of failure, a badge of shame.

I’m glad Bungie isn’t giving us badges of shame. LFG is cruel enough as it is without having more fuel for their fire.

**Comment by vthornheart-bng** [comment]
That is unfortunate, and I'm glad we're having this discussion.  It's a tough issue, because if you look at many of these stats someone *could* arbitrarily use them to decide whether someone is good or not, when the true answer is actually more complicated than any single stat could answer.

Not to mention the deeper issue of whether we should encourage exclusion of people based on skill in this way.  I personally would not want to endorse that kind of behavior on a wide scale, though I could see where niche groups who voluntarily subject themselves to it would not be a bad thing, as long as they don't also try to impose it on people who aren't voluntarily agreeing to abide by their standards.  For instance, if people are using these stats to kick random people out of fireteams, I would implore you to reconsider that sort of practice and/or discourage your users from that sort of practice.

But if you have a group of individuals who want to "push themselves" and thus have some kind of elite requirements for entry into a clan etc... that seems reasonable, as everyone has agreed by virtue of being in that group that some arbitrary measurement is being used to determine their inclusion/exclusion.  But that's just my take on it from a philosophical perspective.

Anyways, for Raid Wipes it's looking to be a moot point: we can't get at that data.  But the potential for it being used in an abusive way is something that we need to keep in mind on our side as we assess these requests, while weighing the fact that private groups might get some level of use out of it.  Perhaps in the future there'd be some set of stats that are disabled for users by default, and you would have to explicitly enable them in order for them to be returned, thus allowing that "voluntary" scenario to exist.  But that too is unfortunately only a fantasy: I don't see us having the time to implement something like that unless we got more resources to work on the API.  So just as a caveat, this is more of a brainstorming session about how we might bring that about, and not something which will actually exist.
