### ISSUE TITLE
Should the manifest be private only?

### ISSUE THREAD

**Issue by thisbarker** [Bungie-net/api#110]
It appears the manifest can only be retrieved if authenticated or using a web browser that creates cookies. Is this intentional?

**Comment by JonnyOThan** [comment]
I don't think that's totally true...you do need to supply the API key, but you don't need to have a logged-in user's access tokens.

**Comment by thisbarker** [comment]
It appears if you pass an authorization header within old/invalid information the API will throw a not authorized error.

This may not be a bug, not sure.

**Comment by vthornheart-bng** [comment]
Hmm - yeah, when grabbing the manifest itself, don't bother to pass auth info.  IIRC it's going to check for whether the auth is valid no matter what, so it's only providing an additional barrier of entry that you otherwise wouldn't have!

I'm going to go ahead and close this one for now.  If you run into any other issues, let us know!
