### ISSUE TITLE
Add WeaponType definitions / list to manifest

### ISSUE THREAD

**Issue by mikechambers** [Bungie-net/api#1130]
Currently there is no single definitive source to get a list of weapon types.   It needs to be parsed and then manually filtered from DestinyInventoryItemDefinition.

It would be useful if there was definitive list of weapon types in the manifest. Bonus points if other areas of the manifest reference that table.

Maybe a new DestinyWeaponTypeDefinition table.

**Comment by vthornheart-bng** [comment]
By weapon type, do you mean things like "Fusion Rifle," "Auto Rifle," "Shotgun" etc?

If you're talking those, then you can use either the DestinyItemCategoryDefinitions related to the item, or the ItemType/ItemSubType enum values on them.

But if you're talking something else in there - some other quality about the items that might be considered a type - let me know, as I know people categorize items in a variety of ways and we may not be covering or providing all of the ones you'd want!

**Comment by mikechambers** [comment]
Thanks for the help.

When I look at the a weapon item entry for a weapon in DestinyItemCategeoryDefinitions, here is what I see:

```
{
  "displayProperties": {
    "description": "Yet another type of laser rifle.",
    "name": "Linear Fusion Rifles",
    "hasIcon": false
  },
  "visible": false,
  "deprecated": false,
  "shortTitle": "Linear Fusion Rifles",
  "itemTypeRegex": ".*_fusion_rifle_line",
  "grantDestinyBreakerType": 0,
  "grantDestinyItemType": 0,
  "grantDestinySubType": 22,
  "grantDestinyClass": 3,
  "groupedCategoryHashes": [],
  "isPlug": false,
  "parentCategoryHashes": [],
  "groupCategoryOnly": false,
  "hash": 1504945536,
  "index": 56,
  "redacted": false,
  "blacklisted": false
}
```

Which has grantDestinyItemType as 0.

But looking at the DestinyItemTypeEnum at:
https://bungie-net.github.io/multi/schema_Destiny-DestinyItemType.html#schema_Destiny-DestinyItemType

It should be 3 (0 is None). AM I looking at the wrong properties / enum? or is that the wrong type?

The grantDestinyClass property is 3. Is that the correct property?

Sorry for the confusion, and if Im missing something obvious. Just want a way to know what is a weapon with out having to hardcode weapon types.

**Comment by vthornheart-bng** [comment]
Ah, in this situation the Linear Fusion Rifles category is setting grantDestinySubType to 22 (FusionRifleLine)

grantDestinyClass setting 3 is, unfortunately, some historical cruft.  That particular enum (DestinyClass) has 3 = "Unknown", so it defaults to 3.  It's one of those dumb choices I made back in 2012 that is now difficult to rollback for backcompat reasons.

The trick to item categories is that an item can have multiple, and the layering of them is how an item ends up with these enum values!  For example, with weaons there's another Category that any linear fusion rifle (or any weapon) should be assigned, CATEGORY_WEAPON, which is the one that grants itemType "Weapon" (3).

If it's a heavy weapon for example, it'll also get the CATEGORY_HEAVY_WEAPON category, which doesn't provide an item type but you can check for on the item definition as well if you're filtering for specifically heavy weapons regardless of type.

I hope this info helps!  Let me know if you have any other questions!

Investigating these definitions is difficult for those of you looking to dig through the data, because these entries aren't mapping back to their enums in our HTML documentation, which I need to fix.  I apologize for how much of a pain it is to deal with them at the moment.  If it helps, looking through the Swagger spec file will get you the enum links that the HTML documentation is currently lacking.

**Comment by floatingatoll** [comment]
If you’d like to break all of us someday to fix this, you need only ask.

**Comment by vthornheart-bng** [comment]
It's been one of those things where, once every couple of years, I am reminded of how awkward it is: but I think it's mostly a bruise to my pride rather than a significant problem worth stopping other work for.
