### ISSUE TITLE
Haunted Forest activity (1454880421) does not persist in available characterActivities once challenge is completed

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1136]
Haunted Forest activity (`1454880421`) does not persist in available characterActivities once challenge is completed

_Profile endpoint -> Response.characterActivities.data[characterId].availableActivities_

Once its challenge/weekly reward is completed, the activity is no longer "available."

Completely understand if this can't be fixed for this year's event, but please know that the desired behaviour is for the activity to persist, as is the behaviour for other activities with similar milestone/weekly reward challenges.

I personally believe that characterActivities is the future of milestones and I use them to highlight special events, such as Festival of the Lost, on Braytech.

Fig. 1: Example
![image](https://user-images.githubusercontent.com/156681/68143512-55622100-ff7d-11e9-9d3c-5aa20c265ba7.png)

❤❤

**Comment by vthornheart-bng** [comment]
I'll give this some thought, as I'm of a similar mind: I'd like to move away from Milestones and to a more consistent response for activity-based info.  Right now, the characterActivities component wasn't built that way: it's just returning the raw info about activities that a character can play, and wasn't built with the intent of showing completed activities in mind.  But I could see it expanding to meet that.  However, doing so will require moving some configuration that's currently being done to make Milestones work over to characterActivities, which comes with its own risks/maintenance tasks/inconsistencies that we currently see in Milestones.

Before I commit to doing this to characterActivities, I need to weigh our options (including potentially other options that we may not currently be thinking of).  But I will definitely keep this in mind, and I welcome any suggestions along these lines that people have!

Those of you reading this thread: how do *you* use Milestones and Activities data?  What is useful to you, what is broken?  Is there data that you always use?  Data that you never use?  Data that you rebuild from other information?  I'd like to hear more about how all of this info is actually being used in the wild.

**Comment by justrealmilk** [comment]
So I feel foolish - it's listed in activities so long as you meet the requirements (has the appropriate item, the mask, equipped). 

Different but same problem but I don't expect you to change anything to _fix_ this one 😂

**Comment by vthornheart-bng** [comment]
It's definitely a tough one, because in an ideal world I'd like to return you information about the fact that you *could* do this activity, if only you were to do X (in this case, X = equip the mask).  But we also don't want to flood you with a bunch of irrelevant info - like activities that are disabled because you legitimately can't play the activity.  But perhaps there's a good path we could head down for that.

Interesting side note: activity visibility and accessibility is actually an unusually complex issue in Destiny content.  The activity itself has gating, but so does the Activity Graph node where it shows up on the map, the parent objects of that graph node, and of course there's always the possibility that it's activated by some other way than the director.  There's also the potential for different requirements if you're joining as a Fireteam member vs. being a Fireteam leader.  If we ever get the chance to break up Milestones and pull that information into the Activities data, I'd like to convey that info in a compact manner if possible.
