### ISSUE TITLE
DestinyProgression has no reward state info when inventory is full

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#1140]
Seasonal rank rewards have a list of `rewardItemStates` bit flags (see [DestinyProgressionRewardItemState](https://bungie-net.github.io/multi/schema_Destiny-DestinyProgressionRewardItemState.html#schema_Destiny-DestinyProgressionRewardItemState)) that describe how to display an item, however there isn't a flag for when an item can't be claimed due to other requirements such as your inventory being full.

**Comment by vthornheart-bng** [comment]
Mmm, good call.  I'm not 100% certain that we're going to be able to provide it anytime soon because we need to move that logic closer to the game side (which means a long turnaround), but that is certainly something I want to provide!  When I am back in the office I will try to loop back to this and make a bug.  (my back problems have flared up again in an even worse way than earlier this year.  This sucks.)
