### ISSUE TITLE
Old Nightfall: The Ordeal activity definitions are missing

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#1171]
Since the Season fo the Dawn update, it appears the Ordeal Nightfalls  that were removed from the rotation have had their Activity definitions removed entirely. 

An example of that is this PGCR 5270169905, which fails to render on Bungie.net https://www.bungie.net/en/PGCR/5270169905/. In the API it's referenceId and directorActivityHash is 1390900084, which no longer exists in the definitions.

<img width="403" alt="womp womp" src="https://user-images.githubusercontent.com/46142/70735562-659cb700-1d06-11ea-8ead-31d0db5051c3.png">

Using Light.gg's historical definition diffs, we can see that this activity was actually https://www.light.gg/db/compare/104616 "Nightfall: The Ordeal: Master, The Inverted Spire".

It's problematic to remove the definitions for entities the API is still actively returning because it means we're unable to display these activites once the season has passed. Is there any change these definitions could return?

**Comment by justrealmilk** [comment]
Addendum: it appears even nightfalls that weren't remvoed from rotation have had their hashes changed

**Comment by vthornheart-bng** [comment]
I need to look into what's going on with Nightfall data for sure.  I'm filing a bug on this!

As far as changing hashes, unfortunately we've seen this problem before: BNet is at the mercy of the game design team, if they change the identifier of these activities we can lose references to them.  I will need to speak with them and try (A) to get them to not rename these activities anymore and (B) to see if I can make some sort of mapping between what the identifiers used to be and what they are now, so that we can give you some sort of data when you look at historical records.

I can't guarantee when this will happen - and I apologize for the miss on this.  Usually the policy is to keep those identifiers unchanged for just this reason, and they haven't done a change like this in a long time.  Caught us by surprise this time.
