### ISSUE TITLE
Most (?) Tower PGCRs no longer being generated

### ISSUE THREAD

**Issue by as-com** [Bungie-net/api#1189]
This was brought to our attention on the Discord by @justrealmilk - it appears that tower PGCRs are no longer being generated for instances that have a lot of players. This has been backed by anecdotal reports of Tower PGCRs going missing. 

@joshhunt and [redacted] queried their datastores of PGCRs and found that Farm PGCRs look normal-ish (with thousands of players) while Tower PGCRs mostly contained very few players.

**Comment by v-fedorov** [comment]
Im not sure where @joshhunt is getting his data but both social spaces look fine
![image](https://user-images.githubusercontent.com/1764879/74252160-40530780-4cbb-11ea-8c4b-b2db2c4505f1.png)

Theres definitely a good amount of instances with 1-3 players but thats what happens when every player leaves the instance.

I do see a lot of pgcr with mode 0, including tower and farm but im assuming those are somehow related to the story mode

**Comment by as-com** [comment]
This is probably just a false alarm... but I'm going to leave this issue open until I have a chance to look myself.
