### ISSUE TITLE
Special characters in profile names

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1228]
Due to a recent security patch, special characters in profile names are now rendered as boxes - probably incomplete sequences.

Obviously, security takes priority over everything, but if possible, it would be nice to whitelist characters such at those found in the game font.

Personally, I dislike the fad of using super icons to spruce up my profile name, but I prefer viewing them to tall rectangles. 😆

**Comment by Achronos-BNG** [comment]
The "boxes" are not incomplete sequences, they are a deliberately picked character that mimics what happens in the game if you give it a character that the game font does not have a character for (or a few other characters we decided not to let you use).  

The security fix was actually a fix to the parser that scanned profile names - it would often only catch one bad character instead of all of them.  The set of allowed characters has not actually changed - it is still a whitelist of the thousands of characters the game font supports.  It is the largest regex I have ever written - it is nearly 80,000 characters, all on one line.  Visual Studio does not like it when I open that file.

**Comment by justrealmilk** [comment]
So just to clarify, SpeakableAuto (https://www.bungie.net/en/Profile/1/4611686018438041671/SpeakableAuto), who has  (Sniper Rifle, Precision) at the end of his name, is no longer is supported by the API?

It displays correctly in game as with all other names using the Destiny font's characters, but as of this security update...

**Comment by justrealmilk** [comment]
Here's a different example

![image](https://user-images.githubusercontent.com/156681/101710158-cbb93880-3a45-11eb-9b47-ae1a3ef574ca.png)

The larger profile name comes from the profile info component (100) while the transitory component (1000) _does_ return these characters correctly.
