### ISSUE TITLE
seasonHashes are int64, but declared as int32

### ISSUE THREAD

**Issue by akandratovich** [Bungie-net/api#1244]
```
Expected an int but was 3612906877 at line 1 column 345 path $.Response.profile.data.seasonHashes[0]
```

**Comment by vthornheart-bng** [comment]
Ah!  So the problem here is that they're actually unsigned ints and not signed ones.  You'll see as you use the data that anything that refers to "hashes" are uints in there, so you'll likely run into a lot of trouble like this if you try to make them signed.  Try a uint32 instead and it should serve you well!
