### ISSUE TITLE
Titan Mark: Ere the End missing collection record

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#1246]
There are InventoryItem records, but no Collection record for the Titan Mark Ere the End.

Armor v1 and v2 items:
DestinyInventoryItemDefinition 1700762222
DestinyInventoryItemDefinition 1809381922

**Comment by floatingatoll** [comment]
This issue is known to affect 6 class items that were added to world drops in a recent patch.

Reddit post about this on March 12th: https://www.reddit.com/r/DestinyTheGame/comments/fhq3ez/bungie_resolved_an_issue_in_the_game_that_was/

Bungie Help confirmed “we’re investigating” on March 23rd: https://www.bungie.net/en/Forums/Post/255564416?sort=0&page=0&path=1

**Comment by jshaffstall-bng** [comment]
This is a known game issue that we don't intend to fix manually in the Bungie.net content, and we'll wait until it's addressed in the game.

**Comment by kramrm** [comment]
Makes sense if it's game side.  Thanks for the update.
