### ISSUE TITLE
Please add ability to specify multiple redirect url's for authentication.

### ISSUE THREAD

**Issue by michaeldaw** [Bungie-net/api#1255]
In the past, I've developed authentication solutions using Azure Active Directory or Auth0. Both systems allow the developer to indicate as many OAuth re-direct url's as required. The desired redirect url is then specified as part of the authentication process. (eg: Microsoft's documentation on the subject: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code)

This enables development/testing environments. If I need to track down a bug, I can have a dev/test instance of the website that the authentication system will allow redirects to.

**Comment by Tetron-bng** [comment]
This is a reasonable request. Support for multiple redirect URIs was skipped in the initial version of the Bungie.net OAuth implementation in order to keep it simple. Demand for further development was not high and so it has not materialized.  I believe most people use a second application instance for development purposes so a different redirect URI can be used.

**Comment by michaeldaw** [comment]
I'm currently using a second application for this, yes. It certainly works; thanks for the suggestion. That said, from what I understand, there is a limit to the number of applications that a particular user can associate with their account, which then further limits how many dev/testing environments that can be made.

**Comment by luislobo** [comment]
Any news on having a way to provide more than one redirect URI? Right now if you include one it errors if it's not the exact same one as the one defined.

Most use cases are having multiple environments: localhost, staging, production.

Thank you!
