### ISSUE TITLE
Get Activity Stats - Buckets

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#126]
In the get activity stats endpoint, I'm looking up AllPvP, Countdown, and Trials.  

AllPvP = sum of all playlists (pre trials was accurate).

Trials = trials specific stats, seems accurate.

Countdown though now, is Countdown (quickplay) and Trials.  Meaning Trials data is doubly accounted for and no longer add up to AllPvP when summing all the current playlists. 

Can Trials be removed from Countdown?

**Comment by vthornheart-bng** [comment]
Yeah, let me pull over some conversations I was having externally on this topic.  I do think at the moment that the right thing to do would be to segregate "Trials Countdown" from "Countdown" - basically making a new "leaf" activity mode under Trials for each specific mode of play that Trials can be played under.

I'm open to opinions on this right now, as doing this will make it harder for people who want their Countdown aggregated stats to also count Trials (or future modes... let's say Iron Banner comes around and it turns out you can play Iron Banner Countdown... we'd segregate that as well, so neither Iron Banner nor Trials Countdowns would count in the normal Countdown aggregated stats).

If this is preferable for people, we can definitely accommodate!  But unfortunately with our model, it's going to be an either-or situation for us.  In retrospect, I think it might have been useful for our own internal architecture to separate the concept of these "special modes" from "activity modes" so that they could be grouped more interchangably... but that'd imply some larger scale changes that I don't think we have the capacity to do.  But if the suggestion above is sufficient for most use cases, hopefully that will be enough.

Comments anyone?

**Comment by sgtfrankieboy** [comment]
I think that would be the way to go. It gives us the most flexibility on how/what we want to show.

**Comment by bladefist** [comment]
@vthornheart-bng I agree w/ your Iron Banner example.  Iron Banner and Trials are in-game UI decisions a player makes, those are specific playlists people want to play and want stats on.    

Countdown itself should be the quickplay variation of it.  Also I think that all the modes should add up to AllPvP.  We'll see what others say, one mans opinion!

**Comment by adherrling** [comment]
I agree with the two above commenters. As an additional point, it's a lot easier to add together separate countdown stats than it is to try to parse out which is which if they're all combined - returning the most fine-grained detail doesn't restrict functionality, but pre-grouping the data does.

**Comment by vthornheart-bng** [comment]
Aye, good calls all around.  I'm looking to get this released with next week's releases!  Thanks for the input y'all!
