### ISSUE TITLE
Feature request: API for emblem/stat equipping

### ISSUE THREAD

**Issue by bradchoate** [Bungie-net/api#1262]
It would be nice to see support for equipping an emblem and the active stat for it through the API. Since this would be cosmetic, it could be invoked with less restrictions than equipping other gear.

I can imagine this could be utilized to automatically equip a relevant emblem and stat appropriate to the activity the player is doing in the moment. Ie, a crucible emblem and trials stat for trials; a raid emblem and clear count for the active raid; the appropriate strike emblem and score stat, etc.

**Comment by jshaffstall-bng** [comment]
Filed as TFS 919046

**Comment by bradchoate** [comment]
SO MANY GREAT EMBLEMS from recent charity / awareness drives. "Be Heard", "Bungie Foundation Emblem", "A Guardian's Heart", "Star Light, Star Bright", "Planet of Peace"... having a programmatic way to equip one of these at random would be awesome.

Alternatively, an in-game option to mark some of my emblems as favorites (similar to finishers) so they are equipped on a rotation/cycle would be another way to implement that wouldn't require a third-party service.

**Comment by floatingatoll** [comment]
Note that you can equip emblems that are stored on-character using the API today, and would simply need to do so while in orbit. You’d need to take care to detect that the character is actively participating in activities, so that you aren’t rotating the emblems for a logged-out character, or constantly rotating emblems while they idle in orbit/farm/tower — and you’d have to set up some sort of “keep trying to equip it” 30-60 second retry unless/until Bungie weakens the restriction on changing emblems while in-activity — but it’s absolutely something that could be done today.

**Comment by bradchoate** [comment]
Thanks for the reminder... I agree that the "in orbit/farm/tower" restriction is the real limiting factor.

Another use case I had in mind was auto-equipping the emblem appropriate for the active strike. Being able to detect the player is in a strike, and then equipping the strike emblem (I suppose the player would have to have the emblem in their inventory, but I'd love to see the day when your collection is considered your inventory when it comes to many cosmetic things that cost nothing to re-obtain-- emblems, emotes, finshers). You'd have to be able to equip while in the activity for this to work.

I suppose lifting this restriction could allow for abuse. A cooldown could be imposed, so switching a player's active emblem wouldn't allow for bombarding other networked players with emblem change traffic (unless this isn't an issue, and the player inspection operation always fetches the emblem on invocation).
