### ISSUE TITLE
Iron Banner Mode

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#129]
I'm assuming there is an Iron Banner due to it's popularity.  In D1 Iron Banner was randomly different modes, Clash, Control, Supremacy, etc.

I wanted to get the convo on this started early, as IB modes were often wrong in D1 (at least in my view).

1) There is a discussion over at #126 about how these stats would show up in get activity.  Would love to see IB get it's own playlist and not be included in control/clash/etc.  That's up to vthorn/votes.

2) PGCR.  I would really like to see IB come down w/ a mode that is it's own unique mode, like 41 or something, and then in modes:[] you could go into more detail.  This will allow us to query a players recent IB stats and separate it from quickplay.

Thanks!

**Comment by vthornheart-bng** [comment]
Yeah, I'm planning on doing what's discussed in #126 for Iron Banner as well when the time comes.  In that approach, if you're looking for "leaf node" activity modes there will be one per variant of Iron Banner, specifically for Iron Banner's variants of play and rolled up into a single Iron Banner mode.  This doesn't exist yet - currently the activity modes are configured such that they will be under the non-special variants as Trials is - but I intend to fix that along with the fix for Trials and set that as the precedent going forward.

**Comment by vthornheart-bng** [comment]
I'm going to close this one out because I think #126 covers the intent of how we'll deal with these modes pretty well - let's centralize the conversation over there!  But to note, I agree with your points all around and we'll make that happen.
