### ISSUE TITLE
Question: Is the perk dictionary key an item hash or instance id?

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#13]
[Documented here](https://bungie-net.github.io/multi/schema_DictionaryComponentResponse-int64-Destiny-Entities-Items-DestinyItemPerksComponent-.html#schema_DictionaryComponentResponse-int64-Destiny-Entities-Items-DestinyItemPerksComponent-)

I'm curious if the key is an item hash or an item instance id.  Thanks!

**Comment by vthornheart-bng** [comment]
Ah, yes!  That is an instance ID - I need to see about adding that to the documentation, finding a place to document it other than the parent is a little tricky because they're implemented via a single generic class under the surface.  Another good reason for these dictionaries to be inline instead of listed as individual schema.

**Comment by vthornheart-bng** [comment]
I don't have the time right now to add the metadata needed to make sure this can come through in the generator - for now, you'll have to infer it from the description of the property that's pointing to it.  They should say whether they're instance IDs, vendor item indexes etc..
