### ISSUE TITLE
API Key in Google App Script

### ISSUE THREAD

**Issue by phork37** [Bungie-net/api#135]
I'm fairly new to Javascript and API and am attempting to use Google App Script to create a spreadsheet for my clan's stats.

I have an API Key, but can't figure out how to send it through [UrlFetchApp](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app). 

Any suggestions, help, or examples would be much appreciated. Thanks!

Edit: I'm also new to github and don't know how to label this with the 'Question' tag, sorry!

**Comment by vpzed** [comment]
Looks to me like you have to use the options object to specify your x-api-key header in the headers object.

https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch(String,Object)

So maybe something like:

    var options = {
       'method' : 'get',
       'headers' : {
          'X-API-KEY' : 'your_api_key'
        }
     };
     var response = UrlFetchApp.fetch('https://www.bungie.net/Platform/Destiny2/Manifest', options);

To be clear I have only just read the instructions on the link you provided so that is just a guess.

**Comment by phork37** [comment]
Thank you! 

I had tried using options earlier, but was still getting an error. The code you provided is working perfectly, so it must have been a formatting error on my end.
