### ISSUE TITLE
Playlist Stats are not updating

### ISSUE THREAD

**Issue by brianbolnick** [Bungie-net/api#1380]
I've noticed the data from the historical stats endpoint isn't being updated. For example, I played a few nights ago on this character but this endpoint is coming up entirely empty:

https://www.bungie.net/Platform/Destiny2/1/Account/4611686018449620150/Character/2305843009265284017/Stats/?modes=84

Possible reference to #1371....

Thanks!

**Comment by brianbolnick** [comment]
@jshaffstall-bng curious to know if you have an estimated timeline with this at all so I can pass it on to my users?

**Comment by jshaffstall-bng** [comment]
Good catch! Filed as TFS 967913 for us to investigate.

**Comment by bladefist** [comment]
Can confirm,  Iron Banner stats not updating as well.

**Comment by bladefist** [comment]
The issue is none of these stats are updating.  As players play more, the PGCR are recording, but the aggregate stats from the API call  (https://www.bungie.net/platform/Destiny2/TigerSteam/Account/4611686018491485350/Character/0/Stats/?modes=AllPvP.....)  don't update.

So right now stats at the playlist level, like Trials, Controls, etc, are stagnant and haven't updated for almost a month.  Thank you.

![image](https://user-images.githubusercontent.com/1520456/105213992-0c13d800-5b15-11eb-9b95-0e05f184a7c1.png)

**Comment by bladefist** [comment]
I would rename this issue "Playlist Stats are not updating".  "Historical Stats" is a bit vague but I understand why it was chosen.

**Comment by justrealmilk** [comment]
> I would rename this issue "Playlist Stats are not updating". "Historical Stats" is a bit vague but I understand why it was chosen.

I mean it's the name of the endpoint 😅

**Comment by bladefist** [comment]
At the risk of being annoying, any update on this? Still impacting crucible players.

**Comment by jshaffstall-bng** [comment]
Sorry, no update on this yet.

**Comment by GuilianC** [comment]
Hi, average crucible player here :)
Is there any news on this? 
Today i realized playing iron banner was not counting to my KD ratio at all, like i never killed anyone and never died at all
Thanks :)

**Comment by andy440124** [comment]
This has been bugged since literally the start of beyond light. Every time Iron Banner rolls around I check to see if anything's changed and come back here to see if there is any updates and see nothing. At this point I don't expect it to ever be fixed....

**Comment by jshaffstall-bng** [comment]
Yep sorry, I understand the frustration. I'll see if we can make this a priority soon.

**Comment by andy440124** [comment]
Much appreciated! :)

**Comment by osori83** [comment]
It would be great if this issue could be resolved. Sad to see 50+ hours of Iron banner this season not being counted towards crucible stats such as KD or winrate.

**Comment by kuleshov-aleksei** [comment]
Hello! Is there any updates on this issue?

**Comment by Noevuh** [comment]
Nope. Still nothing.

**Comment by osori83** [comment]
Disappointing that this issue has existed for so long and there are no updates.

**Comment by kuleshov-aleksei** [comment]
Yeah... I think Bungie currently have a lot of issues that appeared with new season, so we will not see fix soon.
At least this endpoint is showing some part of data, for most users it is enough

**Comment by AllynH** [comment]
Hi @jshaffstall-bng  is there any movement on this issue? 
I believe it impacts Trials, Iron Banner and possibly Gambit.

**Comment by Marruk** [comment]
Curious to know whether there's an update on this 🙂

**Comment by Breeky** [comment]
Hi, seeing that these issues are closed, does it mean it won't be resolved after all ?

**Comment by braddadocio** [comment]
Bungie definitely keeps accurate summarized competitive stats for all players for the purpose of match-making. If they're not coming through this public API, it seems intentional. While I can perhaps understand a motivation around keeping competitive stats private, it doesn't stop sites like Trials Report, Destiny Tracker, Warmind.io, etc., from getting them the hard way. So, there's no real benefit to breaking this API.
