### ISSUE TITLE
Redirect Code doesn't always work

### ISSUE THREAD

**Issue by zoltaroth** [Bungie-net/api#1383]
I have my site setup to take the redirect code from user auth and immediately request an oauth token with it.  Sometimes it takes 2-*8* code requests to get one that doesn't yield a 400 error when requesting an oAuth token.  Am I just doing something wrong or is this a bug?

**Comment by floatingatoll** [comment]
2-8 code requests over how many seconds?

**Comment by zoltaroth** [comment]
> 2-8 code requests over how many seconds?

I retry as soon as I get a failed oAuth code so probably 1-3 seconds depending on network timing.  But the first code shouldn't fail to begin with is my point.

**Comment by floatingatoll** [comment]
It's possible that Bungie's backend caching servers may, by design, require a couple seconds of patience from your code. You should ensure that you aren't retrying more often than once per second and that you give up after a certain number of retries — otherwise, an auth outage could cause your app to infinite-spam the servers.

**Comment by zoltaroth** [comment]
I finally found the issue (hard to spot with the reloads).  By adding the 1s delay as you said I started to see more failures which lead me to dig deeper.  Turned out I was calling the oAuth endpoint 2x back to back due to a rerender and it depended on which call returned first as to if it failed or not.  I've now blocked from sending more than 1 request at a time and it has resolved itself.

**Comment by floatingatoll** [comment]
Woot! Cheers, glad I could (indirectly) help.
