### ISSUE TITLE
VendorItemStatus is either wrong or used incorrectly or nonsense.

### ISSUE THREAD

**Issue by nandor-code** [Bungie-net/api#1394]
I was working on my Banshee-44 alerter and ran across something odd.  When I look at the VendorItemStatus enum on a mod you already have it is set to 8 and 0 if you don't have it / can buy it.  The problem is that according to the [enum](https://bungie-net.github.io/multi/schema_Destiny-VendorItemStatus.html#schema_Destiny-VendorItemStatus),  8 means NoUnlock which does not make a whole lot of sense vs something like AlreadyOwned.

Here is my logging:
```

  | 2021-01-10T16:10:28.393-08:00 | 2021-01-11T00:10:28.392Z ca0fc314-37a4-4ac7-84ae-b93b276ea9e2 INFO ITEM Radar Tuner STATUS 8
-- | -- | --
  | 2021-01-10T16:10:28.393-08:00 | 2021-01-11T00:10:28.393Z ca0fc314-37a4-4ac7-84ae-b93b276ea9e2 INFO ITEM Fusion Rifle Scavenger STATUS 8

```

Is the enum published wrong or is the internal code just really wonky?

**Comment by jshaffstall-bng** [comment]
It's possible that these Mods just behave differently from other kinds of vendor items, but this just seems like an implementation detail on the game side. The failure reason string you get is 'Already Owned' but I understand that it doesn't help with this kind of application.

It sounds like the issue is that you can't distinguish between 'NoUnlock' when you don't meet some requirements, and 'NoUnlock' when you already own it, correct?

Filed as TFS 969109, but this is game-side content and probably won't be changing soon.

**Comment by zoltaroth** [comment]
> It's possible that these Mods just behave differently from other kinds of vendor items, but this just seems like an implementation detail on the game side. The failure reason string you get is 'Already Owned' but I understand that it doesn't help with this kind of application.
> 
> It sounds like the issue is that you can't distinguish between 'NoUnlock' when you don't meet some requirements, and 'NoUnlock' when you already own it, correct?
> 
> Filed as TFS 969109, but this is game-side content and probably won't be changing soon.

I think the enum has a value to describe "You Already Have this" and it is confusing at best that this is not using that value.  And like you said it makes it impossible to know if there is acutally an unlock issue or not.
