### ISSUE TITLE
Weapon icon 'thumbnails' pointing different ways

### ISSUE THREAD

**Issue by ashleypb** [Bungie-net/api#143]
No biggy really, just a visual thing...
The weapon directions are different on some weapons.
In Destiny 1, within all the thumbnails the weapon 'grip' was on the left side of the image.

Ive noticed in Destiny 2 some thumbnails 'icons' are the otherway around. 
Im not an OCD person but things looking uniform are always better on the eyes!

For example: Mida Multi Tool & Nightshade (technically pointing the wrong way, need flipping horizontally)
http://www.bungie.net/common/destiny2_content/icons/077e9577fb39cb521b49048db236e39d.jpg
http://www.bungie.net/common/destiny2_content/icons/fe0a4a1d2d0f2a152b1f7ac63445ab54.jpg

There's probably loads like this, Ive only seem a few while testing layouts, maybe new weapon renders were right to left instead.

**Comment by ArkahnX** [comment]
Kinetic weapons such as Mida Multi-Tool and nightshade point to the upper left, energy weapons will point to the upper right, this is an intentional difference

**Comment by floatingatoll** [comment]
The API matches in-game in this behavior, so it may not be a bug.

**Comment by vthornheart-bng** [comment]
Aye - unfortunately all we've got is what we're given!  I'll bring it up to them, but unfortunately because we don't really have any sources other than the game's icons itself, we have to work with whatever we get from them.  I'll close it for now, but I will go ahead and bring it up to those who might be able to change it if it's something they're willing to do!
