### ISSUE TITLE
GroupV2 not returning results past the first 25 Clans

### ISSUE THREAD

**Issue by sakebomb** [Bungie-net/api#1453]
I have been attempting to query the [GroupV2 Search](https://bungie-net.github.io/multi/operation_post_GroupV2-GroupSearch.html#operation_post_GroupV2-GroupSearch) endpoint with multiple combinations to get past the first page of results. The documentation mentions the below objects but only "name" has worked.

```
url = "https://www.bungie.net/Platform/GroupV2/Search/"
group = "dod" // Should respond with more than 25
count = 1
{
  "name": {group},
  "requestContinuationToken": True, // This is not returning any token no matter if I try True/true/1
  "currentPage": count, // Incrementing this does not make any change to the page number
  "itemsPerPage": 100, // Incrementing this does not make any change to the amount of results
  "useTotalResults": True // This does absolutely nothing for some reason
}
```

This is the response using the above object query:

```
{
    "Response": {
        "results": [ ...
        ],
        "totalResults": 25,
        "hasMore": true,
        "query": {
            "name": "dod",
            "groupType": 0,
            "creationDate": 0,
            "sortBy": 0,
            "itemsPerPage": 25,
            "currentPage": 4,
            "requestContinuationToken": "True"
        },
        "useTotalResults": false
    },
    "ErrorCode": 1,
    "ThrottleSeconds": 0,
    "ErrorStatus": "Success",
    "Message": "Ok",
    "MessageData": {}
}
```

**Comment by ashakoor** [comment]
- You're getting 25 results because the maximum is 25.
  - That being said, putting anything less than 25 for `itemsPerPage` still returns 25.
  - Incrementing the page does nothing for me either.  
- `useTotalResults` does nothing because you're not supposed to send it - that's what you get back.
  - [`GroupsV2.GroupQuery`](https://bungie-net.github.io/multi/schema_GroupsV2-GroupQuery.html#schema_GroupsV2-GroupQuery) has what you can send.
- `requestContinuationToken` is a string, not a boolean.
  - Not too sure what it does, but I can say that you're not supposed to send `true`/`false` for it.

**Comment by sakebomb** [comment]
Thank for for checking this out. Good to know that you could replicate this.

You are correct about requestContinuationToken. I guess it would return a hash which would be the next results?

The reason I tried all of those fields is because I wanted to ensure I exhausted my options on testing the API.
