### ISSUE TITLE
Cross save problom

### ISSUE THREAD

**Issue by Saltasaur** [Bungie-net/api#1459]
I recently played on Xbox and then switched to pc on Destiny 2. Everything went completely fine except that my shadow keep expansion that I have purchased in the past didn't load in for some reason. I even have some of the exotics that you need to get the expansion to get. I need help does anyone know how to fixed this problem or have experienced it in the past?

**Comment by ats** [comment]
This isn't a forum for general gameplay issues, rather is focused on use of the D2 API itself. That said: any items that you have unlocked through play will transfer across platforms, which is why you have access to the exotics on PC after playing on Xbox. But expansions like Shadowkeep are not unlocked across platforms by a single purchase. For Shadowkeep, you need to buy the actual expansion on the platforms where you want to play. (This doesn't apply to season pass content; that's fully cross platform. Also: since Beyond Light is now part of Game Pass on Xbox, you can buy it on PC and play on Xbox without an additional purchase if you keep playing on both platforms.)

**Comment by jshaffstall-bng** [comment]
Yes, sorry, this isn't a good place to get Bungie account support, but you can try https://help.bungie.net/hc/en-us or the Help forums on Bungie.net instead.
