### ISSUE TITLE
Some users have accounts in a state that causes GetLinkedProfiles to return zero profiles

### ISSUE THREAD

**Issue by NigelHietala** [Bungie-net/api#1512]
I don't know how big an issue this is, as I have only had a handful of reports. For some users calling GetLinkedProfiles shows the following 

`{"Response":{"profiles":[],"bnetMembership":{"supplementalDisplayName":"masinmesaiaensi#3726","iconPath":"/img/profile/avatars/bungieday_14.jpg","crossSaveOverride":0,"isPublic":false,"membershipType":254,"membershipId":"8617529","displayName":"masinmesaiaensi"},"profilesWithErrors":[]},"ErrorCode":1,"ThrottleSeconds":0,"ErrorStatus":"Success","Message":"Ok","MessageData":{}}`

There are zero profiles. When GetLinkedProfiles is then called with `"getAllMemberships": "true"`  a single valid profile does show up. So I am using that to work around this issue.

Another account with the same issue is 4391429 dirtyfrank77

**Comment by Achronos-BNG** [comment]
This is actually by design.  In both cases, the users in question have marked their linked accounts as "private".  This means that if you look them up by membership id, you can't see the accounts unless you use that membership id.  4391429 and 8617529 are bungie.net profile membership ids, so you won't see linked profiles that are private.  If you want to see their destiny account, you have to use the proper destiny membership.  Cross save accounts can't be in this state, since account links must be public in a cross save relationship.

**Comment by joshhunt** [comment]
Is it expected that `?getAllMemberships=true` can be used to bypass this privacy option?

**Comment by Achronos-BNG** [comment]
No, that query option causes memberships overridden by cross save to be shown (normally non-primary accounts in a cross save relationship are hidden).
