### ISSUE TITLE
Should I hide the api key?

### ISSUE THREAD

**Issue by GitJaeSung** [Bungie-net/api#1536]
Hello.
I use jekyll, vanilla JavaScript. should i hide the api key? exposure seems inevitable when using vanilla javascript.
Can i hide the api key through jekyll, netlify? or can i reveal it?

**Comment by floatingatoll** [comment]
The API key system is designed such that no one benefits from stealing your API key, because they can just sign up for free and issue their own key with exactly the same access if they want to, so that you shouldn't have to worry much about theft. If someone misuses it someday, you can always replace it and update your Jekyll, but I've never heard of that happening, so it's not really likely to.

**Comment by GitJaeSung** [comment]
>The API key system is designed such that no one benefits from stealing your API key, because they can just sign up for free and issue their own key with exactly the same access if they want to, so that you shouldn't have to worry much about theft. If someone misuses it someday, you can always replace it and update your Jekyll, but I've never heard of that happening, and it's not really likely to.

Thank you for your answer!
