### ISSUE TITLE
activityWasStartedFromBeginning inconsistent

### ISSUE THREAD

**Issue by BlazeBoss17** [Bungie-net/api#1601]
The new field "activityWasStartedFromBeginning" in PGCR has a couple inconsistencies:

1. For all legacy PGCR (pre 2/21/2022), activityWasStartedFromBeginning returns False and startingPhaseIndex returns 1, regardless of whether they were started from the beginning or not. For example, pre Beyond Light PGCR used to have valid startingPhaseIndex in {1...n}.
2. PGCR for Last Wish (referenceId=2122313384) can return activityWasStartedFromBeginning = False, even when started from beginning with no checkpoint. Sometimes returns true as expected. Looking at population data, only 5% of last wish instance PGCR say they are fresh, compared to ~90% for other raids.

**Comment by jshaffstall-bng** [comment]
Sounds frustrating! Filed as TFS 1070650.

**Comment by Achronos-BNG** [comment]
We will have to look into the Last Wish issue.  I may be able to fix it for pre Beyond Light activities, but for Beyond Light to Witch Queen (the period of time startingPhaseIndex was completely broken) will not be able to ever be fixed.

Do you have a repro of a PGCR that started from the beginning of Last Wish that was done post 2/22 but has the wrong value for activityWasStartedFromBeginning?

**Comment by Achronos-BNG** [comment]
Okay - I'm going to fix this so that the code will no longer override startingPhaseIndex and instead change the documentation to reflect that pre-beyond light activities can use startingPhaseIndex but afterwards they can't.  Witch Queen and later activities will have to use the new boolean, and startingPhaseIndex will usually just be zero or otherwise be unreliable.  As for the issue with the Last Wish raid, we'll be looking into that but that is likely a game bug and I have no further details on that right now.  Test is going to look into it to get a better idea as to what is happening.

**Comment by MrLinks75** [comment]
Hi,
Been skimming through post WQ release PGCRs for dungeons, but also new raids clears (such as Vow of the Disciple), and it seems the inconsistencies regarding the behavior of the Boolean are still active.
Reference PGCRs (those activities were made post witch queen release) : 10368671459 || 10306552150
Even with the activity started from orbit with no cutscene skip, activityWasStartedFromBeginning seems to be extremely inconsistent.

Thanks in advance !

**Comment by BlazeBoss17** [comment]
@Achronos-BNG Something to pass onto test:

After doing some experiments, I think wiping an encounter causes an otherwise fresh run to return as a checkpoint.

**Comment by jshaffstall-bng** [comment]
Sorry for our delayed response.

We expect to have this fixed with the beginning of the next season, on May 24th. The fix won't be retroactive, but activityWasStartedFromBeginning will be preserved after a fireteam wipe.

**Comment by BlazeBoss17** [comment]
Fixed on 5/24.
