### ISSUE TITLE
Activity (Lost Sectors, Nightfalls) definitions list double and incorrect champion modifiers

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#1602]
> GENERAL ACTIVITIES 
> - On most activities that feature multiple Champion types, we now display a single combined activity modifier (e.g., Barrier and Unstoppable as a single icon) instead of a separate modifier for each one. 

The modifier is called "Champion Foes."

There is only one variation of the modifier description. As such, some activities are incorrectly labelled. The game content doesn't suffer from this issue and appears correct.

**Comment by justrealmilk** [comment]
@jshaffstall-bng

**Comment by jshaffstall-bng** [comment]
Interesting - can you get us screenshots of correct example in-game, and corresponding activity definitions with incorrect modifiers?

I wonder if there's run runtime state we need to start delivering to make the API more consistent with the game.

**Comment by justrealmilk** [comment]
The Glassway: Legend - activity hash `3812135452`

![tiger_release_final_20220316_040813](https://user-images.githubusercontent.com/156681/158443560-80dd4f97-4276-413b-95ed-50ebe4919418.png)

https://data.destinysets.com/i/Activity:3812135452

**Comment by jshaffstall-bng** [comment]
Thanks, this helped! Filed as TFS 1076131.

The activity modifier definitions are generated by Bungie.net, and it assumed unique titles, so definitions were hashed on the titles alone.

Obviously that is no longer feasible, so we can fix how these definitions are generated. Expect new hashes for all activity modifier definitions, and new definitions for the ones that were skipped because of duplicate titles.

We can also add new boolean properties for `displayInNavMode` and `displayInActivitySelection`. I think we can have this available on 3/22.
