### ISSUE TITLE
Error 1601 in Destiny2.GetProfile

### ISSUE THREAD

**Issue by CrunchyWizard47** [Bungie-net/api#164]
Going through my clan membership to collect details on their characters and get the above error on seven of the members. The returned JSON is `{"ErrorCode":1601,"ThrottleSeconds":0,"ErrorStatus":"DestinyAccountNotFound","Message":"We were unable to find your Destiny account information.  If you have a valid Destiny Account, let us know.","MessageData":{}}`

The destinyMembershipIds are 4611686018447002384, 4611686018452627488, 4611686018447911634, 4611686018430151316, 4611686018468099072, 4611686018460940319, 4611686018463024904.

The URI I'm using is `/Platform/Destiny2/1/Profile/4611686018447002384/?components=200` (obviously changing the membership ID for each member).

From what I can see, they're valid Destiny accounts.

Help?

**Comment by CrunchyWizard47** [comment]
Is there a possibility that these members have their privacy set so their information is not publicly available?

**Comment by iBotPeaches** [comment]
I haven't checked, but I usually get that error when I incorrectly make a Profile request with wrong platform. Based on that URL, all your requests are for Xbox Live guardians.

**Comment by CrunchyWizard47** [comment]
The clan member list shows they're type=1 (honestly haven't checked _every_ ID but at least a couple are). There's a possibility one or more are legacy members from the D1 clan who haven't played D2 yet. I'll have to do some more digging on this side. I can't say that I've played with any of them or seen them in D2 yet.

**Comment by caitriggs** [comment]
There definitely seems to be a difference between the membershipId returned by the call [SearchDestinyPlayer](https://bungie-net.github.io/multi/operation_get_Destiny2-SearchDestinyPlayer.html#operation_get_Destiny2-SearchDestinyPlayer) and the ID needed to call [GetProfile](https://bungie-net.github.io/multi/operation_get_Destiny2-GetProfile.html#operation_get_Destiny2-GetProfile). Since the membershipID returned by the SearchDestinyPlayer call is not the ID to use for GetProfile, where can we get the ID required for GetProfile?
