### ISSUE TITLE
Get the twab and the update link api

### ISSUE THREAD

**Issue by allbrochard** [Bungie-net/api#1726]
Hello, 
I'm a noobie with api and i try to have a simple link to get every twab and an other to get every update information. But i just found the NewArticles link but it give every latest articles.
can i have help please ?

**Comment by SolidKalium** [comment]
One option is to use the RSS feed and just filter to titles starting with "This Week at Bungie", "DESTINY 2 HOTFIX", or "Destiny 2 Update". This might miss some results because of human deviation but should normally work.
`https://www.bungie.net/en/Rss/NewsByCategory?category=all&currentpage=0&itemsPerPage=8&FILENAME=NewsRss&LOCALE=en`

---

Otherwise you could use the news index:
`https://www.bungie.net/en/News/Index?tag=news-destiny&page=0`
Limitation: Non-TWAB articles are included in `news-destiny`.

`https://www.bungie.net/en/News/Index?tag=news-updates&page=0`
Limitation: In the past some update articles were accidentally excluded from `news-updates`.

It looks like there was once a news-weekly-update tag, but it is no longer used as far as I can tell.

**Comment by allbrochard** [comment]
thanks a lot for your help !
