### ISSUE TITLE
Orphaned Lore

### ISSUE THREAD

**Issue by baxter** [Bungie-net/api#1797]
To figure out which lore entries belong to which lore books, I traverse the tree starting from the root lore node (4077680549) until I can figure out which entries belong to which books.

With the recent API update I've noticed that at least one entry (but I think there might be more than one) cannot be navigated to in this way.

"The Forest" (https://data.destinysets.com/i/Lore:2656540435) should belong to "The Beaten Path" but the record connecting the book to the lore entry does not have a `loreHash`.

https://data.destinysets.com/i/PresentationNode:4077680549/PresentationNode:2368205079/PresentationNode:1177466224/Record:3354387596

I think "I—From Great Distance" (https://data.destinysets.com/i/Lore:4033010921) suffers from the same problem.

https://data.destinysets.com/i/PresentationNode:4077680549/PresentationNode:2368205079/PresentationNode:2910802452/Record:569417316

Is this a bug? Should I be figuring out which entries belong to which books in some other way?

Thanks!

**Comment by joshhunt** [comment]
It appears the issue here is weird/inconsistent redactions. [Lore 2656540435](https://data.destinysets.com/i/PresentationNode:4077680549/PresentationNode:2368205079/PresentationNode:1177466224/Record:3354387596/Lore:2656540435) is not redacted, but it's [Record 3354387596](https://data.destinysets.com/i/PresentationNode:4077680549/PresentationNode:2368205079/PresentationNode:1177466224/Record:3354387596) has been redacted. 

In the game data Record 3354387596 does correctly link to it's lore entry, so the lore definition isn't _actually_ orphaned (in game data), but Record 3354387596's redaction makes it seem like it is. 

![image](https://user-images.githubusercontent.com/46142/222785192-1aa7f4c8-2f76-470b-8892-62b3fac17be7.png)

Once the record is unredacted, this should resolve itself.
