### ISSUE TITLE
Ability mods inflate stats for all items on characters

### ISSUE THREAD

**Issue by SunburnedGoose** [Bungie-net/api#181]
If a player equips an armor item with an ability mod, the +1 will be applied to all items equipped and unequipped on the character.  This inflation means the player cannot know the true stats for an item.

![screen shot 2017-09-27 at 3 05 51 pm](https://user-images.githubusercontent.com/984608/30935861-9ee15128-a397-11e7-88b4-5ff627d69544.png)

This exotic gauntlet has an ability mod that adds +1 to mobility.  If the gauntlets are not equipped, the helmet correctly reports its stats.

![screen shot 2017-09-27 at 3 05 10 pm](https://user-images.githubusercontent.com/984608/30935893-bb62d2c2-a397-11e7-9005-aab3b1b6979d.png)

Equipping the gauntlets will inflate the mobility stat for the helmet.

![screen shot 2017-09-27 at 3 04 57 pm](https://user-images.githubusercontent.com/984608/30935910-cf236d12-a397-11e7-957b-2e60f1369a1f.png)

This can be reproduced in DIM and the Destiny Companion App.  You do have to refresh the data from the API to see the stat inflation.

**Comment by vthornheart-bng** [comment]
I've found the root cause, and it's a doozy.  I'm going to consult with some people on the game team about it, but I also want your guys' input on a variant of this problem.

So in this scenario - armor affecting character stats - it feels obvious that you wouldn't want to see the mod's bonus on non-equipped armor, because the very act of un-equipping the armor will also un-equip that mod and remove the buff.

But what about scenarios where armor affects stats of other items, like weapons?  There are mods that affect weapons... and strangely enough, you can actually see even in-game that they affect not only the equipped weapon of that type, but the un-equipped ones as well, even though the tooltip for these mods claims it only affects the equipped weapon. However, in this case, having that feels... convenient.  At least if you're under the assumption that the armor providing the bonus will remain equipped.  But if you are, say, trying to evaluate the weapon independent of the equipped armor, perhaps this will similarly cloud your judgment about which weapon to use.

... what do you all think about this variant?  Would you want to see the bonuses that apply to types of items other than the type of item whose mod is providing the bonus to still be returned?  Or would that cloud objective decisions, or perhaps even just plain be confusing?

**Comment by vthornheart-bng** [comment]
Just to note, I was looking into this back in November, but tabled work on it for other features (PGCR player reporting, Postmaster transfer, DLC 1 support).  I was just asked about it separately, and I wanted to add some notes about my current thoughts since it has come back up.

Right now, my gut is that I should *not* return these weapon/armor stat boosts on the items themselves except for already-equipped items (who are actually having the bonus applied to them).  This will remove the original bug mentioned above, as well as some of the unexpected edge cases (like the bonus being applied to un-equipped items).  It's not ideal, but it is likely going to be the best win we're going to get in a reasonable amount of time.

---

I have a "nice to have"/"unsure if practical" alternative where instead we return data either on the item providing the boost or on the Character indicating:

1) What item is providing the boost (if this data ends up on a Character component)
2) What stat is being boosted
3) How much the stat is being boosted
4) What types of items the boost applies to

That would allow items' stats to be returned independent of other entities affecting them, but then to also have the data you'd need to see how that item is being modified by other items if you care to use it in your calculations.

However, I'm not entirely certain that this will be reasonable: it's possible in particular that I can't give one value that globally applies to all affected items for (3).  I haven't had time to investigate.

Right now my approach when I get back to this is going to be to do the first fix, and if we ever have time to dig further I'll look into the feasibility of the second separately.

Let me know your thoughts if you have a strong opinion on the issue.  I don't feel great about this solution, and I get the feeling that it will not fix everyone's potential use cases.

**Comment by designker** [comment]
Not applying the stat boost from a mod would be fine. We can then look at what is plugged into the mod socket to see if an extra should be applied. This will also be great in the future if you ever allow plugs to be inserted via the API. It can take a second or two for the api to come back with the right values. But if we are working them out locally we can calculate them instantly and show the relevant values.

**Comment by vthornheart-bng** [comment]
Excellent, sounds good to me!  Thanks for the input!

**Comment by SunburnedGoose** [comment]
Inconsistent application won't help. Agree with just letting us work it out.

**Comment by vthornheart-bng** [comment]
Cool - okay, I have made the changes in preparation for the next release.  I think it should do well - just note as we said that you won't get stats being provided to specific types of items *from* mods on other types of items any longer.  An armor mod that says "Provides your equipped power weapon with additional handling" will still provide that handling to an equipped power weapon, but that modification will no longer be reflected in the data coming down from the API.

We'll see how we feel in practice.  I think it's a good move, I just still have some reservations.  If this still ends up feeling dissatisfying, we'll have to reconvene on it later.  But at least it'll fix the more glaring item stat issues being caused by it.

**Comment by vthornheart-bng** [comment]
At last, this is fixed.  The caveats mentioned above will continue to be true - about how, if you care about these modifiers, you'll have to discern them for yourself.  But it sounds like having the real stats in isolation are greatly valued over that, so I think this was the right move.
