### ISSUE TITLE
Destiny2.GetHistoricalStatsForAccount information

### ISSUE THREAD

**Issue by rentalhost** [Bungie-net/api#184]
I need to know some infos about this API, if possible:

* What mean: `allParticipantsCount`?
* What mean: `allParticipantsScore`?
* What mean: `allParticipantsTimePlayed`?
* What mean: `remainingTimeAfterQuitSeconds`?
* What mean: `objectivesCompleted`?
* What mean: `bestSingleGameScore`?
* What mean: `score`?
* What mean: `teamScore`?
* What mean: `weaponKillsRelic`?
* What mean: `{*}.pga` in some attributes?
* Additionally: seems that `secondsPlayed` as `totalActivityDurationSeconds` values are inverted. For instance, for my account, `secondsPlayed` is `3d 0h`, and `totalActivityDurationSeconds` is `4d 14h`. I have played more activities than I have played the game? If it is not the expected behavior I will open a new issue.

Thanks for attention!

**Comment by vthornheart-bng** [comment]
Greetings!

allParticipantsCount = the total # of people who played in the activity, be it from beginning to end or transitorally (they entered and subsequently left before it was over)

allParticipantsScore = the combined score of all participants.  Score means different things in different modes: for instance, in PvP it is the point contribution to your team's score.

allParticipantsTimePlayed = the sum of the amount of time in which all participants played the activity.

remainingTimeAfterQuitSeconds = if you left the game early (aka if you bailed before a PVP match ended), this is how much time was still remaining in the game when you left.  (so if you jumped ship 5 seconds into a match that ended up being 20 minutes long, this would be 19 minutes and 55 seconds)

objectivesCompleted = I'll have to ask about that, I don't actually know what that stat means!

bestSingleGameScore = This is a leaderboard stat that you can use to compare, for example, your best score with your friends or your clanmates for a given activity mode.  For instance, perhaps you played a really great game of Control and scored a bunch of points.  You could compare the best Control match you ever had to your friends' best.

score = Depends on the mode, usually this translates to the match score in PVP.

teamScore = Same, but for your whole team.

weaponKillsRelic = If you had access to a special temporary-use item provided by the level itself, rather than an item or ability on your character, this would be how many kills you got with that special item.

I'm not sure offhand what you're referring to with the {*}.pga, can you give an example?

Yeah, open a new issue for the totalActivityDurationSeconds situation, I'm not sure about that but I can refer someone who may know.

**Comment by rentalhost** [comment]
Thanks a lot.

![image](https://user-images.githubusercontent.com/421851/31571718-8402126e-b06e-11e7-8e36-3fa069c1a2bc.png)

You should note the `pga` key. Maybe something like "per game activity", but I too don't know what it means.

**Comment by cortical-iv** [comment]
My working guess has been that _pga_ stands for 'per game average'. The other stats give totals (e.g., total kills), while pga gives the average number of kills per match/event.

**Comment by vpzed** [comment]
You are correct.  [It's in the API spec here](https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-DestinyHistoricalStatsValue.html#schema_Destiny-HistoricalStats-DestinyHistoricalStatsValue)
