### ISSUE TITLE
Allow for dismantle and infusion

### ISSUE THREAD

**Issue by chelor** [Bungie-net/api#187]
Hey Guys, I've been using tools that leverage the destiny API this since D1 and realized that this key feature to do online management was never there.

Is there a reason why this was not implemented?

**Comment by floatingatoll** [comment]
As an app beta tester, I implore Bungie to never permit irreversible actions through the API. Every app I’ve seen reviews of gets waves of anger and hatred every time they think a helper app deleted a weapon that can only be deleted in-game. If apps were permitted to delete, people would rage legitimately at the risk. By maintaining it read only, you at least offer a simple and inviolate defense against these folks who sharded gear: Apps cannot do that, Bungie simply doesn’t offer that, even to their own app.

**Comment by vthornheart-bng** [comment]
I'll pass this on, I think it is good to see both sides of this issue.  There's definitely a strong distrust of the safety of apps: partly, I think, because this is such a new experience in games.  I can definitely see the reason why destructive actions could only serve to make that (incorrect) perception worse.

However, I do think there are potentially good ways to make it so that the user can come to trust destructive actions, and so that apps can opt out of even having destructive actions in their allowed scopes, if such actions were ever to be allowed.

For now, I'm going to close this issue - as the truth is that there were both design and security reasons why we have not allowed for destructive actions up to this point.  I don't know what the future will hold for destructive actions, but you can be assured that *if* they ever exist they will be locked down in such a way that will hopefully alleviate the fear of apps that use it, and in such a way that apps can clearly choose not to have any association with destructive actions.  And if that world ever comes into existence, there will be much more conversation here on the subject!
