### ISSUE TITLE
[Question] Possible to get Nightfall modifiers?

### ISSUE THREAD

**Issue by jgayfer** [Bungie-net/api#201]
Is it possible to get the nightfall modifiers in some round about way? Or is there a timeline on when these will be available? Currently I just see them as "Classified"

**Comment by kbreit** [comment]
Some of the modifiers are declassified but many aren't. It will be hit or miss for the time being.

**Comment by xlxCLUxlx** [comment]
All modifiers except for one are declassified.  This is true even in the mobile and web page for Bungie.  I am guessing they do this to try and keep some mystery and get people in game.  It would nice if they declassified a modifier after it has been used.  If you really wanted to go to the trouble you keep track of the modifier hashes on a weekly basis as modifiers have now been reused you could start cross referencing them against previous weeks modifiers and deduce what the hashes represent.  Basically have a lookup structure and if the modifier is still redacted then go to your structure.  For example this weeks nightfall has hashes 3974591367 (Attrition), 1183352841 (Timewarp: Killing Time).

**Comment by vthornheart-bng** [comment]
Yes, sorry about this guys - we've been told that we can't un-redact them until they are shown in the game, and due to my absence the un-redactions of new ones didn't occur on schedule.  Our deployment next week should reveal more of them, and eventually they will all become un-redacted.  I know it's a total pain in the butt from an API usage perspective, thanks for bearing with us.

I'm going to close this for now, as we will continue to un-redact these when we are allowed to!

**Comment by hskrasek** [comment]
@vthornheart-bng Sorry to dig up a closed issue, but does that mean the API will soon unclassified Zero Hour and Torrent? Noticing those two are showing up as Classified still. A third one is also classified, but I can't tell if that's me having horrible memory on what's available as modifiers.. or if Bungie has something hidden coming in the future.

**Comment by lowlines** [comment]
There's still classified modifiers including one this week.
https://www.bungie.net/en/Explore/Detail/Event/2171429505
