### ISSUE TITLE
exclusive field isn't set on PS4 exclusive items

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#211]
Tesseract Trace IV (2811180959) is PS4 exclusive so I would expect it to have the `sourceData.exclusive` set to a useful value, but it isn't.

In fact none of the items in InventoryItemDefinitions have exclusive set - it's `0` for everything.

**Comment by vthornheart-bng** [comment]
Yes, this is an issue that we are currently experiencing - our old algorithms to determine this are not functioning at the moment.  I'm going to leave this open - for now, we don't have an ETA for when we're going to fix it.

We are going to be adding, in the next few weeks, a field to DestinyVendorDefinition's sale items that you can use to see whether the offer is exclusive: but I'm not pumping that value through to the DestinyInventoryItemDefinition yet, because theoretically (though not in practice, so admittedly this is a bit pedantic of me and I'm realizing that even as I'm typing this) you could have a vendor item for sale that is exclusive to a platform but the item itself isn't platform exclusive.

But even as I type this, I realize that I'm being pedantic.  I'm just afraid that the assumption could end up being brittle, and I am considering a more robust solution that may be feasible.  If the more robust solution doesn't pan out, I may go ahead and just take this more brittle but also immediately useful heuristic.  Stay tuned.  I'll keep this open until it's resolved one way or another.

**Comment by bhollis** [comment]
Now that exclusives are gone you can probably close this.

**Comment by vthornheart-bng** [comment]
Phew, thanks for spotting this ancient bug!
