### ISSUE TITLE
[Question] about kiosks

### ISSUE THREAD

**Issue by Ashesheart** [Bungie-net/api#220]
Hello,

i'm currently trying to know which emblems/exotics and more an user have. 

When i called 
`/Destiny2/2/Profile/4611686018441638922/?components=500`

i have this information 
![d2api](https://user-images.githubusercontent.com/32743115/31504676-47b5450c-af73-11e7-9a20-8b94c112f5fd.png)

But what is "index" ?

Thanks a lot for your help

**Comment by xlxCLUxlx** [comment]
I believe you want to query the DestinyVendorDefinition table in the  world_sql_content database.

For example:

`SELECT * FROM DestinyVendorDefinition WHERE id = 622587395`

This should return the vendor definition JSON string which contains an itemList array (`#/definitions/Destiny.Definitions.DestinyVendorItemDefinition` if you using OpenAPI implmentation).  You will be able to get the itemHash based on the index value that you are asking about.

For example, I am displaying just index 20 below from your example for the definition of vendorHash 622587395.  You will really have indexes for 0-192 in the itemList when you execute the query above.  But this gives you an idea through a snippet.  In your example index 20 would relate to vendorItemIndex 20 in the itemList.

```json
"itemList": [
    {
      "vendorItemIndex": 20,
      "itemHash": 4077939647,
      "quantity": 1,
      "failureIndexes": [],
      "priceOverrideEnabled": false,
      "refundPolicy": 0,
      "refundTimeLimit": 15,
      "rewardAdjustorPointerHash": 0,
      "creationLevels": [
        {
          "level": 0
        }
      ],
      "displayCategoryIndex": 3,
      "seedOverride": 0,
      "categoryIndex": 5,
      "originalCategoryIndex": 5,
      "weight": 0,
      "minimumLevel": 0,
      "maximumLevel": 0,
      "licenseUnlockHash": 0,
      "action": {
        "executeSeconds": 1.5,
        "isPositive": true
      },
      "displayCategory": "",
      "inventoryBucketHash": 4274335291,
      "visibilityScope": 3,
      "purchasableScope": 3
    }
```
Then in turn when we query the DestinyInventoryItemDefinition for itemHash 4077939647 in the above JSON which is for the Laurel Triumphant emblem.

Unfortunately, itemList is implemented as a List rather than a Dictionary so you will have to iterate the List and search for each index or if your language supports some kind of way to query the list (i.e. I use C# in conjunction with LINQ where I can execute a WHERE on the list).

Anyway I hope this kind of explains and gives you the information you were looking for.

**Comment by ckhicks** [comment]
This is actually super helpful for me on another side issue. I've been 
looking at database structures other than the stacks of SQL content and 
it really helps to see someone else doing queries for things. Thanks for 
the good example of your thought process.

**Comment by Ashesheart** [comment]
Thanks for your help, i'll try this.
