### ISSUE TITLE
Incorrect icon in IB: Season 1

### ISSUE THREAD

**Issue by kbreit** [Bungie-net/api#222]
I'm not sure if you're responsible for the Manifest file. However, the Manifest has hash 612307426 under DestinyInventoryItemDefinition which specifies displayProperties.icon. Icon is /common/destiny2_content/icons/d15f19ac27f0c685a30c6e68532ad182.png which is showing as 404 on bungie.net

**Comment by xlxCLUxlx** [comment]
I have also run into this issue in regards to milestones as well.  You can see issue [185](https://github.com/Bungie-net/api/issues/185) that I created that is similar.

What I have been doing in the meantime to deal with this until the issue is resolved is a I create a request to see if the image/icon I get from the manifest is correct.  If I receive 404 Not Found then I call the following endpoint:

`/Destiny2/Manifest/{entityType}/{hashIdentifier}/`  

You can see the documentation here: [Destiny2.GetDestinyEntityDefinition](https://bungie-net.github.io/multi/operation_get_Destiny2-GetDestinyEntityDefinition.html#operation_get_Destiny2-GetDestinyEntityDefinition).  

For example you would call 

`/Destiny2/Manifest/DestinyInventoryItemDefinition/612307426/`  

Since the rest endpoint is hitting their manifest database it seems to return the correct image/icon for me.  Like I said I try the manifest first and test it via request and only call the endpoint if needed to reduce calls.  This seems to be a successful workaround for the time being.
