### ISSUE TITLE
Question on Unique Hashes

### ISSUE THREAD

**Issue by ckhicks** [Bungie-net/api#223]
I'm looking at ways to simplify the data structures a bit for easy lookups and testing. As I was pouring through the Manifest it occurred to me that the hash is likely unique for each item in your system, correct?

For example, when looking through DestinyFactionDefinition I noticed that The Nine is listed twice, even with the same info, but still has their own unique hashes. This made me hopeful!

Can we safely assume that _every_ hash in _any_ table will always be unique, or is there a chance that we may have duplicates once we start looking at queries throughout the entire collection?

**Comment by ArkahnX** [comment]
You are only guaranteed to have unique hashes within a given definition, not across the whole manifest

**Comment by ckhicks** [comment]
Darn, worth a shot, even if slim. :P Thanks!

**Comment by vpzed** [comment]
@ckhicks I can confirm the hash values are not globally unique in the manifest even by happy accident.

**Comment by ckhicks** [comment]
Back to the drawing board - thanks for confirming. 👍

**Comment by vpzed** [comment]
@ckhicks I still make a "combined table" with all the entries in it (in addition to the normal tables) in my app's database because even though the hashes aren't globally unique it is helpful for prototyping.  I add a field for the source table name as I populate it.  So when as often is the case, I don't know which table I need to use for a given <whatever>Hash lookup, I query the hash in the "combined table", look at the table names that return and print them out.  Most often there is only one table returned and even when there isn't, it is usually pretty obvious which table is really the one I want.  Then I can go back and update the code to point to the specific table. It's quite handy.

**Comment by ckhicks** [comment]
That's a really good idea - I've been trying to think of ways to make 
things easier for new devs and this is exactly the kind of stuff that 
can help someone dig deeper into the data. While I know we're a very 
language-agnostic community, even projects/interpretations like 
https://destiny.plumbing are super great for inspiration, data 
awareness, etc. Thanks again for the input!
