### ISSUE TITLE
"Fresh run" flag request

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#228]
I would love a way to check if a given activity was a fresh run opposed to a checkpoint. We are trying to add a few features that are impossible without this.

I am making a raid speedrun leaderboard, but it will not be very meaningful if it includes boss checkpoint runs:

| InstanceId | Leaderboard |
|-------------|---------------|
| 716410278 | 9m 5s |
| 717532377 | 12m 32s |
| 717565038 | 14m 18s |

In the past, I could look at the enemies killed and figure out what cps they played (although this logic is not 100%); however, enemy kills are no longer included. 

A fresh run flag would also enable us to see if a given run was "flawless," ie fresh and deathless.

**Comment by BlazeBoss17** [comment]
After five months of development effort, we finally launched raid leaderboards today at http://raid.report/  It was a colossal undertaking, but we now track every single activity played in Destiny, similar to TrialsReport. 

I am happy with the results, but we could add and improve a lot of functionality with a fresh run flag. For example, the raid lair speedrun record is currently 3m 15s, but that is a worthless value because it is only the boss checkpoint, not the whole raid. A fresh run flag would allow us to filter to only display full runs, so that the value would be closer to the 18m legit value. The flag would also let us add a "Flawless" badge to go for, similar to the Destiny 1 trophy. 

In Destiny 1, aggregateActivityStats' fastestCompletionTime variable only included full raids, but in Destiny 2 checkpoints and full runs are included. Even if that value can be changed, we still want a flag in the postgame because we build all data from postgames.

I know any change like this would require resources that would have to be weighed against a potential value add, but this feature would result in giving many players more reasons to run raids, as our users keep telling us.

Thanks for the awesome API! Your team does really pioneering work,, and I think it's something that sets Bungie (and Destiny) above the competition.

**Comment by vthornheart-bng** [comment]
Nice man, that looks fantastic!  Very well done!

I'll send this over to the team, see if there's anything that can be done on that front.  I know it's been a popular request. :(

**Comment by BlazeBoss17** [comment]
We are scraping all PGCRs.

**Comment by vthornheart-bng** [comment]
Sweet - good to know!  That could be a good avenue then, excellent.  I'll bring this all to their attention!

**Comment by TorKallon** [comment]
waterpolotrev67 and I have also requested this for Charlemagne. A PGCR flag would also work for us, as we are also scraping PGCRs. Reparsing all of the Raid PGCRs would be pretty trivial, so adding that would be truly awesome. This is probably the number 1 request from our users for the last four months.

**Comment by vthornheart-bng** [comment]
Ah yes, I have not forgotten!  It's a good request - I've hit up the Stats folks for it, and I'll be keeping you all posted on it.  When stats bugs or missing features are due to the underlying data, the turnaround can be a lot longer because that ends up on the game's release/triage/greenlight schedule rather than BNet, but it is on their plate!

**Comment by BlazeBoss17** [comment]
Have the stats people had a chance to look at this issue yet?

**Comment by vthornheart-bng** [comment]
Ah, yes!  I have filed requests for two features from this:

TFS 628265, Adding StartingPhaseIndex to the PGCR blob
TFS 628268, to stop storing fastestcompletion if the starting phase index is > 0

I don't know when they'll have time to get to them - they are swamped.  But I optimistically put in the request for them to be part of an upcoming update later this year.  I can't unfortunately promise that it'll happen, but we've at least got it on the books.

**Comment by ChaseMalik** [comment]
@vthornheart-bng 

With today's release the `fastestCompletionMsForActivity` is only getting updated on fresh runs (#132 and TFS 628268), so I was wondering if you have any update on TFS 628265, as I thought they would be bundled together.

Thanks

**Comment by BlazeBoss17** [comment]
I was under the impression that TFS 628265 (Adding StartingPhaseIndex to the PGCR blob) was releasing in July as alluded to in #132: "PGCRs from [the July release] forward will have this change." To prepare for its release, our team invested resources in a patch to take advantage of this new feature.

Now that both 1.2.3 and this week's backend deployment have passed, it looks like I was unfortunately wrong. :(

The other feature request mentioned in this issue TFS 628268 (stop storing fastestcompletion if the starting phase index is > 0) was added in 1.2.3. This is a nice change, but it doesn't solve our use case as it is impossible to aggregate this information on a global scale in real-time (unlike postgames). 

We would do anything to get startingPhaseIndex exposed in the postgame JSON. Our entire website's backend was based on the hope that we would one day have this variable and a huge amount of functionality hinges on it. And I know other community developers would also love to see this get added (Charlemagne in this thread).

I know you all are busy with Forsaken work, but can you set reasonable expectations for us (before Forsaken, with Forsaken, further out)?

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into this - indeed, I thought this had been released.  I may have misunderstood something.  I'll take a look later today and see what I can find out.

**Comment by vthornheart-bng** [comment]
Well, crap.  Sorry @BlazeBoss17, this is totally my bad.  The Wizard of Stats(tm) got this working in the underlying system, and the reason why it's not coming through is because there was additional work that had to be done on our side before it'd actually be exposed externally.  That's totally my bad, I missed that.  I'll see to it that it goes live with the upcoming release!

**Comment by vthornheart-bng** [comment]
Okay, so next time we release, we'll have a "startingPhaseIndex" property on DestinyPostGameCarnageReportData (a peer property to "period", "activityDetails", "entries" etc...)

It will be a nullable int, so if it's null then there was no phase data.  Otherwise, it'll be an integer matching the index of the phase at which the activity started!  I'll be checking that in shortly.  My apologies for the miss!

**Comment by vthornheart-bng** [comment]
Okay, good news that came from unexpected news.  We have to cancel our August 8th deployment, but as a result I'm being allowed to bump this into the July 31st patch/hotfix deployment!

**Comment by bladefist** [comment]
@vthornheart-bng  on new matches going forward or all prior matches have this?

**Comment by rentalhost** [comment]
I have checked it an seems that it could be marked as done. I just think that it is `0` if is a fresh run.

![image](https://user-images.githubusercontent.com/421851/55030451-2a791d00-4feb-11e9-9544-37fd4b780a90.png)

**Comment by vthornheart-bng** [comment]
Ah, thank you!  Indeed, I forgot to mark it as done!
