### ISSUE TITLE
Armor Perk - Intrinsic - Name in description

### ISSUE THREAD

**Issue by duckmanBR** [Bungie-net/api#232]
For exotic armors, the intrinsic perk is returning the name (followed by a line feed) in the description...
![screenshot_20171017-122102](https://user-images.githubusercontent.com/32077894/31670677-df548f78-b336-11e7-8ec6-b7c53f63c19a.jpg)
![screenshot_20171017-122154](https://user-images.githubusercontent.com/32077894/31670680-e15e45ac-b336-11e7-956b-0def9ae3cb3a.jpg)

**Comment by vthornheart-bng** [comment]
When I get the time, I'd like to remove those.  The game itself actually has them, and apparently must also have some logic whereby it shows that instead of the combination of name + description, which is somewhat frustrating.  We can do some cleansing on our side to strip it out, which would be preferable.

**Comment by bhollis** [comment]
This appears to be fixed: https://data.destinysets.com/i/InventoryItem:3927963100

**Comment by duckmanBR** [comment]
Yep, it is.
