### ISSUE TITLE
Simple Question Regarding "completionReason"

### ISSUE THREAD

**Issue by ChemDataFarmer** [Bungie-net/api#235]
Hi all,

I've been going through the activity history and was wondering what the various possible values for "completionReason" correspond to.

It seems like a value of 0 means the match completed on either time or points. However, I've seen a few instances where the value was 255. In these cases, the character I am viewing typically has won the match and the duration of the match is very short, so I assume this is from the other team backing out. However, I'd like to be sure and I'd also like to know what other values this can take and what they mean.

Can anyone point me in the right direction?

**Comment by vthornheart-bng** [comment]
We need to document this better, but here's the completion reasons!

0 = "Objective" (finished because the objective was completed: in PvE, this means you "won".  In PvP, this means one team/player won)

1 = "Time" (finished because the timer on the activity ended)

2 = "FailedActivity" (finished because you were forced out of the activity due to loss, such as in D1 Nightfall where wiping caused you to die and be booted out entirely)

3 = "NoOpponents" (finished because only one team remained in PvP)

4 = "Mercy" (finished because of the PvP Mercy rule)

255 = "Unknown" (Unfortunately, there are a variety of reasons that this can happen, and we don't have a way of knowing which.  But the most common scenario is in a PvE activity where everyone quits.  From what I am told, this always means a "failure" or "abandonment" of the mission in some way or another though: you should never see 255 as the completion reason for a successfully completed activity)

**Comment by Tetron-bng** [comment]
I added a bug to make this value more strongly typed in the API which will give a place to put this info in the generated documentation.

**Comment by ChemDataFarmer** [comment]
Excellent! Thanks for spelling these out for me! This will make things much easier :)
