### ISSUE TITLE
Leaderboard endpoints

### ISSUE THREAD

**Issue by ashleypb** [Bungie-net/api#236]
Stumbled upon the Leaderboard endpoint in the documentation. 

Whats the end goal with leaderboards? I see there's maxtop, modes & statid parameters. Will it be for PvE, PvP or both?

The description for 'Destiny2.GetLeaderboardsForCharacter' reads that it may be close to release albeit with possible bugs. IS it still on track?

Ive tried to test a response but just hit a error 'WebAuthRequired'.

Will it not be possible to simply query using the standard API key?

Doesn't WebAuth require the user to login with Sony or Microsoft using their PSN or Live account details, can't see users wanting to login each time they want to view someones leaderboard position?

**Comment by vthornheart-bng** [comment]
Ah, yes!  The idea with the Leaderboards was so that you could compare your score to your friends or your Clanmates.  That's why it requires authentication: we don't let you get an arbitrary player's leaderboards, only your own.  (partly because it's an expensive operation for us to do that aggregation, and partly because we wanted to discourage people treating or trying to use Leaderboards as something that they could make global inferences from)

There are still some Stats bugs, but most of the systems - including Leaderboards - should be pretty much ready to go now.  The most severe bugs have all been resolved, but we're always open to hearing about new bugs if you find them!
