### ISSUE TITLE
New since recent update - ThrottleLimitExceededMomentarily(36)

### ISSUE THREAD

**Issue by afehners** [Bungie-net/api#244]
Since the most recent update to Destiny yesterday I now see the following error regularly when trying to bulk transfer a number of items.

ThrottleLimitExceededMomentarily(36) - Patience is a virtue! Please wait a moment before performing this action again.

I rate limit all calls to the 25/second over 10 second window. The point at which I get this error is when trying to move items for a loadout. I see it happen as early as moving the third item, with a call count of 3 per second at that point.

Is this new expected behaviour or a bug? I didn't see this once yesterday before the hotfix, but see it every single time today.

**Comment by Tetron-bng** [comment]
You are hitting a different type of throttle.  You will notice the response itself will tell you how long to wait before calling the API again.  I believe we limit you to one request per second for transferring items for a particular account.  This is not new to the recent update.

**Comment by afehners** [comment]
That's strange, I never saw this previously and was transferring far bigger numbers of items during my testing:

Error message doesn't contain a time to wait either:

{
    ErrorCode = 36;
    ErrorStatus = ThrottleLimitExceededMomentarily;
    Message = "Patience is a virtue! Please wait a moment before performing this action again.";
    MessageData =     {
    };
    Response = 0;
    ThrottleSeconds = 0;
}

**Comment by Tetron-bng** [comment]
ThrottleSeconds is the value I was referring too.  It may be a subsecond wait time (Thus the "Momentarily" error code).  Not sure why you are hitting this now, but it seems you just barely exceeded the threshold. @vthornheart-bng  is the real expert in this area, not doubt he will chime in when he get a chance.

**Comment by floatingatoll** [comment]
For someone who needs to transfer and equip a loadout of 9 items (3 wep, 1
ghost, 4 armor, 1 class), what is the appropriate interval to wait between
each transfer? Can equip calls be interspersed with transfer calls to make
use of the downtime more effectively?

**Comment by afehners** [comment]
I’ve now seen this returned as early as the second transfer call in a set. My suspicion is that this is getting returned if two or more transfer calls are being processed by Bungie.net at the same time

**Comment by vthornheart-bng** [comment]
So, the lack of throttling that was happening was actually a bug: we need a throttle to be applied, just as it was in Destiny 1.  Like in Destiny 1, the throttle is still set to 1 request per second: but because the throttling was not working for the first month or so, unfortunately everyone got used to there not being that throttling.  And perhaps that's a good sign - perhaps we can reduce it somewhat.

I'll need to talk to people about that though before I can make any promises in that department: the throttling is in place to protect the upstream systems from malicious users, and so I can't make the decision to remove it unilaterally.

**Comment by vthornheart-bng** [comment]
Okay, so here's the gist of the situation: the throttling that we apply should merely delay your response and not return exceptions *if* you are performing your requests serially.  If you perform them in parallel, you're going to run the very real and intentional risk of having ThrottleLimitExceededMomentarily returned.

We're going to tweak with the throttle time, and try reducing it so that serial requests can go through more quickly: but we would like to discourage parallel write requests.  The next time we deploy we'll try a much lower throttle (sub-second) to speed up your equipping, but in exchange those of you doing parallel equip requests for a single account should switch to doing those requests in serial if you want to prevent hitting the ThrottleLimitExceededMomentarily error code.

**Comment by ArkahnX** [comment]
@vthornheart-bng what is defined as "Serial" vs "Parallel" on bungies end?

Is it based on when the server receives the request, or based on when the user sends the request?

For instance, if I send a request every second to the transfer / equip endpoints, as long as they are 1 or more seconds apart they should be counted as serial?

**Comment by floatingatoll** [comment]
You won't be able to implement 'serial' with a timer - the only safe way to
do it is to wait for one response before transmitting the next request.

**Comment by Tetron-bng** [comment]
Serial means you don't send the next request until the previous request returns a response. This is with respect to equip/transfer actions to the same Bungie.net user.

**Comment by afehners** [comment]
Thanks for the clarrification @vthornheart-bng, that makes sense, I used to do transfers serially in D1 but noticed I could do them parallel in D2 and they were really REALLY quick so switched to that and made sure they followed the rate limit rules, which I now see they aren't governed by.

Speeding up the delay between calls would be great. A common task in my app would be to select an item to equip before doing a raid. This item will usually reside on their last character to raid and so requires a series of calls such as (equip item on second character to free item up -> transfer item to vault -> transfer item to character -> equip item.. With those imposed 1 second delays the user at best will be waiting over 2 seconds. When they are doing this with a saved loadout, usually moving over all three weapon types its now a minimum of 6 seconds. That makes for a poor user experience with a waiting/loading widget spinning for that long.
