### ISSUE TITLE
Bungie.net privacy settings and the API

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#246]
Is there documentation on how the Bungie.net privacy settings impact the API and/or how applications should be interacting with the privacy field returned in some API responses?

From what I can see on Bungie.net there are these options that appear related to privacy:

> Settings > Accounts & Linking > Authenticated Accounts > (platform)
 - Display on public profile

> Settings > Privacy > Bungie.net Privacy
 - Show your Forum activities to other Bungie.net members
 - Show who follows you and who you are following on your Profile page

> Settings > Privacy > Destiny Privacy
 - Show my Destiny game Activity Feed on Bungie.net
 - Show my non-equipped Inventory
 - Show my Progression
 - Allow Clan Invitations for (platform) account

In the API spec we see reference to privacy in Components.ComponentPrivacySetting enum:
 - None: 0
 - Public: 1
 - Private: 2

Many spec schema references include the "privacy" field which references this enum.

And in the Exceptions.PlatformErrorCodes enum:
 - DestinyPrivacyRestriction: 1665

However, I'm based on using the API I don't understand how these relate to each other or how this is supposed to be implemented on the application side.  

One example is sometimes I get a privacy: 2 value in an object but there is still other data returned.  Should I not be storing and/or displaying data in an object that has privacy: 2 in it?

Another example is what would be a situation where ErrorCode 1665 would be returned?

If anyone has guidance on these details, please let me know.

**Comment by vthornheart-bng** [comment]
Ah, so that privacy field was an attempt by us to return information about whether that component is considered publicly or privately available by the API: that is, whether we may restrict its return.  We were picturing using it mostly for our own debugging and testing purposes, and figured theoretically that people might find it useful to know what the server considers to be a public vs. a private/potentially restricted component.

In practice, we probably could have just had this as documentation on our side: I don't picture our privacy restrictions changing enough that they need to be returned dynamically, and indeed the values don't change depending on whether or not there's actually data that was returned: for instance, if someone allows others to see their non-equipped inventory, the API will still return the inventory components as having the "private" value.  It merely means "we're checking privacy settings for this component."

Indeed, feel free to ignore it.  If I had it to do over again, I probably wouldn't include it in our results.
