### ISSUE TITLE
Legend of Acrius

### ISSUE THREAD

**Issue by joshhunt** [Bungie-net/api#267]
There's two Legend of Acrius's in the database, one which is the 'fake' mission item, and another which is the 'real' weapon. I thought I knew the different hashes for them, but I keep getting reports that I get it wrong either way I do it (and I'm a casual so I don't have the weapon).

I thought `3580904580` is the 'fake' mission item, and `1744115122` is the real one.

Is it possible to distinguish the two in the API, or are we able to get manual confirmation on which is which?

**Comment by xlxCLUxlx** [comment]
Hi @joshhunt,

I queried a user who has the weapon and I see hash `3580904580` as being the one equipped on the character.  This also make sense since this hash has all of the `socketEntries`.  I am not sure if hash `1744115122` is an entry that should be removed from the manifest or not.  You should be able to just use `3580904580` in the meantime though.

[https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018448361367/Character/2305843009268128836/?components=205](https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018448361367/Character/2305843009268128836/?components=205)

**Comment by vthornheart-bng** [comment]
Hmm, interesting - yes, it seems that these items in question have "previewItemOverrideHash" populated with the hash of the "fake" version of the item.  Unfortunately, I don't know offhand whether every preview item is similarly fake, or whether they sometimes point to "real" versions.

I'm going to log this as an enhancement request... I'll need to investigate.  We don't get any explicit distinction given to us in the data about which is real and which isn't, so we'll have to find some heuristics to generate such a response for you (for instance, if it turns out that items pointed at by previewItemOverrideHash are always the fake/uninstantiable versions of items, then we could flag them as such - perhaps with a new ItemCategory and ItemType enum value.

**Comment by xlxCLUxlx** [comment]
Hi @joshhunt and @vthornheart-bng,

I think I see what is going on which these two versions of the "Legend of Acrius".  I finally acquired this and was able to query my character see what is gong on.

After completing the "Arms Dealer" Quest Strike (Quest awarded once beating the Leviathan raid) you will be awarded the "Legend of Acrius" with hash `1744115122`.

You can view this version here and specifically click on the mods button you will notice it only has the "Shock Blast" perk and nothing else.
https://www.bungie.net/en/Explore/Detail/Item/1744115122

Once you have this version of the "Legend of Acrius" you need to go back into the Leviathan raid and collect 10 of the emperors seals.  You will then unlock the "Legend of Acrius" with hash `3580904580`.

https://www.bungie.net/en/Explore/Detail/Item/3580904580

You can see that this version has additional perks, weapon mods and oranaments when clicking on the mods button.

Based on how weapons are now handled in Destiny 2 my assumption is the sandbox designers had to create two versions of this weapon since they have different perks (i.e. are different builds of the same weapon).  It appears you first get `1744115122` and once you acquire `3580904580` then `1744115122` gets deleted from your inventory.

**Comment by vthornheart-bng** [comment]
Ah, interesting - yeah, and there's not much that we can do about that: particularly if they're both items you can actually earn in-game.  I'm going to go ahead and marked this closed for now, there's not much we can do in this situation without having a lot of manual configuration that would be error prone for us to maintain.

**Comment by vthornheart-bng** [comment]
Ah, interesting - yeah, and there's not much that we can do about that: particularly if they're both items you can actually earn in-game.  I'm going to go ahead and marked this closed for now, there's not much we can do in this situation without having a lot of manual configuration that would be error prone for us to maintain.
