### ISSUE TITLE
GetHistoricalStats using daily periodType generates error

### ISSUE THREAD

**Issue by danreynol** [Bungie-net/api#272]
If I make the call to GetHistoricalStats, with character id of 0, using the daily periodType parameter, I get the following error: An unexpected error has occurred on Bungie's servers while trying to grab Destiny information.

If I make the same call except for a specific character, it works. Is there something special I have to do to pull all characters data for a time range?

Thanks!

**Comment by vthornheart-bng** [comment]
Oh, so in this situation you'll want to call GetHistoricalStatsForAccount rather than merely GetHistoricalStats.  GetHistoricalStats only understands how to work with characters: so if you pass 0, it assumes this was the intended character ID which throws a fit because that character ID isn't valid.  But if you call GetHistoricalStatsForAccount, it should return you the data you seek (historical info across characters)!

**Comment by danreynol** [comment]
Thanks! I'll give that a shot.

**Comment by vthornheart-bng** [comment]
No prob!

**Comment by danreynol** [comment]
GetHistoricalStatsForAccount works great to pull back all characters data, but is there an option to specify a time range? I tried the same parameters defined in GetHistoricalStats, alas with no luck. Looks like groups is the only querystring param listed.

**Comment by vthornheart-bng** [comment]
Ohhh - yeah, in that case GetHistoricalStatsForAccount won't help.  Indeed, there aren't such aggregation options on an account-wide basis.  If you need that, you'll have to query for each character separately.

**Comment by danreynol** [comment]
Many thanks. I will go that route. I appreciate the super fast response!
