### ISSUE TITLE
Blizzard Account #number not being saved in PGCR anymore?

### ISSUE THREAD

**Issue by ashleypb** [Bungie-net/api#281]
Noticed when viewing post game reports only the users 'displayName' without `#0000` is now being saved.  Makes it harder to find players within the specific activity...

                            [score] => Array
                            [player] => Array

                                    [destinyUserInfo] => Array

                                            [iconPath] => /common/destiny2_content/icons/dbc42b541333a49226e2cb50746773c2.jpg
                                            [membershipType] => 4
                                            [membershipId] => 4611686018470676529
                                            [displayName] => Snickers

                                    [characterClass] => Titan
                                    [characterLevel] => 20
                                    [lightLevel] => 276

                            [characterId] => 2305843009301595733`

I know you could get the `#0000` again by re-querying the `membershipId` and `characterId` but thats just extra work, extra calls to the API, more requests, more load.

Maybe its a bug that can be fixed or maybe its intentional ??

**Comment by floatingatoll** [comment]
Feature idea: 'membershipName' => 'Snickers#0000' could work well as a new
property for that. It'd have the same value as displayName for Xbox and PSN
users, which is fine.

**Comment by bladefist** [comment]
Ya, the #0000 needs to be on there as w/o it, the names are not unique.

**Comment by Tetron-bng** [comment]
This is intentional.  The string we return is the Display Name, not a unique name.  The general rule is we don't want to display the #0000 part of the name since it is clutter and not usually necessary in the context of a single name.  The guidance from Blizzard was to only show the full battle tag to the owner of that Battle tag, or as a secondary display (like on hover) to facilitate friend requests etc.  We return the membership ID so you can uniquely identify the player without depending on the gamertag/battletag/PSN ID which can change over time and are therefore not reliable.
