### ISSUE TITLE
When do we get Scope for GroupV2?

### ISSUE THREAD

**Issue by kenwolter** [Bungie-net/api#295]
I'm trying to work with the GroupV2 area but I'm running into a lot of issues with Access Denied, not the right scope.  I read that you reject any attempts to add scope to the Auth process so I was wondering when can we expect to see these missing scope values in the [application page](https://www.bungie.net/en/Application)?

All the scope values that are available are posted [here](https://bungie-net.github.io/multi/schema_Applications-ApplicationScopes.html#schema_Applications-ApplicationScopes)

**Comment by Tetron-bng** [comment]
Hey!  Glad you are trying new things.  We didn't make every scope available right away because we were not really sure we had picked the right set of possible scopes.  Once we put them out there, there was no taking them back, so I be sure the scopes are well suited to type of things developers want to build.  Can you give me an idea of the scenarios or APIs you would like to enable?  I can either make the right scopes available, or at least use that as input to fine tuning our scopes.

**Comment by kenwolter** [comment]
No hurry needed on this.  I'm trying to write a .Net wrapper over your API that merges the API response with the world DB data to make an interface that is a little easier to use without having to know all the details about the API to write a program.  So I really need it all eventually.  I was curious about the timelines you are working with.  I'm also a developer so I understand the complexity of putting out a solid API.

**Comment by Tetron-bng** [comment]
New GroupAdmin scope coming at the end of Jan.
