### ISSUE TITLE
Missing enum "DestinyComponentType" in API documentation

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#3]
Referenced in any endpoint with querystring parameters such as [Destiny2.GetProfile](https://bungie-net.github.io/multi/operation_get_Destiny2-GetProfile.html#operation_get_Destiny2-GetProfile)

> components
A comma separated list of components to return (as strings or numeric values). See the **DestinyComponentType enum** for valid components to request. You must request at least one component to receive results.
Type: string

This was brought up already, but I'm adding it to github so it doesn't get lost

**Comment by vthornheart-bng** [comment]
Ah, yes good find!  I'm going to go hunting if not tomorrow then this weekend, to see why my generator is missing certain entities.  I'll try to get this cleared up!

**Comment by vthornheart-bng** [comment]
I found the issue - our metadata about querystring properties usually treats the metadata for comma delimited strings of strongly typed enum values as that strongly typed value, instead of just as a string.  I've fixed the metadata, and now this enum will be picked up properly.

Next deployment of docs will have it!  Thanks for reporting this!
