### ISSUE TITLE
Faction rally winner information is duplicated

### ISSUE THREAD

**Issue by kbreit** [Bungie-net/api#300]
I noticed on the Milestones endpoint that 364880304 and 3591754413 appear to be duplicate of each other. What is the difference between the two and which can I assume is the main one to watch in the future?

**Comment by vthornheart-bng** [comment]
Ah, yes!  The differences are very subtle: so 364880304 is the "WinAnnouncement" Milestone: it's the milestone that everyone gets when a winner is declared, whether your faction won or not, so that you know who won, which faction won etc...

The other one is 3591754413, that is the milestone that you get if the faction *you* pledged to won.  Unfortunately, for any meaningful content at the moment they are basically identical.  They point to slightly different "quest" items, but the localized text indicating what happened and what to do appears to be mostly the same... which admittedly isn't very useful if you're trying to display this information.  They both exist in game, but unfortunately having both isn't very useful externally... I may end up removing one as a result: I need to think about the potential future implications of that, and investigate whether there are any differences between the two that are worth keeping them both around in API data.  For now, assume both will exist: and I'd suggest using 364880304 as the go-to Milestone for displaying who won the Faction Rally.

**Comment by kbreit** [comment]
How does 3591754413 detect your character pledges when the endpoint doesn't require any CharacterID information passed to it?

**Comment by vthornheart-bng** [comment]
Ah, you're calling the Public Milestone endpoint?

Indeed, the intent of 3591754413 was that it should come down only with your personal milestone data - Milestones on the CharacterProgressions component of GetProfile/GetCharacter requests.  Yeah, I just made the call now and I see it's coming down with the Public endpoint.  That is not intended behavior, I'll add a bug and investigate that.  Thanks for bringing this to my attention!
