### ISSUE TITLE
Graph QL wrapper for API?

### ISSUE THREAD

**Issue by AlexeyDemedetskiy** [Bungie-net/api#302]
Hi! I want to help/build a Graph QL wrapper for an API. How do you look at this idea? Will it align with general project direction?

**Comment by vthornheart-bng** [comment]
I've got no problem with anyone making whatever wrapper they would like - go for it!

**Comment by floatingatoll** [comment]
Note that you'll want to take care around request amplification - that is,
if one request in GraphQL requires more than one request of the API.

On Mon, Nov 20, 2017 at 2:28 PM, Vendal Thornheart <notifications@github.com

**Comment by vthornheart-bng** [comment]
Yeah, for sure - our throttling is pretty generous, but if you go overboard with requests you may find that the wrapper becomes less useful than you might desire.

**Comment by AlexeyDemedetskiy** [comment]
To avoid performance problems with bulk requests, GraphQL resolver will need to be moved closer to the database. However, this is too far away in spacetime. I will try to build the GraphQL schema that will reflect current API in my spare time.

**Comment by vthornheart-bng** [comment]
Closer to the database as in you're considering pushing user information into your own database?  Go for it if that's what you want to do!  Just know that, because particularly the character/profile information is very mutable, the information won't likely be relevant for long.  More static information, like the Manifest Database data or historical stats would definitely be good contenders!

**Comment by vthornheart-bng** [comment]
I'm going to close this for now as I think the question is answered - go for it man!  Just beware of the potential pitfalls mentioned above.
