### ISSUE TITLE
Is it possible to retrieve the values from the "You are worthy" emblem?

### ISSUE THREAD

**Issue by v-fedorov** [Bungie-net/api#305]
Looking for possible workarounds for setting up flawless counts in D2 since the D1 workaround i had is now invalid.

**Comment by vthornheart-bng** [comment]
Yes, we'd like to return all of these for any item that has special counters on it!  I just need a little spare time to get it exposed, it's been something I've been wanting to do but not taken the time to yet - but I'll see if I can cram in this time shortly, because several people have now requested this for various items... and I believe they're all implemented the same way, so if we can get that built in it should satisfy everyone's needs!  I'll see what can be done.

**Comment by vthornheart-bng** [comment]
Ah, forgot to mark this as closed - this is on the objectives component, under the "flavorObjective" property!
