### ISSUE TITLE
Allow HTTP protocol for Redirect URL

### ISSUE THREAD

**Issue by xarxer** [Bungie-net/api#311]
Consider allowing HTTP protocol for Redirect URL, at least for localhost.
Currently I'm writing a library with Qt to communicate with the API, and the way OAuth is currently implemented in Qt is in such a way that it always assumes the Redirect URL to be "localhost:port".

Perhaps I'm wrong, but I don't think it is a big issue to have HTTP at least for localhost?

**Comment by bterrier** [comment]
In Qt you can implement your own ReplyHandler for https, but then the browser will complain about invalid certificate.
Google offers support for `urn:ietf:wg:oauth:2.0:oob` as redirect url, but Bungie does not seem to support that either.

But the easier would be indeed to support http for localhost. Also it would be nice to allow every port for localhost, because the port can be chosen dynamically when the application start on the user device.

**Comment by Tetron-bng** [comment]
Glad you found a work around.

**Comment by bterrier** [comment]
@Tetron-bng It is NOT a proper work around. 

Without HTTP allowed, either we have to use in app webview or leave the user with a blank browser tab. This is no acceptable.

Please either allow HTTP for localhost or provide a nice page for the user after login.

**Comment by xarxer** [comment]
I agree. It is not a workaround; it's more of a hack to circumvent the restrictions.
Bungie says HTTP is not allowed, so we just set "localhost:xyz" as redirect URI, and then manually add the HTTP part during authentication. So the "restriction" is not working for localhost anyway.

**Comment by Hmaal** [comment]
This is also a problem for me. Attempting to use Flutter and its workaround after workaround to get past the OAuth2 side of things as well as well as the HTTP vs HTTPS issue.

**Comment by nine13tech** [comment]
I and my dev groups use this every day for local ssl.
https://medium.freecodecamp.org/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec
I hope it works for you.

**Comment by Hmaal** [comment]
Thanks nine13tech, but I would need something that works for setting it up on the device dynamically in Dart.
