### ISSUE TITLE
Need Help To Count Trials of 9 or raids victory

### ISSUE THREAD

**Issue by predalpha** [Bungie-net/api#312]
Hello,

Im currently developping a website for my clan but im stucked.
Is it possible to get victories number count of Trials of nine or Raids.
What i mean is how many times a member of a clan finished the 7 victories of TOT9 or how many times he completed the Calus Raid.

I dont succeed finding those informations by myself.

Moreover thanks for those awesome API !
https://wwwfrenchguardsfr.000webhostapp.com/

**Comment by vthornheart-bng** [comment]
Ah, victories in Trials of the Nine as in number of rounds/matches won?  Or as in the number of times they got "perfect" runs?

The best spot to start looking is the GetActivityHistory endpoint:

https://bungie-net.github.io/multi/operation_get_Destiny2-GetActivityHistory.html#operation_get_Destiny2-GetActivityHistory

There's a lot to it, so give it a look and see whether it'll fit your needs.  When you're looking for Raid wins, for example, you'll want to find matches via GetActivityHistory where the "referenceId" matches one of the Raid Activity Hashes (if I had it to do over again, I'd have named referenceId "activityHash" to make this association more obvious), and then check the "Completion Reason" to see if they won!

Trials of the Nine is a bit more difficult at the moment, unfortunately.  I'm not sure exactly what - for example, trials.report is doing to try and mine out that information, but currently we don't have anything that actually directly tells you whether they got a "perfect" run... but you can use a similar technique to the above to determine whether they won a given match.  It's a bit more difficult for PVP though, because they're all in "playlists" - you'll want to check in this case that the activity's "modes" property contains DestinyActivityModeType.TrialsOfTheNine (value 39), that's the easiest way to see if it was a Trials match.

Hope this gives a decent kick-start!  I wish you luck in your efforts!

**Comment by predalpha** [comment]
Thank you so much for your very detailed answer. Ill try to move forward on our website with your tips and share !
I really appreciate !

**Comment by vthornheart-bng** [comment]
No problem, glad to help!  We'll be here if you have API questions!

**Comment by vthornheart-bng** [comment]
(I'll close this for now since the gist of the original question is answered - if you have more questions, feel free to make new Issues.  We may someday move Q&A-style asks somewhere else, but for now this is the best spot)

**Comment by floatingatoll** [comment]
See also #369.
