### ISSUE TITLE
Mayhem - team not returned

### ISSUE THREAD

**Issue by mattybeard** [Bungie-net/api#351]
In the new game mode, the team is not returned. The team score is returned so I can use that to guess but it's not ideal (in the PGCR)

**Comment by vthornheart-bng** [comment]
Indeed, this is related to #348, and will be fixed once we repair the broken association between Mayhem games and their intended Activity Mode (right now they're coming across just as "All", which means it loses all of the data that we use to determine - for example - if it's a PVP match, or whether we should return a team score, etc)

I'll close this one since I'm tracking it under #348!
