### ISSUE TITLE
[Question] How to detect the activity type / name

### ISSUE THREAD

**Issue by joshlopes** [Bungie-net/api#371]
http://raid.reports seems to be able from a few calls:

- https://www.bungie.net/Platform/Destiny2/2/Account/4611686018454285894/Character/2305843009283368187/Stats/AggregateActivityStats/
- /Platform/Destiny2/2/Account/4611686018454285894/Character/2305843009290214604/Stats/Activities/?page=0&mode=raid&count=25
- /Platform/Destiny2/2/Profile/4611686018454285894/?components=Profiles%2CCharacters 

to find the completions for each raid type individually. I have tried myself but without any luck and i can't find anything that would help me.

Can you please give me some tips where i can find the key , string, enum that would help me distinct the types ? I don't need this much information, all i want is from the bungie api to grab the total completions for a player (cross all characters) for each type of raid, EoW and Leviathan.

Thank you, great job!

**Comment by xlxCLUxlx** [comment]
Hi @joshlopes,

You are on the right track!

Since you will want to get total completions it sounds like at the profile level you will need to grab all characters using the [Destiny2.GetProfile](https://bungie-net.github.io/multi/operation_get_Destiny2-GetProfile.html#operation_get_Destiny2-GetProfile) endpoint.  An example with the data you supplied in your post the constructed endpoint would be (i.e. your third bullet item in your post):

`/Destiny2/2/Profile/4611686018454285894/?components=201`

You would now iterate through each character and call the [Destiny2.GetActivityHistory](https://bungie-net.github.io/multi/operation_get_Destiny2-GetActivityHistory.html#operation_get_Destiny2-GetActivityHistory) as shown in your second bullet item and immediately below.

`/Platform/Destiny2/2/Account/4611686018454285894/Character/2305843009290214604/Stats/Activities/?page=0&mode=raid&count=25`

This will give you raid activities that the player has engaged in for a particular character.  

Based on the data that is returned you would need to look at the `directorActivityHash` and look up the value in the `DestinyActivityDefinition` to determine if the raid is Eater of Worlds or Leviathan.  Alternatively, if you do not want to use the `DestinyActivityDefinition` table from the manifest you could use the [Destiny2.GetDestinyEntityDefinition](https://bungie-net.github.io/multi/operation_get_Destiny2-GetDestinyEntityDefinition.html#operation_get_Destiny2-GetDestinyEntityDefinition) endpoint to look this up as well.  In addition in order to determine if the character successfully completed the activity you need to look at the `completionReason` where the value is equal to 0.  Any value not equal to 0 is not a completion.

Sample JSON of completed raid:

```json
"completionReason": {
    "statId": "completionReason",
    "basic": {
      "value": 0,
      "displayValue": "Objective Completed"
    }
  }
```

I hope this helps you out!

Regards,
@xlxCLUxlx

**Comment by joshlopes** [comment]
Thank you will give this a try and re-open if new doubts surges.
