### ISSUE TITLE
Include Mayhem in AllPvP mode

### ISSUE THREAD

**Issue by vtubelsky** [Bungie-net/api#397]
Follow up to https://github.com/Bungie-net/api/issues/348

GetActivityHistory with mode=25 does return Mayhem games, but they still seem to be excluded from AllPvP (mode=5).

**Comment by vthornheart-bng** [comment]
Hmm, last time I remember there being a controversy about this.  IIRC, in D1 there was a controversy about whether Mayhem should be part of AllPVP stats because its playstyle was so skewed from normal modes of PVP play.

I'd be interested to hear input from you all on it, as you all will ultimately be the ones to use this data.  Do you want Mayhem to be part of the AllPVP pivot?  We can add it in if the majority desire it.  Let's consider this a public request for comment.

**Comment by floatingatoll** [comment]
All Crucible is PVP, so by a strict definition it has to be present.

Is Crimson Doubles considered "competitive PVP" or "quickplay PVP"?
(Competitive, presumably.) How about Iron Banner? (Quickplay, presumably.)

I think Mayhem needs a third category, "mayhem PVP", under which all of the
various Mayhem types over time get placed into. (One today, but knowing
Bungie, there's more!)

My reasoning is simple: Competitive and Quickplay are differentiated by
play style, and Mayhem is as well. The massive regen and ammo rates of
Mayhem lead to gameplay styles that resemble neither Competitive approachs
nor Quickplay approaches, and should not be included in them.

So if you're in the mood to do a lot of work, I encourage:

AllPVP (all crucible)

And then also provide three additional pivots:

AllCompetitivePVP
AllQuickplayPVP
AllMayhemPVP

On Thu, Feb 8, 2018 at 11:59 AM, Vendal Thornheart <notifications@github.com

**Comment by vthornheart-bng** [comment]
My memory may be fuzzy, but I think I recall people being upset in D1 about mayhem being in PVP data because mayhem results in skewed kill etc... stats.  I could be remembering incorrectly though, it was a while ago: that's the only reason I can think of for not putting it in PVP, and if people don't care about that I'm fine to put it in there!

**Comment by vtubelsky** [comment]
I think Mayhem games should definitely be included in AllPvP results.

It's a different question wether Mayhem should affect player's lifetime stats like killsDeathsRatio and killsDeathsAssists but it's completely unrelated to the list of activities.

**Comment by vthornheart-bng** [comment]
Ah - you know what, now that you mention it I think that was the prior controversy.  It's been a while, I apologize for my rusty memory!  Yeah, unless anyone has a strong objection remaining I'll go ahead and add it in.

**Comment by vthornheart-bng** [comment]
Added as TFS 608544.

**Comment by vtubelsky** [comment]
Thank you, sir.

**Comment by mistahj67** [comment]
Just my two cents here: From what I've seen so far the emblem that features your KAD (Kills + Assists / Deaths) already includes the mayhem stats (At least it was during the Dawning event, I haven't checked since hotfixes).

While I agree that it is technically API part of allPvP, that will result in all the stats rolled into overall PvP values which I'm not sure how I feel about. On the one hand it is pvp and thats the total kill count, on the other hand from a snapshot view of stats, it significantly skews the rest of the data due to the nature of the mode itself. I'm new to this space, but I lean keeping it separated and letting those using the data decide to lump it together. If you include it in overall allPvP stats, many players who rely on third party sites to display their "skill", however they define it or show off their emblems, will stay away from the game mode completely.

**Comment by joshhunt** [comment]
Just to chime in here (while acknowledging I neither consume these stat APIs nor really use the sites) -  although Mayhem will drastically skew the stats in one way, at least that will be consistent across the entire player base.

If sites which to provide more insight into _where_ those kills come from (explain Mayhem kills) they can supplement AllPvP stats with additional info, like % of Mayhem matches for example.

**Comment by bladefist** [comment]
I really don't like the idea of Mayhem being statistically grouped with the other data, but I feel I am in the minority on that.  A lot of the Destiny Tracker users have contracted us and asked for it to count.  

So for that reason, I think it should be in allPvP, as well as have it's own [type](https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType.html#schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType)

@vthornheart-bng Is there anyway we can get a Mayhem mode? This is actually probably my biggest request in terms of Mayhem.  It would allow me to remove it or re-categorize those stats.  Thanks

**Comment by vtubelsky** [comment]
@bladefist You can use mode=25 right now to get Mayhem games. I think Vendal mentioned that it will be added to the DestinyActivityModeType doc sometime soon.

**Comment by rourkem** [comment]
Mayhem is meant to be a fun thing where you spam abilities and heavy and it’s all a big mess.

I think that should be excluded from general stats like KD. If it isn’t, people who care about their stats will avoid Mayhem because they don’t want their hard-earned kd to suffer.

I think everyone should be able to drop into Mayhem and just have fun and not care.

**Comment by vthornheart-bng** [comment]
Oh yeah, the mode is available - I've got a separate bug to rename the enum, but enum value 25 is the mayhem mode value!

**Comment by vthornheart-bng** [comment]
Oh, that's what I get for catching up by reading my mail in oldest-to-newest order instead of reading the whole thread.  Sounds like things are set.

I'll check about whether Mayhem is included in aggregate stats, that is indeed a good question and I unfortunately don't know the answer to that offhand!

**Comment by vthornheart-bng** [comment]
Also, I should note that we (the API folks) have way less control over the actual aggregation of stats than we do about what gets returned in GetActivityHistory.  It is possible that we won't be able to change the way this aggregation works if Mayhem is rolling up into PVP... but I will let you all know.  Just to forewarn though, it might not be possible for us to alter the aggregate stats at this point.

**Comment by paname75** [comment]
I think it should be in because as stated in https://github.com/Bungie-net/api/issues/384 , this create a disconnect between the API KDA and the emblem KDA.

**Comment by vthornheart-bng** [comment]
Definitely a good point.
