### ISSUE TITLE
Can't pull some items from Postmaster

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#406]
We're respecting the `doesPostmasterPullHaveSideEffects` flag, but it's true in cases we don't expect, such as normal weapons: https://github.com/DestinyItemManager/DIM/issues/2623

**Comment by floatingatoll** [comment]
I’ve also seen one report of this on a mid-200s blue rocket launcher, and IIRC nothing happened when they removed it from postmaster.

**Comment by vthornheart-bng** [comment]
Aye, indeed you've run into a known limitation of postmaster transfers: some weapons can conditionally alter your state when transferred from the postmaster - for instance, in this situation, picking up the item you linked to through that DIM bug is setting a value on the server that lets us know this was the first time the user picked up a "superior quality" weapon if they haven't picked one up before - but on the BNet side, we don't have an understanding of what these side effects can do and the ripple effects they can have.

For instance, even in this seemingly benign example, what happens if that flag gets set for the first time and you're not playing?  Is there important tutorial UI that a user might miss out on?  This is why our "doesPostmasterPullHaveSideEffects" is so aggressive, and will indeed sometimes hit false positives.  We are erring on the side of caution, because we have no way of knowing a priori what side effects some of these actions can have.

I think it will likely be prudent to create a "whitelist" of safe actions: for instance, if the designers feel like this one is safe enough to exclude, then we could add it to a list of potential actions that we're okay with being run as a side effect.  But we'll have to be careful, as this whitelist will come with both an ongoing maintenance cost and the possibility that it could have undesired side effects in the future that we'd then not be protecting against.  So if we do create a whitelist, it will be in extremely rare cases and only if we feel pretty certain of its harmlessness.

I'll ask around about this one, and then if they feel comfortable about it I'll see about adding a whitelist exemption for this specific side effect.  But I can't promise that we will be able to provide it, and you'll definitely want both your users and your fellow DIM developers to know that Postmaster Transfer is aggressively conservative and that sometimes you won't be allowed to transfer an item that otherwise seems benign.

**Comment by ckhicks** [comment]
This is amazing info on both this feature and how the back-end 
validation systems work - so cool to see more of those moving pieces

**Comment by vthornheart-bng** [comment]
I'll close this for now.  Just made a wiki page that includes this info for postmaster actions... I'd like to do some cleanup of the wiki and organize it a bit better, but at least it'll be there for now.
