### ISSUE TITLE
How to access "previous season" vendor item tiles?

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#416]
There are a few items for "sale" by vendors that are some sort of dummy (like inventory item hash 4195309789, "World Gear (Previous Seasons)". They have a wide tile-like icon. "Bright Engram" has a bunch under "Vanity Items Preview". I assume that there should be other vendors behind those tiles, but I don't see any vendor definitions that look like that, nor is there any hash I could use to find them.

**Comment by vthornheart-bng** [comment]
Hmm, I'll have to look into it.  They are almost certainly "Preview vendors," which are basically vendors being used for the purpose of providing a preview of categorized items somewhere in the UI - or that *were* going to be used for that purpose, but got cut.  I'd put cash down that this is one of those Vendors, and if you're not seeing it in game it's probably because it wasn't quite ready for prime time and got cut (and we missed it in redactions!).
