### ISSUE TITLE
Forum API:  GetTopicsPaged date filter "All Time" and "Year" giving same results

### ISSUE THREAD

**Issue by GrayWulf25** [Bungie-net/api#427]
I am retrieving Forum topics marked as Answered Question in Help category.  "GetTopicsPaged" with Date Filter of "All Time" or "Year", is giving same total topics number. I iterate through pages starting from zero and stop at the first page with zero results. End-points:

All-time: /GetTopicsPaged/{pageNum}/0/0/3/0/4/?tg=Help&lang=en
Year:       /GetTopicsPaged/{pageNum}/0/0/3/1/4/?tg=Help&lang=en

So by my thinking, either "All Time" date filter of 0 does not work, or forum posts outside this year are archived and not retrievable through the API. 

Please advise, as I am keen to get "All Time" answered questions going back as far as possible. If I cannot get that I will have to change tack on my project.

**Comment by vthornheart-bng** [comment]
Ah, yes - so what you're running into is the unfortunate side effect of optimizations we had to make in order to keep the Forums system performant given our current design, technical, and server constraints.

We no longer return data from GetTopics endpoints for topics that have not had activity for longer than 6 months, which is why now AllTime and Year are basically going to be identical.  There was a time where we'd return activities throughout all time, but the constraints above proved to be too severe for us to allow that data to be returned freely.

Sorry, wish I had better news for you!  It's likely going to be this way for the foreseeable future, which means that your goal of getting all time answered questions is unfortunately not something we can provide a direct route for you to get at this time.

**Comment by vthornheart-bng** [comment]
Just out of curiosity, what were you thinking of doing with the data?  Just out of my own curiosity!

**Comment by GrayWulf25** [comment]
Thanks for confirming, I suspected that was the case. It’s an MSc Computing project in UK. Destiny is my specialist subject! I am going to apply Machine Learning algorithms to text from Destiny Forum posts. 

Initially I was going to  measure Toxicity, LOL but I changed my mind and decided to focus on the positive and try to teach a Machine Learning model to recognise a question similar to an already answered one. If that worked I was going to then teach it to rate the possible answers to non-answered questions by using answered questions as training data etc.

So it looks like I will only have approx.. 500 Answered Question threads, and maybe 250 unanswered Questions. I will try it based on that but IDK if that is enough data to successfully train the model. If not I will go back down the sentiment analysis for toxicity route

Thanks for your help so far!

Sent from Mail for Windows 10

**Comment by vthornheart-bng** [comment]
Cool - yeah, I hope that data is sufficient!  Let us know how it turns out!  I'll close this for now, but feel free to reopen it or update as desired!

**Comment by GrayWulf25** [comment]
Hi Vendal,

In the spirit of “at least I asked”, is there any possibility of getting the real “All Time” Answered Question topics from the Help Forum created as a one-off text dump, in JSON format, exactly as it would be from “/GetTopicsPaged/{pageNum}/0/0/3/0/4/?tg=Help&lang=en” (if that still worked)? If it could then be uploaded to Google Drive (or similar) I could retrieve it

I know it is a big ask for scare resources, but I just need to know if there is any possibility, before I change the direction of the project

Kind Regards
Mark

Sent from Mail for Windows 10

**Comment by vthornheart-bng** [comment]
In general, it probably wouldn't be good for us to agree to one-off dumps of data because it sets a precedent that other people subsequently looking for data dumps would be able to point to and (rightfully) state it was unfair that one person got the data and not another.

I do think that academic use cases are potentially an interesting exception: though if we got flooded with requests, or the requests took too long to fulfill, it would impede our own work that we have to do: and we're pretty crowded for time as it is.

In the case of All time Forum data, unfortunately we're not well set up to do get at that data without a lot of effort that I don't think we have time to aggregate.  I apologize - it's a bummer, and if it wasn't going to take a lot of time to do I'd consider making an exception in this academic case... but in this situation I don't think we can make it happen.  Sorry about that!

**Comment by GrayWulf25** [comment]
No problem, I completely understand, but I had to ask

**Comment by vthornheart-bng** [comment]
Totally!  I wish we were in a position to make it happen! :(

**Comment by GrayWulf25** [comment]
One last question on this (promise): Are the underlying posts < 6 months active still there and accessible through GetPostsThreaded or GetPostAndParent requests (if I had the PostId)?

If they are, then theoretically I could create a one-off back-fill to iterate backwards from last Answered Q PostId,, and for OP's satisfying Answered Question criteria get it and it's answer without having to use GetTopicsPaged. I'm crossing my fingers anyway...

**Comment by vthornheart-bng** [comment]
Ah, yes!  Indeed if you don't mind the length of time it'd take to do that, they are still there: just not accessible via querying, only via direct access.  Luckily, post IDs are indeed linear: so you could traverse the entire set (or find a "sufficiently old" post ID as a starting point) and do that!  Good call!
