### ISSUE TITLE
Clarification for inventory from getProfile endpoint

### ISSUE THREAD

**Issue by ArkahnX** [Bungie-net/api#44]
If I want to get a guardians inventory, in destiny 1 you called the inventory endpoint on a characterId.

For destiny 2, it looks like it's possible to make a getProfile request with CharacterEquipment, CharacterInventories components to get all character inventories in one go?

Now, do I need to have both CharacterInventories and CharacterEquipment to get the full picture? Or will CharacterInventories also have the equipped items.

**Comment by vthornheart-bng** [comment]
Indeed!  You will want to call for both components if you care about both their equipped and non-equipped items.

We had both a functional reason and a privacy reason to split them up - functionally, it allows someone to just get one or the other if they have an app focused on, say, only your equipped items (without our data being redundant and having it in both places).  

Privacy-wise, it allowed us to build up a pattern of having privacy settings be on the component level.  We ran into a lot of bugs, caching issues etc... in Destiny 1 with our "sometimes there, sometimes not" policy for extracting items you're not allowed to see due to privacy.  This way, the privacy is only gated at the component: you'll either get the component and everything inside, or you won't and will have to handle it in your app!  It helps keep a cleaner separation of privacy gating on our side... and we're hoping it'll help prevent you guys from having to do a lot of one-off checks and special exception handling.  We'll see in practice if it actually helps.  It has helped our mobile devs so far, but I get the feeling that we'll see this API used in many ways that we aren't envisioning at the moment.

But yeah, TL;DR: don't hesitate to ask for all the components!

Also, you can hit GetCharacter if you know you only need a specific character refreshed and you're worried about bandwidth issues of refreshing all of them at once.  It's up to you how much you want to worry about those kinds of concerns.
