### ISSUE TITLE
Glitch, go out of the world on nessus.

### ISSUE THREAD

**Issue by UTAaronSr** [Bungie-net/api#445]
By the well of dust there is a crack that you can slide through and go out of the world. Can you please fix it because it is annoying. It is on the top by the hill on the right side looking at the front. You can see trees thought it.

**Comment by rking788** [comment]
This isn't really an API issue, I wonder if there is a spot on the Bungie forums for this type of feedback.

**Comment by floatingatoll** [comment]
There is:

https://www.bungie.net/en/Forums/Topics?pNumber=0&tg=Help&tSort=3&tType=0&d=0&lang=en

You can open a new post on this forum requesting support for the two issues filed today. Note that their mobile theme is broken here, so you may not able to operate the form from your phone - I’ll let them know so that it hopefully gets fixed soon, but in the meantime, that URL should also work from a desktop computer if you have one.

**Comment by Tetron-bng** [comment]
Please share game related issues on the Bungie.net feedback forums.
