### ISSUE TITLE
[Question] PassportJS and passport-oauth2

### ISSUE THREAD

**Issue by RobertCGouge** [Bungie-net/api#45]
I apologize if this is not the place to ask this question.  Has anybody gotten passport-oauth2 to work inside of an Express app to authenticate against Bungie's oAuth workflow?  I get all the way to callbackURL and Passport throws an error that it cannot parse the response.

**Comment by vthornheart-bng** [comment]
Hmm, unfortunately I've never used PassportJS, so I may be of limited help here.  But if you have an example of the response you're getting that it's having trouble parsing, and the request you sent that generated that response, that might help reveal the underlying issue!  (Just XXX out any private information that may be in the request/response when you post it here!)

**Comment by ckhicks** [comment]
I've been messing with Auth0 for this as well - things are looking good there but I haven't tried PassportJS yet.

**Comment by RobertCGouge** [comment]
I've tried to log the request and the response, but I think that is slightly beyond my current level of technical knowledge.  I am going to try to just write my own little function to see if I can get anything back from the TokenURL.

**Comment by vthornheart-bng** [comment]
Hmm, it sounds like some other people are looking for NodeJS oauth libraries that work - did either of you guys get things working?  If so, what did the problem turn out to be?  If not, perhaps we can help diagnose (with the understanding that I've never used NodeJS or any of these libraries, so I'll only be able to help if there's an issue such as pointing to the wrong URL and what-not)

**Comment by ckhicks** [comment]
I’m at the refresh token step over on #71 using Auth0’s JS OAuth extension. If I get that working I will definitely provide a writeup since it’s such a plug-and-play solution for a variety of platforms! I’m a PassportJS fan as well, so I’ve been keeping an eye on this one to see if we can figure something out from either approach.

**Comment by RobertCGouge** [comment]
Sadly, I think my lack of Javascript knowledge is going to cause me to bow out of trying to help get Passport JS working.  I am unsure of how to go about capturing the response that comes back after I initiated the OAuth flow.

**Comment by vthornheart-bng** [comment]
Sweet @ckhicks - yeah, if you guys find any awkwardness/unusual implementation problems with our OAuth that we can work on our side, let us know.

Understandable @RobertCGouge, if you do find a way to capture it definitely update here and we'll try to help.

**Comment by ckhicks** [comment]
After messing with Auth0 quite a bit, I finally got an authorization token to return to my browser-based app. Requesting a refresh token after that should be cake, but I think there's a need for more JS solutions for interacting with the API due to CORS issues (historically solved with something like [this](https://github.com/waltfy/destiny/blob/develop/proxy.js)) and a few other hiccups.

Since solutions like Passport JS require knowledge of server-side JS, and tools like Auth0 only allow 7,000 users in their free tier, I'm considering filling the hole with a simple service others can use to jump straight in and start building.

Ideally, one could save their creds in a safe area, embed a script, and hit authorized endpoints that don't require the robust communication involved in the OAuth flow. Getting more browser apps and Chrome Extensions out there would be amazing if they had full OAuth permissions without the setup time!

**Comment by Tetron-bng** [comment]
Hopefully this question has been answered. Please reopen if there is more to know.
