### ISSUE TITLE
Warmind Rankings

### ISSUE THREAD

**Issue by bladefist** [Bungie-net/api#461]
Will the API have at launch any information about the new ranking and progression systems coming w/ the Warmind update? 

Thanks!

**Comment by vthornheart-bng** [comment]
Ah, yes indeed!  Thank you for mentioning it, I need to get you guys that info!

So, there's two sets of new ranking/progressions that you all will want to be aware of, but fortunately they're using existing systems so it shouldn't require too much alteration on your guys' part:

# PVP Ranking

"Valor": Your non-competitive (Quickplay) PVP ranking.  Implemented merely as a Progression, so you will get this data with Progression component requests.  The hash identifier of the progression will be 3882308435.

"Glory": Your competitive PVP ranking.  Also a progression, hash identifier 2679551909.

Note that, as of DLC 2, Progression "Steps" (the "steps" property in DestinyProgressionDefinition) will have an optional "icon" property.  This was added so that you can show your current rank's icon for Valor and Glory, though theoretically it could be used for any progression now and in the future.  Check whether the icon exists before you attempt to show it of course, as most progressions won't have it.

# Vendor Seasonal Rankings

Some (but not all) vendors will now have a "seasonal rank" that you can increase which will gate access to special items.

DestinyVendorComponent will, as such, now have an optional "seasonalRank" property.  If it is populated, that is the user's current seasonal rank with that vendor.  For now, it appears that this is merely increased in the same manner that you "increase" ranks on Vendors normally - through increasing reputation with them.  This seasonal rank will reset with every game "season" however.

**Comment by bladefist** [comment]
@vthornheart-bng  That's great, glad it will be easy.   Will there be any progression information in a single match? Like the delta or anything?

**Comment by vthornheart-bng** [comment]
Oh, as in on the PGCR?  Unfortunately there won't be, but I think that would have been awesome to include and I wish we'd thought of it before!  I'll bring it up to folks as an idea for a potential future improvement to the PGCR stats.

**Comment by bladefist** [comment]
@vthornheart-bng Awesome.  For 3rd party sites that will be beneficial to see how your rank fared per match.  Big feature there! thanks.

**Comment by vthornheart-bng** [comment]
Ah, so it's a bit janky in the API admittedly - we only return progression data per character presently, so the value is actually the same account-wide but you'll find the values in each individual characterProgression component.

In the future, I'd like to add a "profileProgressions" component, but we don't have that yet: and because moving it from character to account would be a breaking change (in terms of changing where the data is located), if this ever does come to pass I'll try to give you all as much advance notice as possible and perhaps have a transition period where the data is located in both spots but the old location is deprecated.
