### ISSUE TITLE
The new Eververse Engram (Prototype Engram) does not have the appropriate Engram bucketHash

### ISSUE THREAD

**Issue by serkanbal** [Bungie-net/api#471]
Hello,

The new Eververse Engram (Prototype Engram, hash: 3682636565) has the bucketHash: 2422292810 in its manifest definition. This bucketHash has a dummy definition. The other engrams -both Eververse and regular- have bucketHash: 375726501; which has the correct definition.

**Comment by floatingatoll** [comment]
To ask a probably-obvious question: What information are you hoping to find
and use via the API about the Prototype Engram?

**Comment by vthornheart-bng** [comment]
Oh, I bet that's because the engram itself can never actually make it to your inventory: we send items to "dummy" buckets when they're only meant for the spawning of other items as a result of obtaining them.

Now, the other side of that is that it means the player shouldn't have an engram of that type ever in their inventory, so there wouldn't be a need to sort their inventory items taking it into account.  I'd need to take a closer look though - are you seeing these show up in people's inventory?

**Comment by serkanbal** [comment]
Oh I think you are right. Upon closer inspection; I realized that this Prototype Engram is the one that Eververse gives out as a gift only once at the beginning of the season. So you "kinda" have it; but do not actually have it in your inventory. You just redeem it at Eververse.
Thanks for the clarification.

**Comment by vthornheart-bng** [comment]
No problem!
