### ISSUE TITLE
SURVEY: What "Collectibles" info would you want to see?

### ISSUE THREAD

**Issue by vthornheart-bng** [Bungie-net/api#505]
If the API were to return you information about things you can collect in the world (Cayde's treasure maps, Ghost Lore, etc...) what would you want returned?

I'm just curious what kind of things people would find useful, and knowing that might help us prioritize what kind of collectible info we return from the API if we get around to doing that!

**Comment by floatingatoll** [comment]
For completionism purposes, here are all the things I can remember wishing for collectible-style tracking APIs for “I encountered and completed that”:

- scanned ghost scannables
- shot nodes on mars
- completed lost sectors
- opened region chests
- opened cayde chests
- welcome terminals on mars

And a weird one, thanks to lowlines :)

- beaten flashpoint mini-bosses

**Comment by vthornheart-bng** [comment]
Ah, cool!  Good lists, thank you!

**Comment by ArkahnX** [comment]
Having binary completion values for lost sectors, ghost scannables (including the Mars info terminals), region chests, Mars data caches (shootable), Mars sleeper nodes.

Region chests and lost sectors would have to be per character as they are in game I believe

I think having a value of how many times things have been completed for sleeper nodes, lost sectors, and potentially flashpoint public event bosses. Those are all things that are repeatable and could merit knowing how many times they were accessed. (Ghost scannables would also fit in this category, but I don't think it would benefit to know how many times they were accessed, or rather I cant think of a use case)

**Comment by lowlines** [comment]
The priority should be on collectibles that have rewards attached to them like the Sleeper Nodes and Data Fragments. From what I've seen treasure maps might actually already be in the LocationRelease data however there's no consistency and they lack an itemHash reference to the item you pick up from Cayde. In a month's time, the majority of ppl won't care about collecting Sleeper Nodes or Data Fragments because they'll have gotten them all or gotten bored, but future collectibles that follow that same pattern should be top priority with all other things put on a wishlist to do when feasible.

**Comment by vthornheart-bng** [comment]
Some of these we'll be able to provide, some we won't - and some we will with enough time and effort!  I'll keep you all posted once I get more info.

**Comment by vthornheart-bng** [comment]
Ah, see #482 for further updates - these two problems are tied closely to each other, so I'll continue to give updates there and close this one for now.
