### ISSUE TITLE
Incorrect model for UserInfoCard

### ISSUE THREAD

**Issue by inferiormartin** [Bungie-net/api#549]
When going over the model definition for UserInfoCard it says the property of 'membershipId' will be of type int64 while it returns a string. Either the model is incorrect or the API returns a property of the wrong type. I would propose changing the data type that gets returned to match the spec as the string will always be parsable as an int64, however this may not be possible for backwards compatibility.

**Comment by vthornheart-bng** [comment]
Ah, so this is an interesting eccentricity of the fact that we return the data as JSON and frequently need to use the data in Javascript engines.

We annotate in the documentation that the type is int64, but if we returned it as numeric values and you were to actually deserialize it in Javascript, the number could potentially lose precision.  Javascript will convert the number to a 32-bit float.  To prevent this, we return the values as strings and annotate our definitions so that, when people want to use it as an int64 in a language that supports it, they can parse it appropriately (this is what our own client libraries do - it's a bit annoying, but necessary when these values are being returned and parsed by Javascript).  Otherwise, you can keep it as a string value as long as you're passing it back to the API intact.

**Comment by inferiormartin** [comment]
That makes sense, thanks for explaining. Maybe make a note about this in the documentation for future users though.
