### ISSUE TITLE
Looking for coders

### ISSUE THREAD

**Issue by BaileyMillerSSI** [Bungie-net/api#56]
I have started working my way through some basic code for creating a C# class library for the entire Destiny Api. I didn't know where else to advertise this but I would be glad to have others contribute some code to the project.

https://github.com/BaileyMillerSSI/Destiny2Api

**Comment by vthornheart-bng** [comment]
Greetings!  Hmm... I'd not thought about the Github as being a place for advertisements of this manner.  I definitely would like to facilitate people finding each other... but I also would like the Issues section of the Github to be more about bugs/enhancements/questions for the API itself.  Otherwise, that useful information could get crowded out by information that's not as directly relevant to servicing the API.

I'm going to close this for now, but I will open a separate Issue where we can all discuss where a good place for such requests could live - either on the Github, or linked from the Github.

**Comment by BaileyMillerSSI** [comment]
Thanks I didn't know either.

**Comment by BaileyMillerSSI** [comment]
@vthornheart-bng  A thought would be another repo under the Bungie-Net account that houses looking for projects and popular projects so people can find them easily.

**Comment by floatingatoll** [comment]
I’ve seen other projects succeed by creating a new file in repository, “PROJECTS”, and then anyone can submit a Pull Request to add their project. That way it doesn’t mix up with issues and people can self-list themselves, and it lets you specify a “not official Bungie” header right at the top.

**Comment by vthornheart-bng** [comment]
No worries BaileyMillerSSI!  It's actually really good that you posted that - it's a subject that we'd not really thought about yet (where such requests - which are good and useful - should live).  So what we're going to do now is redirect people over to the Discord.  It'll be a better spot in general for those types of conversations/requests/promotion:  https://discord.gg/WJDSUgj
