### ISSUE TITLE
Feature Request: add season property to all inventory items

### ISSUE THREAD

**Issue by delphiactual** [Bungie-net/api#561]
If each item had a season property searching for certain items would be easier

**Comment by duckmanBR** [comment]
But how would we set this property?  This info is being returned by the API now?
Also, how would we handle seasonal ornaments? The armor would be season 1, but would also return true for other seasons if the it had a completed Season X ornament?

**Comment by floatingatoll** [comment]
I think it would go down like this:

1) the armor is either “no season” or “season 1”, and

2) ornaments are plugged into the item in a specific location in its JSON, and so

3) both the armor item properties and the specific unplugged ornament’s item properties would *each* have a season property, and

4) the ornament plug within the armor item would retain the season property originally held by the unplugged ornament item

**Comment by duckmanBR** [comment]
Deleted my original coment because I thought that @delphiactual issue was posted on DIM github :confounded:  

Just to keep it together, part of my original comment (and that @floatingatoll based his comment on) was how would we handle armors (that are mostly from season 1) with ornaments that are from subsequent seasons.

**Comment by floatingatoll** [comment]
It’s still a terrifically valuable thing to consider, in any case!

**Comment by vthornheart-bng** [comment]
Hmm, an interesting proposal - I'd like to look into it if we get some time, though right now we're still knee deep in Forsaken work.
