### ISSUE TITLE
Exotic Ghosts do not have InventoryItemDefinition.loreHash defined

### ISSUE THREAD

**Issue by lax20attack** [Bungie-net/api#609]
Example:  
"Knight's Peace Shell"
Ghost Item Definition Hash: 2894506171
Lore Hash: 3075308677

Thanks!

**Comment by vthornheart-bng** [comment]
Hmm, thanks for the info!  I'll have to look into that.

**Comment by vthornheart-bng** [comment]
I did a little looking - it looks like you can't see its lore in game either, and I think it's because its related lore isn't actually substantial/interesting.  I think we're going to leave it un-hooked up given that the source lore itself is in that state and the game doesn't show it.  If it ever gets more interesting/useful lore (i.e. different than the item description), the folks working on the game side will hopefully hook it back up to the item!
