### ISSUE TITLE
Infusion costs

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#639]
Correct me if I'm wrong, but it looks like there is nothing in the API today that explains what it will cost to infuse an item (post-Forsaken). It'd be great to have this info so we can show the costs on the DIM infusion tool.

**Comment by vthornheart-bng** [comment]
Yeah, good call - we don't return much for that right now, and it does look like it's become a more involved process!  I'll have to investigate further.

**Comment by floatingatoll** [comment]
At minimum, please consider exposing the _type_ of material necessary to infuse a donor item into a recipient item.

For example, the hand cannon Frabjous Way requires planetary materials from Io in order to infuse other non-Frabjous hand cannons into it.

Specific numerical infusion costs can vary based on what you're infusing, so if you decide to provide this, providing the worst-case scenario cost (items not the same, so glimmer+marks+materials) — or if that's not possible, simply which planet's materials at _all_ — would be invaluable for us all building "play session planners".

**Comment by floatingatoll** [comment]
And if there's some sort of secret item property we haven't found yet that indicates which 'planet' a gun is from, so that we could reconstruct which planetary material from it, that would of course be a terrific workaround.

**Comment by ckhicks** [comment]
THAT would be amazing. Being able to start organizing the data to better visualize which infusions require which components would be so killer.

**Comment by vthornheart-bng** [comment]
I need to look into it before I can make any promises along these lines, but I'll try to loop back to it later this year and do some investigating.
