### ISSUE TITLE
Firefly perk for Ace of Spades has incorrect icon in API

### ISSUE THREAD

**Issue by XenosKB** [Bungie-net/api#660]
Firefly perk for Ace of Spades has a custom perk icon in-game. In API looks like the icon for a 1st column grenade launcher perk.

**Comment by vthornheart-bng** [comment]
Ah, interesting!  I'll have to take a look at it.  Thanks for the heads up!

**Comment by vthornheart-bng** [comment]
TFS 708305

**Comment by vthornheart-bng** [comment]
Okay, so it looks like the underlying bug is that there's some icons in-game that have an extra alpha channel, and by the time it reaches us (the BNet API) that extra channel has become the one used for the icon.  I'm looking to get it changed at the source, but it's going to be a bit before that change comes downstream to the API.  This may be broken for some time as a result, but at least folks are looking into it and we should get an icon fix eventually.  Thanks for reporting it!

**Comment by floatingatoll** [comment]
For whatever it’s worth, I suspect many of us would love to receive the raw image without any processing, alpha channels and bizarroland HDR formats and all, in case you ever choose to publish that :)

**Comment by vthornheart-bng** [comment]
Aye, I see where you're coming from, but I don't think I can do that - I don't know what sort of things might leak if I try to build something up to get the raw assets and then expose them without stripping them properly.  Particularly with some "image" formats, you can hide an awful lot of metadata in them (intentionally or unintentionally) in ways that might be very hard and time consuming to detect and strip... I'd rather get the results of their processing where they've hopefully done as much of that as possible.

**Comment by floatingatoll** [comment]
Fair enough :)

**Comment by XenosKB** [comment]
Looks like you guys fixed it :)

**Comment by vthornheart-bng** [comment]
Phew, good stuff!  I'd told one of the artists about it, and they said they'd fix it: but the lag time between changing an asset and seeing it come down in the data is significantly longer than - say - an API change.  And I didn't know *when* it was going to come through - Glad it made it.
