### ISSUE TITLE
GetHistoricalStatsForAccount returns "DestinyUnexpectedError"

### ISSUE THREAD

**Issue by karandashek** [Bungie-net/api#664]
Hey guys! Not sure does it happen only for me, but when i'm trying to use GetHistoricalStatsForAccount endpoint, i see this response

ErrorCode": 1618,
"ThrottleSeconds": 0,
"ErrorStatus": "DestinyUnexpectedError",
"Message": "An unexpected error has occurred on Bungie's servers while trying to grab Destiny information.",
"MessageData":{}

Example queries:
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018464611636/Stats/
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018431531920/Stats/

Can't understand what happened, because before forsaken release the same queries worked perfectly.
In the same time the same endpoint for different user return correct info, for example
https://www.bungie.net/Platform/Destiny2/2/Account/4611686018432040046/Stats/

Please, can you help or clarify what may be an issue? Thanks!

**Comment by floatingatoll** [comment]
Certain users are impacted by a server-side bug at Bungie, and may not be able to return certain historical data. See also #638, if it is indeed this issue affecting you as well.

**Comment by jesserogers** [comment]
From what I've found, players who have done some new activities (probably Gambit) will return an error when querying their Historical Stats. I tried looking up historical stats for friends who haven't played Forsaken yet and no errors.

**Comment by vthornheart-bng** [comment]
Indeed, #638 is unfortunately the related issue for this.  There will be a fix - one that should also fix people retroactively - but unfortunately it won't be fixed until September 18th.  Check out that Issue for more details!  I apologize for the pain this issue is causing - 9 days from now, it should start working again.

I'll close this one out so we centralize it to the one Github issue.  My apologies for this break!

**Comment by karandashek** [comment]
ok, got it! Thanks for your help! :)
