### ISSUE TITLE
Vendor API returning incorrect failureIndexes array

### ISSUE THREAD

**Issue by serkanbal** [Bungie-net/api#683]
The vendor API `https://www.bungie.net/Platform/Destiny2/{membershipType}/Profile/{membershipId}/Character/{characterId}/Vendors/?components=400,401,402` returns a failureIndexes array for each item a vendor sells. The integer values of the array correspond to a failure reason text in the vendor's definition in the manifest.

However, since the launch of Forsaken the API is returning incorrect failureIndexes for items. For instance; the vendor Failsafe (vendorHash: 1576276905) returns "Requires Level 20" error for characters above this requirement. There are many more cases like this. Can provide more info if need be.

This behavior is observed in both 3rd party apps and the official Destiny Companion.

**Comment by vthornheart-bng** [comment]
Ah, yuck.  I'll have to look into that for sure - thanks for the info!

**Comment by vthornheart-bng** [comment]
TFS 710777

**Comment by vthornheart-bng** [comment]
Found it!  But the fix won't go in until October 2nd unfortunately.

In the meantime, if you want a workaround: the bug is that the index we're returning is accidentally the index into the *sale item definition's* "failureIndexes" property, and not the index into the failureStrings on the Vendor itself.  So if you want a workaround until then, you could use that index into the failureIndexes property on the sale item, and then use *that* as the failureStrings index.  But that's a real pain in the ass... my recommendation would be to hold tight and let your users know I screwed the pooch on that one, and that it'll be fixed on the 2nd.

**Comment by serkanbal** [comment]
Thanks for the fast response! It is not a very critical aspect of the feature; but causing questions by users nonetheless.

**Comment by vthornheart-bng** [comment]
Aye, totally understandable!  Glad you reported it!
