### ISSUE TITLE
Milestones: Weekly Crucible and Nightfall Challenges show "Legendary Gear" as reward instead of "Powerful Gear"

### ISSUE THREAD

**Issue by Lalo-ATX** [Bungie-net/api#685]
I'm reviewing my progress in Destiny Item Manager and I can see that my level 50 Warlock is showing available:

- Weekly Crucible Challenge
  - Legendary Gear
- Weekly Strike Challenge
  - Powerful Gear
- Weekly Nightfall Challenge
  - Legendary Gear
- Weekly Score Challenge
  - Powerful Gear
- Heroic Story Mission
  - Powerful Gear

Without booting up Destiny, I believe that the Weekly Crucible and Nightfall challenge reward information is incorrect, and should be Powerful Gear, like the rest of the weekly challenges.

Without digging through source code or debugs, my guess is that DIM is faithfully passing through the info from Bungie-net. Thus, I would guess that the API is returning incorrect reward information for those activities.

**Comment by moeyjar** [comment]
Same issue here.  I'm also seeing items such as Clan Rewards as rewarding Luminous Engram.  They should all be 'Powerful' at this point I believe.

**Comment by vthornheart-bng** [comment]
Yeah, I see the issue - the problem is indeed on our end.  There are multiple variants under the surface of the given challenge: some meant for lower level players that awards Legendary Gear, some meant for higher-level players that rewards Powerful gear.  (it's a little more complicated for Nightfall's situation, but the end result is the same)

On our side, I was attempting to consolidate reward information, but it neglected to take the different types of rewards into account.  I'll look into what we can do for this.

**Comment by vthornheart-bng** [comment]
TFS 711418

**Comment by vthornheart-bng** [comment]
Okay, this should come through in the October 2nd release!
