### ISSUE TITLE
Some character stats not returned if they equal zero

### ISSUE THREAD

**Issue by jgayfer** [Bungie-net/api#69]
I'm grabbing stats for characters (specifically mobility, recovery, and resilience), and I'm getting inconsistent responses. Earlier today, I was able to get all three of these stats for the desired character. But now I'm running into the issue of my call to GetProfile sometimes dropping one or more of these stats. I'm 99% sure that the stats are dropped if they equal zero, but that doesn't make a lot of sense given that other stats are listed as 0 if they are 0. It smells like a bug to me, but I'm not certain.

For reference, these are the hash values I'm interested in:
```
2996146975 = mobility
1943323491 = recovery
392767087 = resilience
```

**Comment by vthornheart-bng** [comment]
Yeah - that is intentional.  We intentionally don't return a stat if it equals 0.  The reason is that, in large responses, you could have thousands of stats over hundreds of items that equal 0: so it's essentially just a bandwidth and serialization optimization on our end. (and a bandwidth/deserialization optimization for users picking it up)

Which stats are you seeing that are being returned if they equal 0?  Ideally none should be getting returned in that state - similarly to Destiny 1, our rule of thumb is to not return a stat if it equals 0. (there are some other things we do return if they equal 0, such as progressions)

**Comment by vpzed** [comment]
I don't know if this aligns with your question but it is similar so I'll add this just in case.  The Clan Leaderboards endpoint sometimes returns a class of stats even if all the stat values are 0.

![image](https://user-images.githubusercontent.com/30138020/30222875-16acab62-948e-11e7-9369-f91ceeffee7f.png)

**Comment by jgayfer** [comment]
That stats I'm seeing that equal 0 are the old stats from Destiny 1. Strength, Intellect, and Discipline.

**Comment by vthornheart-bng** [comment]
Ah - vpzed, we're talking character stats as opposed to historical stats.  Historical stats doesn't have this optimization (but arguably should).

For character stats, I believe that was fixed in Destiny 2 to no longer bother to return them if they are 0.  That's intentional: but we're not going to go back to the Destiny 1 endpoint and fix it there.

**Comment by jgayfer** [comment]
Okay sounds good. One last question, why are Destiny 1 stats returned anyway? It's a bit confusing that Strength, Intellect, and Discipline are returned; it's completely workable, I'm just curious.

**Comment by vthornheart-bng** [comment]
Oh - you're saying you're hitting the D2 endpoint and getting D1 stats?  Ah, I didn't realize that was happening - I can fix that, there's no reason why those should be getting returned.

**Comment by bhollis** [comment]
Yup, we're getting D1 stats with our D2 Characters. There also appear to be some odd stats that I wouldn't expect at the character level. An example:
<img width="562" alt="screen shot 2017-09-21 at 8 50 54 pm" src="https://user-images.githubusercontent.com/313208/30728693-a005436c-9f0e-11e7-8e78-b5d2bb03088d.png">

**Comment by vthornheart-bng** [comment]
Yuck, yeah.  I still haven't had a chance to look into this.  Ignore them for now, right now I don't know when I'll have time to investigate why these are still hanging around.  Very odd.

**Comment by vthornheart-bng** [comment]
Character stats (which I really wish, in retrospect, I'd called "attributes"... but I digress) should be fixed up now.
