### ISSUE TITLE
Activity mode type 5(AllPvP) not including Clash/Control from Competitive playlist

### ISSUE THREAD

**Issue by karandashek** [Bungie-net/api#713]
Hi!
When i'm trying get historical list of played PvP games, i'm using mode=5 based on API doc, but it seems Clash and Control in Competitive playlist are not associated with AllPvP. Can you check what may be a problem?
Thanks!

**Comment by vthornheart-bng** [comment]
Ah, thanks for the info!  I'll file a bug and give it a look!

**Comment by vthornheart-bng** [comment]
TFS 717560

**Comment by karandashek** [comment]
Hey @vthornheart-bng ! Is there any news about this issue? Just it seems all 3rd party sites were affected and players can't see full statistics.

**Comment by vthornheart-bng** [comment]
Ah, sorry for the delay in update!  I fixed it, but not in time for it to be on the boat for the October 30th update.  It'll be in the next train out of the station (mid November).

**Comment by karandashek** [comment]
Awesome! Thank you!

**Comment by vthornheart-bng** [comment]
n/p!

**Comment by Akumati1435** [comment]
Does this impact the stats endpoints too?  Like, destiny tracker for example: https://destinytracker.com/d2/profile/pc/shadzey-1927

It says he has 413 overall games played yet it says 362 in QP and 98 in comp.  It doesnt add up.

**Comment by ashleypb** [comment]
I guess this is going to be released fairly soon, do you know what the mode specific numbers for Competitive Clash and Control are going to be.

**Comment by vthornheart-bng** [comment]
For now, they will be returned in the existing Clash and Control modes.  There is ongoing discussion about refactoring our activity modes to specifically split competitive and quickplay playlists, but that's another issue that has some downstream ramifications we've yet to tackle..

**Comment by nine13tech** [comment]
I'd love for some hierarchy/inheritance from the game modes. Clash is Clash as a game mode, but the type would be a constant assigned list like IB or Competitive etc, then add a new key value for the season being returned. The new hash for IB Season 4 replacing the hash for IB season 3 took me by surprise. I finally gave up on the public endpoints because all the hashes change so often I couldn't keep up with only a few things I wanted to report on.

**Comment by vthornheart-bng** [comment]
Ah, I think I can help with that (as it sounds like the issue you're running into is with the inconsistency of the hash for the Iron Banner playlist activity?).  The Iron Banner activity *mode's* hash remains constant across seasons - but if you're looking for the specific Activity hash, that is unfortunately under the control of the PVP designers who do tend to make whole new playlists between seasons instead of reusing existing ones (thus creating new hashes for them).

However, both the new and old playlists should have the same activity mode assigned to them: if you check for the activity mode of the activity being played rather than the activity hash itself, that should be more consistent!

**Comment by vthornheart-bng** [comment]
Ah, the original issue mentioned here has been fixed.  There is a further question about competitive and quickplay variants being split into their own modes, but I don't know when we're going to have time for that currently.  (as mentioned above, there's a bit of a larger question at stake here about whether we should do more - and potentially backcompat-breaking - activity mode rearranging)
