### ISSUE TITLE
2 burst side arms report 'zero' rounds per minute in the api

### ISSUE THREAD

**Issue by designker** [Bungie-net/api#724]
2 burst side arms such as Death By Scorn 'itemHash: 3334276333' have a rounds per minute stat of zero in the api.

**Comment by vthornheart-bng** [comment]
Interesting, thank you!  I'll take a look around in there.

My fear is that this is a similar situation to magazine size: where the actual effect is being determined/heavily modified by scripts instead of by the stat.  If that turns out to be the issue, I may not have much of a recourse for the stat we return to you.  Hang tight.

**Comment by vthornheart-bng** [comment]
TFS 722962

**Comment by floatingatoll** [comment]
Note that a simple numeric stat is shown in game, and doesn’t seem to much vary by script other than fixed by perks, so even if the value shown in-game has caveats attached, assuming that value is predictably created and not purely script, we’d all be happy with that (see also Magazine Size priors here).

**Comment by vthornheart-bng** [comment]
Hmm, that's interesting - indeed, if it's got even a fake stat that at least should be appearing.  Something funky is up, I'll try to get to the bottom of it.

**Comment by vthornheart-bng** [comment]
Oof, I see what's happening - good news is it's not scripting causing this, just a bug on our side that I'll fix up for my birthday release. :)

**Comment by vthornheart-bng** [comment]
Fixed as of v2.3.3 deployment (12/11)!
