### ISSUE TITLE
Suggestion for repository management

### ISSUE THREAD

**Issue by vpzed** [Bungie-net/api#74]
I have a procedural suggestion.  On other projects I've worked on the administrators don't close Issues where revisions are planned for the repository until after those changes are published.  After the revision is committed, then they will close the ticket and reference the respective commit.

For example I've had multiple people ask about how to lookup the clan for a user and scanning the normal Issues view won't let them know about the closed thread.  They'd have to search closed which is counter-intuitive.  If the issue is closed it is usually expected to have been resolved.

Again just some feedback on how I've seen it done on other projects.

**Comment by vthornheart-bng** [comment]
Ah, that's a good call.  When we first started up, I was closing tickets when I resolved them in our codebase - but indeed, that's not helpful externally.  I can't exactly reference a commit here since the actual API itself is hosted elsewhere, but I can hold off on closing items until we actually deploy the fix.

Yesterday, I started tagging items as "for next release" to inform others and remind myself that these will be fixed in our next deployment.  Hopefully that will be a preferable alternative!  Let me know what you think of that.

**Comment by vpzed** [comment]
Actually you can reference the GitHub commit (not your internal commits of course)  

Like this  https://github.com/Bungie-net/api/commit/dddf93ff8d6599d37ea9d0a736c79b561825f6eb

You just paste the link to the change after you've made it here on GitHub.  It shows up in the [Commit history](https://github.com/Bungie-net/api/commits/master)

**Comment by vthornheart-bng** [comment]
Ahh - yes, for documentation, good call!  I'll do that for Documentation deployments/updates.

I've also got to figure out a good pattern for releasing documentation - I'd like to release documentation a little bit before the feature actually releases when the designers allow me to, so that everyone can be prepared for changes.  But I don't want to trick people into thinking things have been added/changed before the actual deployment happens - I'm considering either making a separate Repo for "preview" documentation, or perhaps just a separate folder in this repo.  Have you seen any good precedent out there for such a thing?  I don't mind copycatting common Github practices. :)

**Comment by vthornheart-bng** [comment]
I suppose we could have branches as well... but that feels a bit odd to me, because everything's codegen'd and I'd never actually merge branches together... hmm.

**Comment by vpzed** [comment]
It could be a separate repository like "api-preview" or whatever, with a clear README that the information is preliminary and may not be currently available and to see the "api" repository for released stuff.

**Comment by nine13tech** [comment]
Python-Social-Auth (as an example) has a secondary repo for generated documentation. you can update that so we can see it early -- say off cycle, maybe sprint middle -- then when the new update is pushed (on cycle release) we have already seen it?

**Comment by floatingatoll** [comment]
That’s still a fine use of branches, as long as you clearly say so in your repo’s README.

**Comment by vthornheart-bng** [comment]
Hmm - yeah, it would be nice to keep it all in the same repo, the branches are a bit more tempting now that I've thought about it a bit.  The alternate repo approach seems good as well... but let's try branches for now, and if it feels awkward we can nuke those and switch to an alternative repo.

I won't always be able to release the info early, because sometimes I'll be asked to keep API changes a secret for new features and the like.  But when possible, I'd like to give more of a heads up than we used to.

**Comment by nine13tech** [comment]
VThorn - if we use branches, a development or pre-implementation branch would be great! If you guys went with a development branch that allowed us to contribute to the OpenAPI Spec JSON, that would be awesome too and it might take some burden off your team to get some of that done!
I'm pretty sure that many of us would be willing to contribute!

**Comment by EdgarVerona** [comment]
Cool - I'll try to make this happen soon.  The only problem with contributing to the spec is that it's generated rather than hand-crafted - though perhaps we could accept requests for improvements in documentation text?  We just wouldn't be able to directly merge changes into it, but we could do updates to the source data upon which it is generated!

**Comment by vthornheart-bng** [comment]
Whoops, posted with the wrong account!  Let me try that again.

Cool - I'll try to make this happen soon. The only problem with contributing to the spec is that it's generated rather than hand-crafted - though perhaps we could accept requests for improvements in documentation text? We just wouldn't be able to directly merge changes into it, but we could do updates to the source data upon which it is generated!

**Comment by floatingatoll** [comment]
That just means you wouldn't be able to *merge* pull requests — and if you did, it'd get overwritten on the next doc run. You'd still be perfectly able to receive them, discuss them, say "We accept this and committed it internally", and close them. While not the most common approach, it's *absolutely* permissible and wouldn't look very weird to any random outsider since closed PRs aren't shown by default.

**Comment by vthornheart-bng** [comment]
Yeah, I think we're saying the same thing. :)
