### ISSUE TITLE
Return Valor and Gambit multipliers for weeks via API

### ISSUE THREAD

**Issue by delphiactual** [Bungie-net/api#779]
Weeks that have double valor(infamy) and triple valor(infamy) weekends. Would be great if this info could be returned by the API.

**Comment by vthornheart-bng** [comment]
As in to tell in advance?  Or to give something indicating it's currently happening?

I think we could actually give the latter!  The former we could give with some manual configuration, but because the start/end of these activities controlled by humans and not the system, we would not be able to give any guarantee that the dates we happened to configure to send back to you were "real".  (We usually hesitate to do this as a result)

But if it'd be useful to get a status indicating that one of these is active *currently* (without any info regarding when it started or when it will end), that is something we could do!

**Comment by floatingatoll** [comment]
Current state would be lovely, regardless of whatever else.

**Comment by delphiactual** [comment]
Current state

**Comment by vthornheart-bng** [comment]
Sweeet, this should be very doable then.  Thank you!

**Comment by delphiactual** [comment]
Closing in favor of #1613
