### ISSUE TITLE
How do you determine how many times a player reseted his/her rank?

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#780]
The progress doesn't look like (to me :D) to contain overall points or how many times the player rested it

```
 {
                            "progressionHash": 2772425241,
                            "dailyProgress": 0,
                            "dailyLimit": 0,
                            "weeklyProgress": 1910,
                            "weeklyLimit": 0,
                            "currentProgress": 6215,
                            "level": 10,
                            "levelCap": 16,
                            "stepIndex": 10,
                            "progressToNextLevel": 865,
                            "nextLevelAt": 1000
}

```

**Comment by vthornheart-bng** [comment]
Good call!  Indeed, we don't provide that information at the moment - I will have to investigate what we can give.  When the progression gets "reset", they're actually resetting the progression back to 0 - which means the "number of resets" is being stored somewhere else - some other location that we're not currently accessing and returning.  I'll have to dig around and see if I can find out where that's at and if it would be reasonable to integrate it into the progression data.

**Comment by vthornheart-bng** [comment]
TFS 738187

**Comment by nine13tech** [comment]
@vthornheart-bng Could this not be pulled from the personal inventory "banner" item that tracks the resets? That, however, precludes that the guardian would have possession of that banner. I was looking for this data somewhere, but I got sidetracked by work tasks.

**Comment by vthornheart-bng** [comment]
Exactly what I need to check on - if that item's data is actually stored on the item, then that's not a suitable/consistent location to pull the data from as we can't assume everyone has the banner.  But my bet is that it's being stored in a more centralized location such as the account or character and merely being displayed through that item.  I'll look into it when I loop back to this.

**Comment by floatingatoll** [comment]
In the Valor Rank case, you're granted an emblem when you reached maximum
valor that shows "0 resets" on it, and it accurately reflects the reset
count whether or not the emblem is present in inventory or is only in
collections at the time of each reset. The Crucible vendor also has logic
that seems to somehow evaluate the reset count, so there may be useful
hints in the vendor script there as well.

**Comment by SarKurd** [comment]
That's true, there are emblems for Glory and Infamy too, thanks for tip

**Comment by floatingatoll** [comment]
Thorn, when researching this, look into how these two emblems get their statistics:

True Valor
Fireforged Valor

I can’t say with certainty but I think that you’ll find it enlightening!

**Comment by SarKurd** [comment]
Thanks for that, i'll try to see what i can find
also the one for Infamy called "Playin' the odds"

**Comment by ArkahnX** [comment]
I know in D1 we had progressions for each vendor that included a level property that indicated what rank you were with that vendor (I think that was the property at least)

Could we add something like that to the glory, valor and infamy progressions to indicate times reset? Though at the moment this property would be useless for glory because you can't currently reset your glory rank

**Comment by vthornheart-bng** [comment]
Aye, I think it'll end up being something like that.  Maybe all progressions have an optional "resets" property that's only populated if we have reset data for it.  I dig it!

**Comment by joshhunt** [comment]
@SarKurd alternative workaround - look for triumphs (records) that contain this info. There's triumphs for basically anything in the game (enemies killed with void vortex grenades!), and all that data doesn't require authentication

**Comment by SarKurd** [comment]
@joshhunt that's what i'm trying t do now but finding the one i need takes so long, i wish they could return the name of the triumph instead of the hash.

**Comment by vthornheart-bng** [comment]
Aye - we don't return the name of any entities because we, as a policy, refrain from returning localized content in Destiny responses.  It reduces the size of our already large payloads, so we depend on folks who use the API to use our manifest databases for localized content.   It also allows us to cache Destiny data once instead of caching the data potentially once per locale.  We also can't guarantee that any given localized string can both be immutable between versions and that it will be unique for a given entity: that's why every entity you see in the API is referred to by a hash instead of by any localized name.

It definitely can be a frustrating level of indirection, but the nice part is that the hashes are both uniquely identifiable for a given type of entity, and that they are at least intended to be content version immutable: once you find a hash for an entity that you want to inspect, with some unfortunate exceptions (such as activities, where many activities designers create new playlist activities every season), you can rely on that hash as consistently pointing to that entity.

**Comment by joshhunt** [comment]
@SarKurd https://clan.report/triumph-report, wait a bit for it to load.

**Comment by nine13tech** [comment]
@SarKurd found it.. .
https://data.destinysets.com/i/Record:559943871

**Comment by SarKurd** [comment]
@nine13tech  @joshhunt thank you guys, you saved me a lot of time. My app is finally finished for gambit, gonna work on implementing crucible and raid tomorrow.

Thank you all again

**Comment by vthornheart-bng** [comment]
Oof, okay so this is ancient, but it bubbled up to the top of my bug list and I have a bit of unexpected time this afternoon, I'm going to try and make it happen.

Here's the plan, let me know if you hate this:

If a progression has a reset count that we both know about and can get (right now, only PvP "Embers" and Gambit "Infamy"), we'll start returning the following data with the progression:

* The count of resets in the "current" season: "currentSeasonResets"
* A list of resets for every season that has resets which we were able to save historical info for: "seasonResets".  The array will have:

{
"season": (# of season)
"resets": (# of resets)
}

We will only have info from Season 3 onwards.

How does that work for you folks?

**Comment by justrealmilk** [comment]
yes, awesome @vthornheart-bng

**Comment by EdgarVerona** [comment]
Sweet! <3

**Comment by SarKurd** [comment]
Amazing, thanks for the hard work.

**Comment by vthornheart-bng** [comment]
<3

**Comment by vthornheart-bng** [comment]
Oh!  This finally made it live - take a look and let me know if it suits your needs!
