### ISSUE TITLE
Aggregate Activity Stats Endpoint returns empty Response object

### ISSUE THREAD

**Issue by ChaseMalik** [Bungie-net/api#79]
Example call: https://www.bungie.net/Platform/Destiny2/1/Account/4611686018429501017/Character/2305843009264156806/Stats/AggregateActivityStats/ 

```
{"Response":{},"ErrorCode":1,"ThrottleSeconds":0,"ErrorStatus":"Success","Message":"Ok","MessageData":{}}
```

Expected:
The response to have an object with one property - `activities` that is an array of aggregate activity objects.

**Comment by vthornheart-bng** [comment]
Ah, thanks for the info!  I will investigate, I'm currently knee-deep in investigating stats-related issues, so I will include this in the data.

**Comment by BlazeBoss17** [comment]
This issue is currently a launch-blocker for my website. Having the main stats endpoint of the API completely broken is a huge issue for us. 

Over the last five weeks, I have had to keep telling our users there is nothing we can do unfortunately. 

Any updates or possible ETA?

**Comment by vthornheart-bng** [comment]
My apologies for the extended delay and lack of progress, I am only now getting back through the Issues log and have just seen your message now.

I have not yet found the time to investigate the root cause of this issue.  I'll bring this up for conversation internally on monday, and see if we can get this investigated and resolved for the November 1st release, which is the soonest release that I would likely be allowed to include the fix once we resolve it.  I'm sorry that you've been delayed so long on your project as a result of these unexpected circumstances.

**Comment by vthornheart-bng** [comment]
Okay, good news on this - it turns out Tetron fixed this internally along with a variety of other Stats problems.  The fixes should be getting pushed through late this week, we'll update the documentation here when we push it live.  Thanks for your patience on this.

**Comment by levscaut** [comment]
I encounter this bug again. Could anyone check if this bug happens again? the path i query: https://www.bungie.net/Platform/Destiny2/3/Account/4611686018491983000/Character/2305843009521296002/Stats/AggregateActivityStats/ and it's not always empty but sometimes reponse with valid data
