### ISSUE TITLE
Items with stackUniqueLabel should be nonTransferrable

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#790]
Specifically [Ghost Fragments](https://data.destinysets.com/i/InventoryItem:4114204995) have a `stackUniqueLabel` but are marked as transferrable. Weirdly, they can be transferred as a whole stack, but can't be transferred as a partial stack! The API should probably either allow these to be partially moved to and from the vault, or make them non-transferable?

**Comment by vthornheart-bng** [comment]
Okay, I asked the source and it turns out this is intended and by design.  Items that have a stackUniqueLabel are intended to not allow partial stack transfers: it's an intended effect, and we're going to continue to allow it as the game itself also does (and also has the seemingly peculiar but intended side effect of not allowing partial stack transfers).

**Comment by floatingatoll** [comment]
Excellent, thank you for clarifying!
