### ISSUE TITLE
Add Triumph rewards to manifest

### ISSUE THREAD

**Issue by lowlines** [Bungie-net/api#803]
With the release of Black Armory, it looks like some Triumphs now sport a reward icon and info about what rewards you get for completing them. Can this info be added to the manifest?

![dty5z8-v4aepo9x](https://user-images.githubusercontent.com/4862548/49519806-64fa6500-f8e9-11e8-89fb-3615c7499bf8.jpg)

**Comment by LordNazo** [comment]
I would like to see this as well. I think there are some Triumphs in-game that give rewards but don't visibly state it. Could we include those as well?

**Comment by vthornheart-bng** [comment]
Ooh, good question!  I'll look into that.

**Comment by vthornheart-bng** [comment]
Could you give me an example of a record that has "secret" rewards?  I'm not 100% sure I'd be able to/allowed to return that data, but I can look into it if you've got an example handy.

**Comment by vthornheart-bng** [comment]
I will note though that I don't see the reward icon in our content: my guess is that's baked right into the UI.  But I do see that reward data, along with expiration data that we're not currently pumping through: I'll see about getting that exposed!

**Comment by ArkahnX** [comment]
I don't have any hashes (mobile sucks) but I believe @lordnazo was referring to triumphs such as the harbringer's echo sparrow which is a reward for cashing in the triumph for finding all 40 corrupted eggs

I believe this is probably a scripted reward rather than noted reward, considering it's been broken since it's launch, so the data to link the sparrow to the triumph doesn't exist automatically
