### ISSUE TITLE
How do I get all the weapon types in Destiny?

### ISSUE THREAD

**Issue by wherkamp** [Bungie-net/api#829]
How do i get all the weapon types in Destiny? So basically all the types.

**Comment by vthornheart-bng** [comment]
It depends on what you mean by weapon type!  If you're just asking for things like "shotgun," "Hand Cannon" etc... you could grab them from DestinyItemCategoryDefinitions (https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyItemCategoryDefinition.html).  You'll have to grab the manifest databases or JSON file, and pull it out from there: but once you set up your system to pull them, you should be able to acquire that info.

If you're counting the intrinsic properties of an item as its "type" as well (such as "High Impact Frame", "Adaptive Frame" etc...)... that becomes a little more complicated.  But let me know if you care about that before I go rambling about it.

**Comment by floatingatoll** [comment]
Those would each be listed in the SQLite database that’s available through the Bungie.net API docs at the GitHub main page for this repo.

Note that this is a programmer-focused forum, so you won’t find instructions for getting the weapons in-game here (and those instructions aren’t in the API datasets either). If your goal is simply to get the weapons in the game, you’ll need to use a Destiny players’ forum or wiki to find out where those items drop. (For example, Play of the Game drops from Crucible activities, IIRC.)

**Comment by wherkamp** [comment]
Sorry, I need all the weapons like in a xml or json format.  Or some,format. I am going to build a random load out generator. So I can take all the weapons in game and stick them in an Java List and grab 3 one heavy, one secondary, one,primary, and check to make sure no double exotic. Does that make more sense?

**Comment by vthornheart-bng** [comment]
Oh, I see!  Yes, in that case what you're looking for is the "inventory bucket" in which an item is found.  If you grab the manifest database, check out DestinyInventoryItemDefinition.inventory.bucketTypeHash:

https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyItemInventoryBlockDefinition.html#schema_Destiny-Definitions-DestinyItemInventoryBlockDefinition

That is a hash identifier that will give you the inventory bucket to which the item belongs.  If the bucket's category property is "Equippable" (see https://bungie-net.github.io/multi/schema_Destiny-Definitions-DestinyInventoryBucketDefinition.html#schema_Destiny-Definitions-DestinyInventoryBucketDefinition) then items within that bucket can be equipped.

From there, you should be able to call GetProfile to get the user's inventory items, filter them by bucket, and then choose at random the item currently in that bucket that you want to equip if you're looking to use live data for this!  If it's more of a theoretical one that isn't using live data, then you could just use the definition properties above to do a similar random pick!

Let me know if this helps!

**Comment by floatingatoll** [comment]
Are the in-game locations “Vault” and “Inventory” two examples of an API “inventory bucket”?

**Comment by vthornheart-bng** [comment]
Sort of: inventory buckets when you look at them in-game correspond to a single area where items are located (usually visually grouped together in the UI, though sometimes buckets are "invisible" or serve special purposes).

In the past, the Vault was actually three buckets.  If I recall correctly, they were something like "general", "weapons", and "armor".  These days there's just one big "General" bucket, that has the hash identifier 138197802.

Buckets that one would consider to be their "inventory" from a UI perspective would likely consist of things like "Pursuits" (1345459588), "Shaders" (18606351), "Modifications" (3313201758), and "Consumables" (1469714392).

However, it should be noted that other groupings of items are represented as inventory buckets as well, and may also be in play for what you're looking for!  For instance, every equipment slot has an associated inventory bucket - the one that holds all of the items you have for that slot that aren't equipped - like "Kinetic Weapons" (1498876634) or "Helmets" (3448274439).  you'll want to look through the manifest database's DestinyInventoryBucketDefinitions to see what's available and decide for yourself which buckets you care about!

Ultimately, in the live data we're going to return all of these items - any item that's not equipped but that is in one of these buckets - when you request the ProfileInventories and CharacterInventories components.  If you want a user's equipped items specifically, you can ask for the CharacterEquipment component.  (it is split out for two reasons: (1) because I was hoping a common use case would be to get equipment but not inventory, saving everyone a ton of bandwidth, and (2) because by default you are allowed to get a user's equipped items but NOT their inventory if you're making a call for them anonymously, and this helped us distinguish between those two sets of "public" and "potentially private" data... for better or worse)

**Comment by wherkamp** [comment]
This is what I want to build. It will live inside a Discord bot. So I will run /gen-loadout
It will pull from the Bungie API. So all the different weapons that exist. So Play Of the Game, Origin Story, Better Devils, Jade Rabbit.
However I need all of those plus more. If this is not possible I will go to plan B of inserting each one which will be fun,
Then I will sort those into the three weapon types. Heavy, Secondary, and Primary. Then I will grab one from each category. Check to make sure no double exotics. Then send the loadout inside the Discord chat. The Part I need is getting all the different weapon types. 

It will work like this did? https://www.bungie.net/en/Forums/Post/243550692?sort=0&page=0 I don't care if the user has it we will figure that out when we build our load. I will also remove Whites, Green, and Blues.

**Comment by dad2cl3** [comment]
A possible solution might be to build the JSON you need by reading the manifest directly and storing the data in memory when the bot starts. You would also need to utilize a background task to refresh the data when a change to the manifest occurs.

**Comment by wherkamp** [comment]
Alright. So I am looking. 
So I went and got the manfiest. https://paste.ee/p/7PL2m
Now what one of these elements is the sqllite database for the items. "mobileGearAssetDataBases" Is my guess. Also how do I read a .content file?

**Comment by wherkamp** [comment]
So I think I figured it out. I am not going to close this yet since I am an idiot. Thx for the help so far :)

**Comment by dad2cl3** [comment]
https://github.com/vpzed/Destiny2-API-Info/wiki/API-Introduction-Part-3-Manifest

________________________________

**Comment by dad2cl3** [comment]
Read that wiki. vpzed did a great job writing it.

**Comment by vthornheart-bng** [comment]
It's all good - don't slam yourself, you're doing great!  Getting the manifest online is one of the hardest parts, because it is not at all intuitive unfortunately and only unofficial guides currently exist (vpzed's guide is fantastic!  But you basically have to know it exists... I should link to it somewhere)

**Comment by dad2cl3** [comment]
Oh and join the API Discord server. You’ll get a lot of assistance there.

**Comment by wherkamp** [comment]
API Discord Server? Invite URL? I love Discord servers.

**Comment by dad2cl3** [comment]
https://discord.gg/m82sew try that one


________________________________

**Comment by wherkamp** [comment]
Worked thx Friday, 28 December 2018, 05:39PM -05:00 from dad2cl3  notifications@github.com :

**Comment by cjhoffmn** [comment]
>" https://discord.gg/m82sew try that one"

Is this discord server still up? I'd love to join -  can someone send a new invite?

**Comment by wherkamp** [comment]
@cjhoffmn https://discord.gg/c3YFKQq

Closing Issue.
