### ISSUE TITLE
Iron Banner Specific Medals

### ISSUE THREAD

**Issue by mattybeard** [Bungie-net/api#859]
From what I can see, Iron Banner medals are not being returned in a PGCR response. I believe they just return `medalUnknown`.

https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/3467339811 as an example topic, entry has a 32-0 KD which I believe should have earned the "Iron Legend" medal which is "In a single life, defeat 20 opposing Guardians." but all I can see in PGCR response is 

```
 "medalUnknown": {
                            "basic": {
                                "value": 1,
                                "displayValue": "1"
                            }
                        },
```

**Comment by vthornheart-bng** [comment]
Yeah, to steal the words of Abraham Lincoln as he watched Hamlet, "Now I fucked up."

They're sitting in the stats backend waiting for us to wire them up, and that's a total miss on my part that we haven't done so yet.  I will try to make sure we get around to this before I leave for my honeymoon!

**Comment by vthornheart-bng** [comment]
I just realized that could be misinterpreted if you don't have my bizarre reference in mind!  I'm referencing this, which I will gladly share because it's the most amazing thing on the internet:

https://www.youtube.com/watch?v=VPJ0TAaJDbM

Anyways, TL;DR I fucked up and it's still not in yet.  I'll see if I can cram it in while I can!

**Comment by justrealmilk** [comment]
This is resolved

**Comment by vthornheart-bng** [comment]
Ah, thank you for mentioning that!  Closing it up.
