### ISSUE TITLE
InstanceId for Petra's Run and Like A Diamond

### ISSUE THREAD

**Issue by SarKurd** [Bungie-net/api#869]
Is there a way to get their instanceId?

**Comment by vthornheart-bng** [comment]
Oh, as in to get the PGCR IDs of games that have been played for those activities?  (sorry for the long delay, things got a little busy between my wedding and the honeymoon - I'm back now!)

**Comment by SarKurd** [comment]
Congrats, wish you the best
Have a property in the PGCR to find out if a wish or like a diamond was a active

At this moment i get the Petra's run and Like a Diamond though profile records, you could add the instanceId there directly

**Comment by vthornheart-bng** [comment]
Ohhh, I think I see what you mean, let me know if I'm understanding correctly - so what you want to see in the PGCR is whether or not there were various modifiers being applied during a particular activity?

(we wouldn't be able to do the flipside of that: that is to say, if you're asking if we could return PGCR instance IDs in profile record data, we'd be unable to do that.  Having whether modifiers were active in PGCR data may theoretically be something we could theoretically do - but I can't make any promises due to the potential cost that could be involved in adding that data and the time that our stats team has to work on it)

**Comment by SarKurd** [comment]
I would love to see that being added in the future

**Comment by vthornheart-bng** [comment]
Cool - yeah, I dig that idea!  I'll bring it up to folks on the stats side.
