### ISSUE TITLE
Anatomy of Destiny.HistoricalStats.Definitions.DestinyActivityModeType

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#876]
I'd super appreciate it if anyone knowledgeable in the area could help me break down what's included where.

Which strike/nightfall modes include what for example? 
Does AllStrikes/18 include nightfalls?
What times do different modes span?

Ref: https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType.html#schema_Destiny-HistoricalStats-Definitions-DestinyActivityModeType

**Comment by smalltimecharlie** [comment]
I'd also like some clarification on this if possible. I looked at some info for my characters and could see the following: 

![image](https://user-images.githubusercontent.com/17934736/52940022-6de1cb00-335d-11e9-99dd-14d59c1421ca.png)


However when looking at the triumph it says i have 45 night fall completions (I was expecting this to be 39 from the sum of all the scored nightfalls(type46)?)

**Comment by vthornheart-bng** [comment]
In terms of the hierarchy of what ends up under which types, the best thing to check is the descendantHashes property: that's the set of all Activity Modes that should show up as "under" the current Activity Mode you're looking at.

For instance, AllStrikes has:

4110605575 - strike
3789021730 - nightfall
1350109474 - heroicNightfall
547513715 - scored_nightfall
532484583 - scored_heroicNightfall

(Jesus, my naming conventions for these have been terrible... I'm so sorry.  Look at that underscore and camelcasing hodgepodge.  Yikes)

Using this approach, you can build up a "hierarchy" of where activity modes appear when they're bucketed together.

Note that a lot of these have some obvious superior alternatives in bucketing that aren't happening.  That's work that I mentioned late last year that I'd like to do if we have time, to overhaul/break bones on Activity Modes and totally redo the hierarchies so that they're more logical and consistent.  (some things are super-well broken down into a hierarchy, some aren't at all - when we have time, I have a plan for making a much more consistent breakdown, but it'll involve making some backcompat-breaking changes if you're assuming the existence of certain activity modes or where they are in the current hierarchy)

I hope this helps!

For Triumphs vs. historical stats, there's unfortunately many reasons why the numbers may mismatch.  For instance, it is entirely possible that 6 of your nightfall matches happened in some time range where we lost stats data: occasionally we do have stats problems on the backend that are severe enough that the data can't be recovered, which would cause the discrepancy you're seeing there.  It's unfortunate, but that's also the most likely cause for such mismatches.
