### ISSUE TITLE
Issues with Milestones / Challenges

### ISSUE THREAD

**Issue by sgtfrankieboy** [Bungie-net/api#88]
While going through the milestone endpoint stuff I noticed that almost all the `challenges` lists are empty, except that of Nightfall.

Another problem I discovered is that the public endpoint only lists 1 of the 3 meditations.

**Comment by vthornheart-bng** [comment]
Yeah, we've got another bug under investigation about the Meditations - but the challenges is good to know.

You mentioned they were (just adding them here so I don't forget when I get back to this):

* Planetary Challenges
* Crucible Challenges,
* Strike challenges

Are they only missing in the public milestones?  Or when you get your own milestone data as well?

**Comment by sgtfrankieboy** [comment]
They are missing from both the public and profile endpoints.

**Comment by benedfit** [comment]
I can also confirm that when they are returned via the profile endpoint, all possible challenges are returned, and not just those that are currently active

**Comment by ArkahnX** [comment]
Just updating this issue, Ikoras meditations (3245985898) show an activityHash within each quest object, I've confirmed in game that the activityHashes are correct.

Trials of the nine (3551755444) also contains 3 challenges (Can't validate if they are the correct ones)

The raid (3660836525) contains  3 challenges for normal (validated in game) and two for prestige (validated in game)

The nightfall has 3 challenges for normal and prestige, validated in game.

Whats missing seems to be challenges for each crucible playlist (excluding trials), strike challenges, and challenges on each planet.

Having access to challenge data on the getProfile request would be nice as well, in order to mark out which challenges the player has left.

**Comment by vthornheart-bng** [comment]
Next full BNet release (slated for early February) should have these coming through now.  Note that for Milestones that cover Challenges over a wide swath of activities, it will *not* return the "Activity" property (as there are potentially dozens of Activities, and at least for now they don't have particularly interesting information to return other than the Challenges).  It will populate the "challenges" property with challenges for all activities that the character can reach.

**Comment by vthornheart-bng** [comment]
There we go!
