### ISSUE TITLE
activityModeType of 75 and 76 are not in the docs

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#883]
Also, 76 never seems to have a completion reason of anything other than Unknown (255).  Not sure if that was intended.  Heck I dont even know what these are... I'd assume reckoning and gambit prime but i could be wrong.

**Comment by kramrm** [comment]
From what I've been able to tell, 75 = Gambit Prime.  76 = Reckoning.  Because you can load into Reckoning and then do multiple rounds right after each other, my best **guess** is that it reports as unknown since it seems to count multiple rounds (orbit to orbit) as one activity in the PCGR.
Somebody with official knowledge please correct me on this.

**Comment by vthornheart-bng** [comment]
Indeed, 75 is Gambit Prime and 76 is reckoning: we should be updating the documentation later this week to reflect that, I'll update the Github changelog accordingly when that happens!

And indeed, we ran into this issue as well unfortunately regarding Reckoning completion reasons,  After some investigating the folks working on Stats found out that, due to the way Reckoning has been implemented, we're not going to be able to give useful completion stats for that activity.  They're going to work with the Activities team using what we've learned from this experience to try and prevent this from happening for new types of activities in the future.

**Comment by ats** [comment]
Will Gambit Prime be reported in the "Comp PVE" category (mode 64)? Likewise, Reckoning doesn't get reported in the "All PVE" category (mode 7). Will/Should it? It seems like there's a little drift in the use of those *all X* modes, so I just currently grab 5, 7, 64, 75 and 76.

**Comment by floatingatoll** [comment]
VThorn, you may also want to have the stats wizard check out whether Reckoning/Prime matches are being counted as “Private Matches” by any of the triumph counters internally.

**Comment by vthornheart-bng** [comment]
Yes, the next deployment will have Gambit Prime appear under Competitive PvE.  I need to look into Reckoning, but I think that makes sense to put it under AllPvE tentatively.

Private Matches is another separate issue that unfortunately has to be fixed deeper in the stats system.  I'm not 100% sure on when that fix is going to go live, but I'll check on that.

**Comment by floatingatoll** [comment]
Oh, as long as you’re aware, no need to follow up; cheers!

**Comment by vthornheart-bng** [comment]
Ah, it looks like the private matches fixes should tentatively be released in early April, but it's still up in the air somewhat as it's coming in hot.  I'll loop back once I know for sure, but right now that's the most likely scenario.
