### ISSUE TITLE
The date a person joined their clan isn't correct.

### ISSUE THREAD

**Issue by Akumati1435** [Bungie-net/api#888]
I thought I had a bug in my clan history code for about 6 months now, but until recently it didn't really affect anything.  I'm at a point where I need it to be accurate so I finally dug into this issue.

**Steps to reproduce:**

1. Have a person request to join a clan.  let's say it is at 10:50PM.
2. Wait 5 minutes so you can see what I'm talking about.
3. Accept the request to join the clan.  Let's say this is at 10:55PM.
4. Look at their joined timestamp.

You'd expect the time they joined to be the timestamp for step 3 because that is when they joined the clan... but it's actually the time they requested to join the clan (step 1).

Now that I finally know what is going on I'll patch my code to look for this, but since this isn't intuitive and probably isn't how you intended it I'm posting this here.

**Comment by vthornheart-bng** [comment]
Hmm, I'll hit up some folks about it.  Thank you!

**Comment by vthornheart-bng** [comment]
Okay, I got an answer on it - unfortunately due to the internal constraints of the clan system and how invites affect your available "clan slots," the system treats the request date as the join date.  It sounds like there's no bandwidth to address that issue for the foreseeable future, so your planned workaround will likely be the best approach for some time.  Sorry about that!

**Comment by vthornheart-bng** [comment]
I'm going to go ahead and close it for now because I was told that we weren't going to be able to fix it, but if you run into anything else let us know!

**Comment by Akumati1435** [comment]
Ok.  Thanks for the response!

**Comment by vthornheart-bng** [comment]
No prob!
