### ISSUE TITLE
Off topic, but I need some help from Bungie.

### ISSUE THREAD

**Issue by Akumati1435** [Bungie-net/api#891]
https://www.bungie.net/en/ClanV2/Index?groupId=3744126

The leader of this clan was banned from Apexus Deft's clans and discord because he was throwing in a raid, then when he was asked to leave, he followed them around in our discord preventing them from replacing him.  The group needed to go to another discord server to complete their raid.

**We do not want our clan associated with this person.  He is pretending to be part of our community and with the name set how it is, we will not be able to create a Div 9 when the time comes.**

Can you help?

**Comment by floatingatoll** [comment]
Unfortunately, this is an issue tracker for the API team alone, and they have no ability to escalate such requests and can only direct you to file a post on the Bungie Help forums. Sorry to be the bearer of bad news.

**Comment by Akumati1435** [comment]
Thorn's helped with random stuff in the past so I figured it's worth a shot.  I have literally 0 faith in the help forums. I've spent hours making posts there, gotten hundreds of upvotes, and been completely ignored by Bungie.  Once I was told to do something that I already told them I was doing (and it wasn't working).  It's a  complete waste of time.

I'm not sure exactly how this will make me sound, but I feel like people like me deserve a better escalation path.  To my knowledge, my clan's discord is literally the #1 most active destiny 2 **clan** discord server in their game (in terms of voice activity).  The only one that has more voice activity than mine is Welfare's LFG server (not a clan). We're discord partnered because of this. With the endless hours I've spent automating my clan and trying to keep people playing their game, I feel like an email address is the least they could do to help support us. 

I mean, why wouldn't Bungie want to keep people like me doing what we're doing?  If one of the community's top streamers or biggest community owners has an issue, why give us the runaround?  We are promoting their product...

**Comment by ckhicks** [comment]
I'm guessing that champion on their side would be someone in the community manager role. Have you tried reaching out to one of them directly via other networks?

**Comment by Akumati1435** [comment]
They never respond.

I'm attempting to go through work to get contacts now... I feel like this shouldn't be necessary.

**Comment by vthornheart-bng** [comment]
Sorry guys, I have never been able to and are still unable to help with these kinds of issues.  I've got neither insight into nor the power to provide help with problems of this nature: Bungie Help folks are your best bet.

**Comment by Akumati1435** [comment]
@vthornheart-bng  Any chance you can pass it on to them?  Posting on the help boards has been a waste of time every single time I've done it and I don't think you guys have any sort of ticket system for us to submit issues to.  It's one of the most user unfriendly systems possible.  It seems like it's built this way so Bungie can ignore us.

**Comment by vthornheart-bng** [comment]
This puts me in a hard position: if I set a precedent where a person can post here to solve non-API issues/interpersonal conflicts, we're going to end up in a bad spot where the API support site becomes a site where people who are having problems with each other come here to get them addressed, and I can't do that for many reasons - structural, the health of the API site, the usability of the API site for people who come for its intended purpose, and the interruption of my job that would come from trying to address and reroute these issues.

I would like to help you, but I can't set that precedent - and when push comes to shove, I'm not really in a position in the company where I even _could_ meaningfully help people in this way.  I wouldn't want anyone coming to this API site to falsely believe that I have an inside track to getting a support request bumped up, because I have no power to affect another team's schedule.  My jurisdiction resides exclusively in API-related issues (and even in those areas, I am frequently at the mercy of competing concerns).

I know this is a bummer, but I am not in a position to help you with this.  All I can do is recommend you hit up the existing Bungie Help and Support channels.

**Comment by Akumati1435** [comment]
Ok.  I'll focus my efforts through my work connections to get contacts in
other groups. I have another meeting setup with one of the higher ups in
our gaming group tomorrow.  Hopefully he can help.  If he comes through for
me, my first contact will be in regards to the support structure.  Someone
needs to champion this kind of thing.
