### ISSUE TITLE
Destiny 1 API down?

### ISSUE THREAD

**Issue by ChaseMalik** [Bungie-net/api#898]
All the Destiny 1 API calls I'm making are returning 500s

example request:
`https://www.bungie.net/d1/Platform/Destiny/Stats/PostGameCarnageReport/5207665325/`

response: 
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>
    <body bgcolor="white">
        <span>
            <H1>Server Error in '/d1' Application.
                <hr width=100% size=1 color=silver>
            </H1>
            <h2>
                <i>Runtime Error</i>
            </h2>
        </span>
        <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
            <b> Description: </b>An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated.
            <br>
            <br>

    
        </body>
    </html>
```

**Comment by BinarMorker** [comment]
Wasted on Destiny is currently affected by this issue too. Was this caused
by today's maintenance?

**Comment by L0r3notData** [comment]
Issue happens with both oauth and non-oauth calls.

**Comment by L0r3notData** [comment]
This appears to affect all 3rd party D1 API calls. My own, DIM, Charlemagne, WastedOnDestiny, etc.

**Comment by kramrm** [comment]
Also, the error message has an opening `<font>` tag for the description without a matching closing tag.  Fix the actual issue first, then the server's error message template.

**Comment by vthornheart-bng** [comment]
Thanks for the info!  I'm going to go investigate shortly - my apologies for not seeing this earlier, I've been waylaid by some health issues that are ongoing and was out of commission yesterday.  Let me see if I can get to the bottom of this.

However, this is a good time to give an important reminder for anyone making or maintaining 3rd party apps that still use the D1 API: remember that our original announcement about continued support of the D1 API was with the caveat that it would only continue to function as long as the internal infrastructure we rely on for it would continue to be compatible and functioning.

Due to the infrastructure of D1 internally, it is entirely possible (and may even be the case here, though I hope not) that the production systems no longer are compatible with the D1 API.  In this situation, we will not be able to devote the resources to keep the D1 API alive.

I'm giving it a look, but however this particular outage is resolved it is a good reminder to **make sure that any apps you have that grab both D1 and D2 data don't rely on the D1 data in order for it to continue functioning**.  D1 has been on life support since the D2 launch, and we won't have the resources to keep it running if a significant change causes it to go out of commission on a permanent basis.

**Comment by BinarMorker** [comment]
Thank you very much for your response @vthornheart-bng. I adjusted my API to ignore the D1 API in case it does not work, but I really hope it comes back as it's a real "plus value" to have this data on my website.

**Comment by vthornheart-bng** [comment]
Sweet - yeah, I hope we can get this thing back off the ground.  I know not many people play D1 anymore, but I'd hate for them to lose access to this data and those features if we can prevent it.

**Comment by L0r3notData** [comment]
We have dedicated community of D1 players on both Reddit and Discord. If the D1 API was R.I.P. for good it would fairly impactful. I understand you likely dont have direct control of this. Crossing my fingers and praying to The Traveler its a temporary issue.

**Comment by vthornheart-bng** [comment]
I'm hoping so too.  I know it's been on life support for a couple of years now, but I'd be bummed to pull the plug. :(  Hang tight, investigation is ongoing.

**Comment by vthornheart-bng** [comment]
Okay, we are investigating a fix presently.  It looks like it wasn't due to game infrastructure changes but rather changes to some shared configuration on our side thankfully.

I'll let you know once we know for sure that the proposed fix will work.

**Comment by vthornheart-bng** [comment]
Yes, looks like it's a go.  We're going to see if we have a safe window for deploying it as a hotfix today.  I will let you know when that happens, or if we have to delay it for any reason.

**Comment by vthornheart-bng** [comment]
Should be good to go now.  Phew.

If you haven't had the chance to yet (or even if you did way back when D2 first launched but haven't mentioned it since), definitely let your users know that the D1 API is considered deprecated, and is only going to continue to work as long as there isn't a breaking incompatibility between our infrastructure and the old API.  If it finally dies in such a manner, there'll unfortunately be nothing that we can do to keep D1 apps running.

Fortunately that wasn't the case here, but at some point in the future it may come to pass, so I want to make sure everyone knows that it could happen someday.

**Comment by ChaseMalik** [comment]
Everything seems to be working now.  Thanks for the quick fix.

**Comment by L0r3notData** [comment]
Thanks for your work on this @vthornheart-bng. There was a cheer from D1 Guardians.when it became available again.

**Comment by vthornheart-bng** [comment]
Phew, glad it worked out!
