### ISSUE TITLE
Gambit Prime Role Data

### ISSUE THREAD

**Issue by kramrm** [Bungie-net/api#902]
Is it possible for Gambit Prime PGCRs to include info about player's role stats (reaper/collector/invader/entry)?  If not exact role points, maybe at least if the player had a role aura active for the match and which one?  Would be interesting to track both how often users choose a role as well as to find a common distribution of roles on a team.

**Comment by floatingatoll** [comment]
Can the aura change during a match?

**Comment by kramrm** [comment]
Gear isn't locked, so yes.  If anything, I would figure the data would be the stats at the end of the activity.

**Comment by vthornheart-bng** [comment]
Hmm, I like the idea!  I'm not sure if we'll be able to get it with the backlog of requests on the folks who work on Stats (along with a number of other systems), but I will hit them up.  I get the feeling though that this is going to end up being in the "distant future wishlist" unfortunately.  *but* I think the idea is fantastic, and I wish we had the resources to provide it.

**Comment by vthornheart-bng** [comment]
I talked to some folks and it sounds like there's also - in addition to time constraints to work on it - some significant technical hurdles we'd have to overcome in the way we get these stats in order to get you accurate data for this.  Unfortunately, those combine such that I don't see it being likely to come through in the near future.  But I do dig the idea conceptually and wish we could provide it!

**Comment by kramrm** [comment]
I had a feeling that it might not be easy if it wasn't included to begin with.  Thanks for the update.  I'm happy I just had a Starlight Shell drop.

**Comment by vthornheart-bng** [comment]
Aye, no problem!  And thank you for the suggestions!

**Comment by kramrm** [comment]
RIP Prime
