### ISSUE TITLE
Seasonal character stats

### ISSUE THREAD

**Issue by insanetron75** [Bungie-net/api#906]
Hello! 

I am building a leader board for me and my friends. I have an all time leader board finished, but now we want per season stats. 

I see you can put in a date range and the documentation says the character stats end point can return 'allTime', 'daily' and 'monthly". But when I put in a date range for say, season 5 (27-11-2018 — 05-03-2019) it says invalid parameters. If I do it with a date range of < 30 days it works and gives me the daily stats.

Is there a way to have a larger date range and/or to get the stats monthly rather than daily like in the documentation?

**Comment by vthornheart-bng** [comment]
Are you calling GetHistoricalStats to get at this data?

Unfortunately, we have a limit to the number of days that can be fetched in a single query (31).  Due to performance reasons, we can't currently allow for more than that in a single query: however, as an alternative you could make three queries and get each month in a separate request!  Try that out when you get the chance, and let me know if that resolves the issue for you!

**Comment by floatingatoll** [comment]
Does the documentation state this limit?

**Comment by vthornheart-bng** [comment]
It does not!  Good call, I'll add that in to the description of those properties.

**Comment by insanetron75** [comment]
I now do a loop through the daily objects for each 30/31 day period.  However the total kills doesn't add up.  For example my account has an allTimePvP kill count of roughly 18,000 but after going through each day until the end of season 5 my kill count sits around 9,000.  

Is there anyway to do something like an "forPeriod" or add back in the "monthly" objects to rule out any potential errors when looping?
