### ISSUE TITLE
Missing ActivityModeType for 'Last Wish' and 'In Orbit'

### ISSUE THREAD

**Issue by t3rr11** [Bungie-net/api#910]
When hitting `https://www.bungie.net/Platform/Destiny2/4/Profile/membershipID/?components=204` (CurrentActivity)

If you are currently in a Last Wish raid, It returns the 'Invalid hash' `2166136261` which leads to nowhere in the `DestinyActivityModeDefinition`

Also i would like to bring up that @vthornheart-bng mentioned you'd look into it back in https://github.com/Bungie-net/api/issues/552 

But never heard back after that. So the 'In Orbit' activity still returns the same mode hash as well. (2166136261)

**Comment by vthornheart-bng** [comment]
Hmm, interesting - is it returning invalid hash wherever you are in the Last Wish raid, or only in certain parts of it?

And indeed, I need to resolve that other issue: when you're in orbit, you're no longer actually in an activity at all, so the invalid hash in that situation is correct.  But Last Raid ought to have you in an activity.  I'd be interested in hearing if it shows you as being in the activity in some parts of the raid versus others!

**Comment by floatingatoll** [comment]
For the record, if you were to unilaterally declare Orbit an activity and give it its own ID, I know several people would enjoy that.

**Comment by vthornheart-bng** [comment]
That would require someone to change how Orbit currently works on the game side, and unfortunately I don't think that's going to happen.

**Comment by t3rr11** [comment]
Just ran a raid to test. Here is the results throughout the raid: 
**Landing**: ActivityHash: `2122313384` ModeHash: `2166136261`
** Before First Encounter**: ActivityHash: `2122313384` ModeHash: `2166136261`
** During First Encounter**: ActivityHash: `2122313384` ModeHash: `2166136261`
** After First Encounter**: ActivityHash: `2122313384` ModeHash: `2166136261`
** Before Second Encounter**: ActivityHash: `2122313384` ModeHash: `2166136261`
** During Second Encounter**: ActivityHash: `2122313384` ModeHash: `2166136261`

Going to submit this now, Still going through the raid, 4 Man, little hard to find a team before reset. But will make edits as we progress.

**Comment by vthornheart-bng** [comment]
Ah, I think I see what's going on now.  Thank you, this information was very useful!  I'm going to do a little digging, but we may be able to fix this up.  Hang tight.

**Comment by vthornheart-bng** [comment]
As the gold miner almost never said because it was pretty rare to actually find gold, "eureka"

I've found the issue - fortunately a configuration issue and not a game content issue! - that is causing this, and I'll see if I can get that into the next BNet deployment.  Thank you for providing this information!

It looks like there may be other activities that are likely returning bad mode hashes as well, I'll try to fix those where possible.

**Comment by t3rr11** [comment]
Sweet easy as! Glad i could help! I'll keep making edits, just in case there is something different. But it seems pretty clear at this point haha

**Comment by vthornheart-bng** [comment]
TFS 783459

Yes, it definitely was helpful!  And I get the feeling due to the nature of the underlying problem, you're almost certain to follow the existing pattern you're seeing as you play through the rest of the Raid.

It looks like this may also be a problem with two other raids as well as the FOTL forest and Revelry forest events, though since those last two already are mis-mapped in game content as "Story" activities I can't help much there.  But I will make sure they at least are populated as a "story" activity in this context as well, and I'll fix these Raids that are having the issue.

**Comment by t3rr11** [comment]
Yeah the forest was also returning the same hash. I had just assumed that was because it didn't have a modeType since it was 'temp' content. Also thanks for the really quick fix! :D

**Comment by vthornheart-bng** [comment]
<3

**Comment by lieuweberg** [comment]
The same thing happens in the Prophecy dungeon. activityHash is `4148187374` (prophecy), but activityModeHash is `2166136261`, instead of `608898761` normally used for dungeons.

**Comment by lieuweberg** [comment]
Hate potentially notifying a bunch of people, but the same is true for the Deep Stone Crypt (`910380154`). I've only tested it at the start, but I don't think it changes throughout the raid.

**Comment by lieuweberg** [comment]
Again, sorry for the emails people may receive. Seeing the same in Battleground: Behemoth (`1784138624`). Europa one (Hailstone) does have the correct activity mode.

**Comment by lieuweberg** [comment]
Vault of Glass also has this problem.
