### ISSUE TITLE
Please include DestinyHistoricalStatsDefinition in the JSON manifest

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#916]
Pleasssssssse

I know the hashes aren't real hashes and that grinds everyone's gears but but but but please 🙃

**Comment by vthornheart-bng** [comment]
I dig that idea - there's work we need to do in order to turn those into standard/"compliant" definitions that behave and are roughly formatted in the same way as the ones we expose externally - but I would like to see that come to pass.  It's definitely possible, we just need time to do that conversion to a form that would be as consumable externally as the current definitions are.
