### ISSUE TITLE
InstanceId to Full Instance Type

### ISSUE THREAD

**Issue by dyl10s** [Bungie-net/api#920]
Hello, this is more a question than an issue. How would I take an instance id and figure out exactly what strike, raid ect. that is.

**Comment by vthornheart-bng** [comment]
Ah, good question!  This is one of those subjects that I wish I had time to do a full tutorial or youtube video about or something.  To get to that data, you're going to need to do a few things.

The API comes in two fundamentally different parts: the "live" data such as PGCRs (where instance IDs, stats etc come from) and character/account/item data, and the "manifest databases": static SQLite databases that you can download, and that have all of the information about everything in the game that is unchanging: the "definitions" of every entity.

Every Entity that is defined in a static definition is referred to by a "hash": an unsigned integer value guaranteed to be unique for that specific type of entity.

Usually, in both the "live" and "manifest" data, these are referred to as hashes: for instance, if you're looking for an activity, you'll see properties like "activityHash" and if you look those up in the manifest databases, you'll find all the information we have about that activity.

Unfortunately, PGCRs don't have the same naming convention for historical/backcompat reasons.  The Hash identifier of the map that was played can be found in the pgcr's activityDetails.referenceId property.  If I had my druthers, I'd rename it to activityHash: maybe in the next major revision of the API we'll finally correct that, or have it listed twice and deprecate the old one.  But I digress!

For PvE activities, this should generally give you everything you need to know.  You can use that hash to look up the activity's data in the manifest database (which stores all that data as JSON.  It's a long story.) and get everything about it!

For PvP, it's a little more complicated because that activity is only the map that was being played, and not the mode.  You'll want to combine that data with the Activity definition from activityDetails.directorActivityHash to find out what mode was being played.

Check this out for more info about what we return for PGCR activities:

https://bungie-net.github.io/multi/schema_Destiny-HistoricalStats-DestinyHistoricalStatsActivity.html#schema_Destiny-HistoricalStats-DestinyHistoricalStatsActivity

And if you want to know the current path to the latest manifest databases, you can call this to get the URL to them (note that they change every release, as the files have a checksum appended to their names):

https://bungie-net.github.io/multi/operation_get_Destiny2-GetDestinyManifest.html#operation_get_Destiny2-GetDestinyManifest

Once you download it, it is - despite its file extension - a .zip file. (again, poor historical decisions that we have not undone due to backwards compatibility needs)  You will need to unzip it, and then its contents are a SQLite database that you can connect to and use as normal.

Final caveat: the API treats hashes as unsigned ints, but the SQLite database only knows about signed ints.  So the final frustrating bit is that you have to convert your uint into an int before making the query.  This is yet another point of frustration that I would love to resolve in a future iteration, ideally by providing a better source of truth than a SQLite database.  (we do expose JSON files, but they are huge.  If I get some time, I'd like to expose them as a file per entity, and then have people use that as the source of truth which would resolve the annoying uint-to-int problem we run into with the SQLite database)

That's the gist - I hope it is helpful!

**Comment by dyl10s** [comment]
Thanks!
