### ISSUE TITLE
How will account data be formatted once Shadowkeep comes out?

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#925]
I think everyone here will need to know as soon as humanly possible what changes are coming to the API so we can prepare for such a massive move.  My discord automation is designed to just work with PC players, so this is going to get interesting...  If there was a preview version of it with sample data we'd be in really good shape to keep all our apps up on launch day.

Can you divulge anything about this? 

Also, with the huge influx of players that will be coming, is there any plan to increase the clan limit from 100?

**Comment by floatingatoll** [comment]
To distill one specific answerable question from this that doesn't require
divulging any new information other than what's been made public —

Will Steam accounts have the same Platform ID as Battlenet accounts?

**Comment by Akumati1435** [comment]
more questions... cross saves... is it a transfer based thing or can we just play on any platform whenever?   if it's the later, will the activity itself tell us what platform they did it on?

i'm a PC based clan so if people are playing on ps4 that activity shouldn't count for my guys.  if they transfer off steam, i need to dispose of them.

**Comment by vthornheart-bng** [comment]
Oy, sorry folks!  I know you all have several burning questions.  I don't know if or what I'm allowed to say at the moment.  But I will loop back once I can.  I will ask about what I can talk about and get back to you all.

**Comment by floatingatoll** [comment]
No need to apologize :)

**Comment by vthornheart-bng** [comment]
Okay, I got the word - it's too soon for us to talk about the details now.  I will loop back once I get the thumbs up to talk more.

**Comment by Akumati1435** [comment]
I feel like this is the time you should get feedback from the community on how the API and move to steam should work.  Waiting till you tell us after it's set in stone could be disastrous for some of us. I care about my community a great deal, but if some of these concerns are not satisfied, communities like mine to call it quits.

Maybe after I post this I'll stop waking up in the middle of the night stressing over how I'm going to keep my community running.

I'm currently researching some of these concerns.  I don't know if they are legit or not.  I know you guys probably already have things setup the way in a way that will make this low effort and all I need to do is wait...  The first 2 questions only you will be able to answer _**(when you are allowed)**_.  The rest are general concerns that I'll be told to post on the forums for it to get buried and never read.

1) Is a person's 64 bit Steam ID going to be stored in the Bungie API? What information is going to be stored about a person for steam accounts?  If the 64 bit steam id is stored in bungie's api, this may simplifies things for third party developers.  You can get some publicly available information from steam's API, so even if you aren't storing what we'd prefer, we could still get it.

2) **How are people in game going to find each other and group up with them?** This might not sound like an API question, but however we connect to other people, imo, should be in the API in a user friendly way.  By users, I mean you're end users, not the API developers.  Currently it's a bug that you can actually get a persons battletag from the bungie API and when the tag is changed, it can take weeks to update in that specific place.  You currently only have a non-unique identifier for a username in most places (because blizzard) and we can't use it to group up with people. **I guess what I'm getting at is that a person's human readable account name, that can be used to quickly group up with others, should be in the API.**

3) This might not be a question for you, but it is a major concern.  What's going to be displayed in game for a person's name? Would it be what a person sets as the custom URL, then with a fallback of the steam account name (which cannot be changed and seems like a terrible idea)?  Will it be their profile name which they can change whenever and to whatever they want? Like for in clan chat, do I need to worry about someone setting their custom URL or profile name to "xP4ssyl1ck3r69x" or something racist? They could change their profile name to that, log in, say something stupid, log out, and change their name again.  This would make it near impossible to find and ban disruptive people we do not want in our community. 

I mentioned this because for most steam games I've played, that is how it works.  You can set your name to whatever you want and it is displayed in the game. You can also change the custom URL whenever you want, but at least that is something unique which Bungie API users can display to their end users if the end user doesn't have the field empty. The fact that you aren't required to set the custom URL means it can't be used for this. If we're grouping up with people through a unique bungie account name, then I might be in better shape, but I'd have the same concern as in the previous paragraph if they can change it for free. **I need tractability for what my members are doing if we're going to run smoothly. This is something I think should be available to me in the API.**  We are discord partnered and the standards are very high.

I'll clarify why I think the real steam name used to log into your account is a terrible idea.  **If this isn't how it will be, just skip this section.**
A) They already have your username so it's easier to try to hack someones account.
B) According to [steam](https://support.steampowered.com/kb_article.php?ref=1558-qyax-1965), you cannot change your account name or merge two accounts. That means that if someone has their name set to something racist or NSFW (xP4ssyl1ck3r69x), they cannot join my clan.
C) Most people set their steam IDs when they were young.  A bunch of people probably don't want what they picked in 2004 to be displayed to everyone.  Another thing is that **their account name might be something that people can use to dox them with**.  Take me for example... I'm running a massive clan and not everyone is mentally stable.  We've even had people with previous suicide attempts seriously saying they are about to kill themselves IN VOICE COMMS.  If I have to ban someone who has anger issues and is mentally unstable, they'd be able to DOX me if my primary steam account name is displayed in the game.

4) **I have 10 accounts**. There's one in each clan and most are battle.net accounts.  I didn't see anything in steam's ToS about not being allowed to have multiple accounts, but when you go to make a new account, it says "Please only create a new Steam account if you don't already have one". With the quantity of accounts I'm going to need, it's a concern. Like, if they ban all my accounts for it, my clan is 100% screwed.  I'm going to get in contact with steam and if I get an answer, I'll post it back here.  Most major clans will have a problem if we can't transfer all our alt accounts in all our clans unless we can leave them as battle.net accounts.

5) Completely out of your scope, but... The steam subscriber agreement(SSA) says: 
> You agree that you will not use IP proxying or other methods to disguise the place of your residence, whether to circumvent geographical restrictions on game content, to purchase at pricing not applicable to your geography, **or for any other purpose.**
When you get to higher ELOs in comp, you are going to get DOS'ed every once in a while.  This takes away from the fun of the game and makes comp really aggravating at the highest levels.  VPNs protect you.   A lot of my high skill PVPers use VPNs when they get to higher ELOs.  Since the SSA says not to do this, people risk getting banned to avoid getting DOSed.

**I know some of these questions are not in the scope of your job and I'm sorry I'm basically just ranting about it here.  I know that some of these questions you will not be able to answer, and that others will be answered in due time.** My hope is that this gets forwarded to people in your company who can see this feedback.  If they don't get back to me, I won't take offense to it.  I'm just very worried about this change from an administration standpoint.  I've been completely unable to get a real contact inside your company.  The guy in PR at my company that was going to help is just full of promises and never follows through with anything. I know you're doing your job very well because the API runs smoothly (and the documentation is on point), but your company's customer relations, especially with people like me who literally volunteered 8 months of their life automating and building the highest activity clan system you have, is non-existent. That to me is completely unacceptable.  It gives the illusion that you guys don't care about anything we do for you (for free). That is why my off topic question here exists.  A position is open at Bungie where I might be able to fix some of these problems and that is very tempting to me.  There are so many things you guys do **extremely well**, but a few where you guys fall into a hole as deep as the grand canyon.

Again, that is not a shot at you.  I'd buy you a god damn steak dinner if I was ever in Seattle.  I get it.  This isn't your job.  I guess I just feel unappreciated by your company as a whole.

**Comment by floatingatoll** [comment]
As an outsider and I’m not Bungie —

The existence of clan systems at all (as I’ve learned from watching API github) has made me more uncomfortable and nervous when interacting with my existing clan, because I’m constantly afraid that I won’t live up to the kind of expectations from others that I see your clan system track and enforce in military-regimented style.

I bring this up to help you realize that the system you’ve built is not necessarily healthy for everyone’s enjoyment of Destiny. While I certainly understand that it is enjoyable for you and those in your regiments, I would be terribly sad if this system were available to all Destiny players, and shy away from clans altogether if it were.

**Comment by Akumati1435** [comment]
Everyone is allowed to have their opinions of it. 

We all know Destiny 2 is a very high turnover game. The content runs dry or we get season of the Gambit... then they get bored and move on to other games. If we could have more than 100 members in a clan it wouldn't be as strict. More people + less activity per person can equal the same amount of activity per clan.

 In d1, I was in a clan where I couldn't do a raid unless everyone was online, which was rare.  It made the game less fun.  If I want to do a raid I should be able to get a group quickly.  I should be able to find people to do my 100k nightfall without having to search high and low to find people to help.  If I want to learn a raid, I should be given the opportunity to do so.  Our level of activity fixed my biggest problem in the game... Finding groups so I can have fun in this game.  Being a clan discord, we don't tolerate toxicity as much as the lfg servers.  Maybe us not putting up with people's nonsense makes us more military like.  At one point half of our leaders we're ex-millitary.  

We have gotten through to some kids though and they have truly changed since joining. One opened up in our sad channel when he first joined.  After a couple months of making friends in our discord he told us this clan has helped him in more ways that we could have imagined.  Some have gone from insecure kids to confidence and a girlfriend. Someone joined after multiple people in his family died very suddenly and he needed a distraction from it....  others have told me the clan has kept a gun out of their hands when they were going through a rough patch.  Everyone has problems, and video game communities are a great way for us to forget about them.

 In college I was pretty depressed without really knowing what that was.  Guilds in wow were extremely important to me.  It distracted me from thinking about how much I hated my life. I'm trying to return the favor. 

Even after doing all this work for them, I'm still told we need to post problems publically on the forums.  The forums are jam packed with trolls and it seems like they aren't moderated.  I know they are, but it needs more of it. 


This clan isn't for everyone.  It is for those who expect people to be just as active as they are.  That's why they join.  If someone goes inactive for 2 weeks without telling us, we replace them to keep the activity up to their standards.  

Imo, our activity requirements are very minimal.  It's an average of 2.5 completed activities per week and 15 minutes in voice.  It's based on a 2 week period. If they go inactive for 2 weeks straight, they get replaced. They all understand this when they join.  Before our bot started messaging people we kick for us, the most common response when I told people was along the lines of "yea that is fair". If they want to rejoin, all they need to do is spend 30 minutes in voice chat and they're back in.  So many clans have died off and I don't want mine to join the list.

**Comment by floatingatoll** [comment]
I like your motivations, even if I don’t fit well with the result. Thank you for taking the time to write them up.

**Comment by Akumati1435** [comment]
I just edited it a lot too... was typing that up on my phone and my hand got a cramp -_-

**Comment by vthornheart-bng** [comment]
Just to loop back - I'm asking around about these Steam questions as well.  I don't know if we're ready to talk about these yet, and everything is still in the works.  But when we're able to talk more about those I'll swing back here with more info.

**Comment by vthornheart-bng** [comment]
Finally got the thumbs up to give more info:

https://github.com/Bungie-net/api/wiki/Blizzard-to-Steam-Migration,-how-it-will-affect-the-API

**Comment by ckhicks** [comment]
Just catching up on this - I'm super excited for: "Membership ID is the only identifier you need to uniquely identify a Destiny Profile" 💯
