### ISSUE TITLE
Result of GetVendor for Tess Everis not in sync with actual in game sale items

### ISSUE THREAD

**Issue by xenodus** [Bungie-net/api#963]
I'm getting items like Popcorn emote (40 Bright Dust) and Vanishing Point sparrow (50 Bright Dust) in my results as show in the image below.

![image](https://user-images.githubusercontent.com/9331270/60966747-845be380-a34b-11e9-9e89-a22581b8ee77.png)

Thought it could be just my side but noticed DIM showing similarly strange results too at https://app.destinyitemmanager.com/#/4611686018474971535-4/d2/vendors

![image](https://user-images.githubusercontent.com/9331270/60967213-b3268980-a34c-11e9-8adf-5f53ed70e475.png)

Issue only started after latest patch (9 July). Thanks =)

**Comment by vthornheart-bng** [comment]
Hmm, interesting!  Thanks for reporting this, I'll have to take a peek shortly.

**Comment by vthornheart-bng** [comment]
Did a bit of investigating, and it turns out that this is due to a temporary issue we're experiencing, where the Destiny API content is mismatching (lagged behind) the game content, causing incorrect data to be returned for Vendors in particular.

I'm going to have to turn off Vendors temporarily until this is resolved.  I'll hit a broader audience about this to make sure they know this is happening.

**Comment by jshaffstall-bng** [comment]
Should be fixed now!

**Comment by xenodus** [comment]
Same issue is back!
