### ISSUE TITLE
Unexpected EquipItem Failure [help wanted]

### ISSUE THREAD

**Issue by HeroicosHM** [Bungie-net/api#966]
I am relatively new to the Bungie API and I was playing around with a simple EquipItem request in Python. The code for this is here:

```python
headers = {
    'X-API-Key': '05a8625c739d40baab0e739999e4a99d',
    'Authorization': 'Bearer {access_token}'
}
data = {
    "itemId": 6917529091310483017,
    "characterId": 2305843009402927792,
    "membershipType": 4
}
res = requests.post('https://www.bungie.net/Platform/Destiny2/Actions/Items/EquipItem/', data = data, headers = headers)
```

The result that I receive from this post request is:
```
{"Response":0,"ErrorCode":30,"ThrottleSeconds":0,"ErrorStatus":"JsonDeserializationError","Message":"There was an unexpected problem decoding the input data.","MessageData":{}}
```

I do not understand where it is in here that I have made a mistake. I am sure that my access_token is up to date and valid, I have used it successfully for other requests less than 2 minutes previously. I have also checked to make sure that my character id and the item instance id are correct, and I am fairly certain that the membership type refers to the Destiny 2 membership type, which is 4 for pc, but just in case I tried both 4 and 254 (the Bungie.net pc membershipType). Since these arguments are all correct there has to be some error with how my data is formatted, but I am unable to see any issues. Please help me, and thank you in advance.

**Comment by arshakoor** [comment]
You'll want to use `json` instead of `data`, so your last line should instead read:
`res = requests.post('https://www.bungie.net/Platform/Destiny2/Actions/Items/EquipItem/', json = data, headers = headers)`

Alternatively, you could specify `'Content-Type': 'application/json'` in your headers, as if you do not use the `json` parameter, the `Content-Type` will be `application/x-www-form-urlencoded`. In this case, you'd also have to pass `data = json.dumps(data)` so you pass the deserialized JSON instead of the dictionary.

**Comment by HeroicosHM** [comment]
Thank you, the tips are much appreciated.
