### ISSUE TITLE
Moments of Triumph 2019 seals’s completion record’s data isn’t being returned by the API

### ISSUE THREAD

**Issue by justrealmilk** [Bungie-net/api#968]
I use the completionRecord data in numerous places on Braytech i.e. `profileRecords[definitionSeal.completionRecordHash]`

![image](https://user-images.githubusercontent.com/156681/61034673-09590280-a409-11e9-9b8f-cd109efcf04f.png)

As you can see, it's undefined 😭

**Comment by justrealmilk** [comment]
Not heard Peter Dinklage in this game for a little while
_Do you think he's Ghosting us?_

**Comment by floatingatoll** [comment]
It seems worth mentioning that Thorn is busy preparing for cross-save, and warned us he might be quite delayed responding.

If you wouldn't mind skipping the joke-updates as a form of "ping, no reply since I filed this" comments, since they're emailed to 66 other people besides you and Thorn, I would personally really appreciate that as one of those 66 others.

**Comment by SunburnedGoose** [comment]
I don’t mind a good joke. 😉

**Comment by vthornheart-bng** [comment]
TFS: 811429
