### ISSUE TITLE
Can i get activity name by hash without downloading manifest?

### ISSUE THREAD

**Issue by Arasfon** [Bungie-net/api#969]

**Comment by DeCoded-Void** [comment]
I do not believe so since a majority of the hash info are stored in that manifest.

Depending on what you are trying to do, you can download the manifest and save it locally until a new version of the manifest comes out so it doesn't download+load it everytime. 
It's good practice to do so in case any new activities come out.

**Comment by vthornheart-bng** [comment]
Indeed, unfortunately the least bandwidth intensive way for you to get at it is by downloading the manifest.  There is an endpoint you can hit - GetDestinyEntityDefinition - if you *really* have a good scenario for grabbing one-off definitions.  But I discourage it if it's not something super simple, for instance if you have a page that needs a single activity's definition.  It's not an expensive call, but the extra bandwidth costs to you will add up over time if you're grabbing the same definitions over and over.

**Comment by floatingatoll** [comment]
(Also, that endpoint would be charged against your API rate limit, where the manifest contents wouldn’t be.)

**Comment by vthornheart-bng** [comment]
Yes, very true and good point!

**Comment by Arasfon** [comment]
Thanks for answers!
