### ISSUE TITLE
[Question]How to get reward related with nightfall?

### ISSUE THREAD

**Issue by atheon-v** [Bungie-net/api#974]
Hi Guys!
I checked manifest content and didn't find way to see nightfall rewards. I thought "DestinyRewardSourceDefinition" table will contains that info, but table is empty, and there is no reward info in nightfall's "DestinyActivityDefinition" json.

Is there any place in manifest to get this info?
Thanks!

**Comment by kdeun1** [comment]
I did not know well, so I configured data myself.

```
-- | -- | -- | --
nightfall | major element | minor element | reward
-- | -- | -- | --
Lake of Shadows | solar | arc(little), void(little) | The Militias Birthright
The Arms Dealer | void | arc(many), solar(little) | Tilt Fuse
The Pyramidion | arc | solar(little), void(many) | Silicon Neuroma
Exodus Crash | arc | solar(little),   void(little) | Impact Velocity
The Inverted Spire | arc | solar(little), void(many) | Trichromatica
Savathûn's Song | arc | solar(little),   void(little) | Duty Bound
A Garden World | arc | solar(little), void(many) | Universal Wavefunction
Tree of Probabilities | arc | solar(1), void(many) | D.F.A.
Strange Terrain | arc | solar(little), void(X) | Braytech Osprey
Will of the Thousands | arc | solar(little), void(X) | Worm God Incarnation
The Insight Terminus | void | arc(little),   solar(little) | The Long Goodbye
Warden of Nothing | void | arc(1), solar(1) | Wardens Law
The Hallowed Lair | solar | arc(little), void(1) | Mindbenders Ambition
The Corrupted | solar | arc(many), void(many) | Horrors Least
-- | -- | -- | --
```

**Comment by atheon-v** [comment]
Thanks @kdeun1! It's weird that this data may be only "hardcoded", NF reward looks pretty static info with one-to-one relation with activity, as result i thought reward may be linked in manifest.

**Comment by delphiactual** [comment]
You have to look at the collectible version

https://data.destinysets.com/i/Collectible:1602518767

**Comment by atheon-v** [comment]
Thanks @delphiactual !
I see 2 rows there which may be needed link:

sourceString:"Source: Complete Nightfall strike "Lake of Shadows.""
sourceHash:2851783112

but not sure what is "sourceHash". I tried to use that for DestinyActivityDefinition and didn't find "Lake of Shadows".

**Comment by vthornheart-bng** [comment]
Unfortunately, we don't provide much in the way of reward information (and in many cases, we can't).  Collectibles are one of the few places we can return that information, because the game designers have explicitly allowed those to be returned in that format.  If it's not in there, we generally won't be able to return it more than in a vague form, such as the "Powerful Rewards" dummy item that you'll often see as the rewards being provided for Milestones.

As far as the sourceHash goes, it unfortunately doesn't link to a separate definition.  It can potentially be used to group collectibles together by source as long as the game designers used the same identifier for collectibles that come from the same source, but we can't make guarantees that they did that.  Here's the info from the [documentation](https://bungie-net.github.io/multi/schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition.html#schema_Destiny-Definitions-Collectibles-DestinyCollectibleDefinition):

_This is a hash identifier we are building on the BNet side in an attempt to let people group collectibles by similar sources.

I can't promise that it's going to be 100% accurate, but if the designers were consistent in assigning the same source strings to items with the same sources, it *ought to* be. No promises though.

This hash also doesn't relate to an actual definition, just to note: we've got nothing useful other than the source string for this data._

**Comment by floatingatoll** [comment]
To add some backstory to Thorn’s first paragraph here —

The game designers control what the API team is allowed to share with us, and in the past have required the API team to protect and/or remove information so that it is not shared with us through the API. This is not due to “technical inability” or “it isn’t clear what we would like from the API team”, but simply due to “conscious game design choices to deny that in the API”, and you will see that come up now and then when asking about quests, rewards, and so forth.

This creative control has been wielded to mark items and quests as “classified” during the initial weeks of a new content release, which generally makes sense. This has also been used to hide Xûr’s location — without allowing the API team to share the detailed reasoning with the community.

So it’s fine to ask for anything you’d like from the API, but the API team can and sometimes do say “no, and we aren’t going to explain why”, and that’s outside of their control when they do.

**Comment by atheon-v** [comment]
Ok, got it and the reason make sense.
Thanks @vthornheart-bng and @floatingatoll for clarification!
