### ISSUE TITLE
Scourge of the past have "placeHash" = 0

### ISSUE THREAD

**Issue by Arasfon** [Bungie-net/api#976]
DestinationHash seems to be normal as number, but have no data.
Is it normal or bug?

**Comment by vthornheart-bng** [comment]
Yes - so unfortunately, this activity takes place in the Last City itself, and it does not appear to have been given an actual Place definition in content.  It has a bare-bones Destination definition, but was never given a full one of those either.

Ideally I'd like to see the game content include this data, but because they don't need it it isn't likely we're going to be returned this data either.  I would call it a bug, but not one that is likely to be fixed unfortunately due to this reason.  I will bring it up to folks on the game side though, so that they will at least consider including this data for all activities in the future even if they won't fix this one.
