### ISSUE TITLE
DestinyHistoricalStatsActivity.membershipType is always 0

### ISSUE THREAD

**Issue by as-com** [Bungie-net/api#978]
^ title

Here are some PGCR IDs where I have seen this; it appears they are all zero.
4301955761 (cross-save)
4302496725 (Xbox)
4302519473 (PS4)
4302521478 (PC)

**Comment by vthornheart-bng** [comment]
Thank you for this report, I'll go take a look and file a bug!

**Comment by vthornheart-bng** [comment]
A heads up for folks who wanted to use this field - a bug has been discovered that may not potentially be fixable in entirety until after Shadowkeep launches.  We may be able to get this field to populate correctly in some situations, which I'm still looking into - but unfortunately it is going to be inconsistent without fixes to a deeper system in the Stats infrastructure.

I will keep folks posted once I know more about the timeline for a fix, but this does mean that for Cross Save-inclusive PGCRs created between now and when this bug gets fixed, you will not be able to identify the platform on which they were played.

**Comment by floatingatoll** [comment]
To confirm, the platform field will either be blank or be correct - but never incorrect?

**Comment by vthornheart-bng** [comment]
Yes - if you're getting a nonzero value, it'll be the right one.  It's just going to be very inconsistent in terms of when you get the right value (and for now, they'll all be zero.  I'm working on at least a partial fix that can go out earlier, but it won't be of much use unless the underlying issue is fixed).

**Comment by mistahj67** [comment]
I realize it may be too early to tell and you likely don't want to make promises and end up not keeping them. I fully do not hold you to your response one way or another but can you say based on your current knowledge if like previous fixes to game modes that were retroactive to the pgcrs, if this will retroactive as well where we can plan on correcting the 0 pgcrs once the bug is sufficiently squashed?

**Comment by vthornheart-bng** [comment]
Unfortunately, the ones that still come through as 0 after I fix the part of the issue that I can fix on the BNet side will remain 0 indefinitely: we won't be able to retroactively fix them.  Which is a bummer, and I apologize for any inconvenience that will cause for those of you looking at platform specific information.  Unfortunately, the 0's that will stay 0's will be for games played with cross saved accounts, which are the exact ones for whom we'd like to have this information.
