### ISSUE TITLE
Trying to kick a user and getting GroupMembershipNotFound

### ISSUE THREAD

**Issue by dyl10s** [Bungie-net/api#991]
I am trying to kick a user I have the correct auth and was able to accept the user in the Clan but then when I try and kick them I get the following:

{
  "ErrorCode": 611,
  "ThrottleSeconds": 0,
  "ErrorStatus": "GroupMembershipNotFound",
  "Message": "GroupMembershipNotFound",
  "MessageData": {}
}

**Comment by vthornheart-bng** [comment]
Interesting - if you can, could you give me the clan's Group ID and the user's Membership ID, and the JSON post data you're sending with the request?  That'll help me spot if it's a problem with our underlying data, or potentially an issue with the JSON data coming upstream to us.

**Comment by dyl10s** [comment]
Here is the exact url

**Comment by vthornheart-bng** [comment]
A couple of potential avenues for exploration!

The first one is the /Members/2/ portion of the URL - at user's actual membership type is 4, and the request may not succeed if they mismatch: GroupMembershipNotFound could have been due to this mismatch if the member was part of the group when you made the attempt.

However, looking in the data it appears that membership ID's clan is a different ID than 3601200 - is it possible that they left your clan in the interim and joined a different one?

**Comment by vthornheart-bng** [comment]
Hmm, scratch that.  Something interesting is going on in there with this account, I'm going to continue investigating.

**Comment by vthornheart-bng** [comment]
Okay, I was looking at the wrong internal ID.  That all looks okay now that I've looked deeper.  Yes, try it again but with the membership type field set to 4!

**Comment by dyl10s** [comment]
Whoops ya that was the issue. I was using the clan memberType and not the membershiptype.

**Comment by vthornheart-bng** [comment]
Sweet, glad that helped!
