### ISSUE TITLE
MMXIX title storage location may be wrong

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#996]
When you make a get profile call and ask for the records, it returns a profileRecords section and a characterRecords section.  All the titles I've grabbed from the API previously have been in the profileRecords section, but the MMXIX title is stored in the characterRecords section.  I asked some of the people in my clan with the title if it was character specific and they said it isn't, so I'm thinking this was a mistake?

(example call: http://destinydevs.github.io/BungieNetPlatform/docs/API-Test#/Destiny2/GetProfile/p:membershipType=4,destinyMembershipId=4611686018467454614/q:components=900)

example title hashes:

3369119720 | Unbroken
3798931976 | Dredgen
2182090828 | Rivensbane
1693645129 | Cursebreaker
1754983323 | Chronicler
2053985130 | Blacksmith
2757681677 | Wayfarer
4177910003 | Petra's Run
1313291220 | Reckoner
1883929036 | Shadow
**2254764897 | MMXIX**

**Comment by vthornheart-bng** [comment]
Ooh, yeah let me take a look into that!  We run some heuristics to try and discern whether any aspect of the Record is character-centric, but we've definitely had bugs with it before.

**Comment by vthornheart-bng** [comment]
Ah, yes - this is indeed not an ideal situation.  Some of the state related to this Triumph has a scope that we cannot determine programmatically: that is to say, we have no automated way of knowing if this scope is only affected by account state or if it could be affected by character state as well, so we are defaulting to the widest scope possible to avoid returning character-specific data as if it is account wide.  You can actually see it in action on the scope of the Objective definition attached to that Triumph.  It's set to Scope 6 (AssumedWorstCase), and it's because there's a value calculated as part of the objectives that is set in a way that our scoping algorithm doesn't account for - in this case, in a way that we can fix thankfully!

However, while we can fix this situation I have to stress that I can't guarantee that we will ever have a perfect heuristic for this scoping: this category of bug can sometimes be the result of state being set in ways that we can't control and have no ability to reason about programmatically.  In those situations, you will still see Triumphs (and other data) that is - for all practical purposes - account scoped but that comes down in character scoped data.  I believe that I can fix this specific instance and it may fix some others by coincidence, but we'll definitely still hit this in other situations.  

The only workaround I can prescribe that would work without fail would be to either always show or use record data in the context of a specific character (rolling Account scoped records in with that character's records), or apply your own heuristic if you are looking for specific records and know that you expect it to be account wide.  I highly recommend the former if at all possible: the split between account and character was originally intended only to minimize the set of duplicate data we return from the API, and not to be a canonical reference as to which Triumphs are character based vs. account based (mainly due to this fact that we can't guarantee absolute knowledge of how certain states are set in game, and thus have to fall back to this "worst case").

**Comment by vthornheart-bng** [comment]
TFS 817503

Fixed for an upcoming deployment - TBD on specific date, but the fix should be live before September.

**Comment by Akumati1435** [comment]
thanks.  i hard coded a fix for now.  if it happens again in the future i'll have to make a fallback mechanism for when it cant find it in the account section.

**Comment by vthornheart-bng** [comment]
Aye, good deal!

**Comment by joshhunt** [comment]
@Akumati1435 For what it's worth, what I do for Records/Triumphs/Seals is that I basically reduce the records from all characters + account together, with the most 'complete' value taking precedence (a complete triumph on a warlock won't be overriden by it being incomplete on hunter, if that occurs in the data).

I've found that this solves a few issues. It would be awesome if Bungie API did this for us  https://github.com/Bungie-net/api/issues/758 😄

**Comment by t3rr11** [comment]
I feel like here might be an appropriate place to bring this up (hopefully not mentioned elsewhere) the Record Definition: `2254764897` has the Shadow title icon, whilst the Presentation Node: `1002334440` has the actual icon for the MMXIX title. 

![image](https://user-images.githubusercontent.com/2139233/63260966-7e99dc00-c2c1-11e9-9498-92b2b570c3a8.png)

@vthornheart-bng
